#infranet.connection=pcp://root.0.0.0.1:@192.168.56.101:11960/0.0.0.1 /service/admin_client 1
infranet.login.type=1
infranet.log.level=1
infranet.log.file=./pin_sepa.pinlog

# Path for xml document generation
infranet.sepa_dd_req_dir.path=/home/pin/opt/portal/BRM/apps/pin_sepa/sepa_dd
infranet.sepa_ct_req_dir.path=/home/pin/opt/portal/BRM/apps/pin_sepa/sepa_ct
infranet.sepa_rev_req_dir.path=/home/pin/opt/portal/BRM/apps/pin_sepa/sepa_rev

# Path for response xml documents
infranet.sepa_resp_dir.path=/home/pin/opt/portal/BRM/apps/pin_sepa/sepa_resp/input

# Threading Parameters - Performance Tuning
infranet.threadpool.size=3
infranet.threadpool.maxsize=5
infranet.threadpool.fetchsize=100

# Specify the Chargebearer. The value could be one of the following:
# DEBT, CRED, SHAR, SLEV
infranet.sepa.sddrequest.ChrgBr=SLEV
infranet.sepa.sctrequest.ChrgBr=SLEV
infranet.sepa.sddreversal.ChrgBr=SLEV

# Specify the instruction priority
infranet.sepa.sddrequest.InstrPrty=NORM
infranet.sepa.sctrequest.InstrPrty=NORM

# Specify the payment method
infranet.sepa.sddrequest.PmtInf.PmtMtd=DD
infranet.sepa.sctrequest.PmtInf.PmtMtd=TRF

# Date on which the creditor requests that the amount of money is to be collected from the debtor.
# File must be submitted at least 6 days in advance of this date for first collections and atleast
# 3 days in advance of this data for subsequent collections. Cut off times also apply.
# Date Pattern=YYYY-MM-DD
infranet.sepa.sddrequest.ReqdColltnDt.pattern=yyyy-MM-dd
#infranet.sepa.sddrequest.ReqdColltnDt.value=1984-04-08
infranet.sepa.sctrequest.ReqdExctnDt.pattern=yyyy-MM-dd
#infranet.sepa.sctrequest.ReqdExctnDt.value=1984-04-08

# To enable SSL, make sure to provide correct values for below config entries. e.g wallet location and filename etc.
infranet.pcp.ssl.enabled = false
infranet.pcp.ssl.wallet.location = /home/pin/opt/portal/BRM/wallet/client
infranet.pcp.ssl.wallet.filename = cwallet.sso

# Specify Name and Id of the Initiating Party.
#infranet.sepa.sddrequest.InitgPty.Nm=
#infranet.sepa.sddrequest.InitgPty.OrgId=
#infranet.sepa.sctrequest.InitgPty.Nm=
#infranet.sepa.sctrequest.InitgPty.OrgId=
#infranet.sepa.sddreversal.InitgPty.Nm=
#infranet.sepa.sddreversal.InitgPty.OrgId=

infranet.sepa.sddrequest.PmtTpInf.LclInstrm=CORE
infranet.sepa.sddrequest.PmtTpInf.SvcLvl=SEPA
infranet.sepa.sctrequest.PmtTpInf.LclInstrm=CORE
infranet.sepa.sctrequest.PmtTpInf.SvcLvl=SEPA

#Custom class Implementation for Sepa DD/Sepa CT/Sepa reversal
#infranet.sepa_dd_custom_class=com.brm.customDD.class
#infranet.sepa_ct_custom_class=com.brm.customCT.class
#infranet.sepa_reversal_custom_class=com.brm.customRev.class

