#infranet.connection=pcp://root.0.0.0.1:@192.168.56.101:11960/0.0.0.1 /service/admin_client 1
infranet.login.type=1
infranet.log.level=1
infranet.log.file=/home/pin/opt/portal/BRM/var/pin_job_executor/pin_job_executor.pinlog
infranet.log.logallebuf=true
 # Enable following entry to perform invoice rendering.
infranet.job.rendering=true
 # To enable SSL, make sure to provide correct values for below config entries. e.g wallet location and filename etc.
infranet.pcp.ssl.enabled = false
infranet.pcp.ssl.wallet.location = /home/pin/opt/portal/BRM/wallet/server
infranet.pcp.ssl.wallet.filename = cwallet.sso
infranet.opcode.handler.JOB_EXECUTE=com.oracle.communications.brm.pje.JobOpcodeHandler
infranet.pje.executable.locations=bin,apps
infranet.server.portNr= 31960
infranet.threadpool.size=5
