#ifndef rw_xmlstreams_RWXmlObjectOutputStreamImp_h_
#define rw_xmlstreams_RWXmlObjectOutputStreamImp_h_

/*********************************************************************
 *
 * $Id: //spro/rel2016.1/rw/xmlstreams/RWXmlObjectOutputStreamImp.h#1 $
 *
 * Copyright (c) 1996-2016 Rogue Wave Software, Inc.  All Rights Reserved.
 * 
 * This computer software is owned by Rogue Wave Software, Inc. and is
 * protected by U.S. copyright laws and other laws and by international
 * treaties.  This computer software is furnished by Rogue Wave Software, Inc.
 * pursuant to a written license agreement and may be used, copied, transmitted,
 * and stored only in accordance with the terms of such license agreement and
 * with the inclusion of the above copyright notice.  This computer software or
 * any other copies thereof may not be provided or otherwise made available to
 * any other person.
 * 
 * U.S. Government Restricted Rights.  This computer software: (a) was
 * developed at private expense and is in all respects the proprietary
 * information of Rogue Wave Software, Inc.; (b) was not developed with
 * government funds; (c) is a trade secret of Rogue Wave Software, Inc. for all
 * purposes of the Freedom of Information Act; and (d) is a commercial item and
 * thus, pursuant to Section 12.212 of the Federal Acquisition Regulations (FAR)
 * and DFAR Supplement Section 227.7202, Government's use, duplication or
 * disclosure of the computer software is subject to the restrictions set forth
 * by Rogue Wave Software, Inc.
 *
 ********************************************************************/

#include <rw/xmlstreams/RWXmlObjectStreamCommon.h>
#include <rw/xmlstreams/pkgdefs.h>
#include <rw/serial/RWDataToVirtualOutputStreamImp.h>
#include <rw/serial/RWObjectOutputStream.h>
#include <rw/serial/RWObjectOutputStreamImp.h>
#include <rw/stream/stream.h>
#include <rw/pstream.h>
#include <rw/rstream.h>
#include <rw/rwstore.h>
#include <rw/tools/bustring.h>
#include <stack>

#if defined(_MSC_VER)
#  pragma warning(push)
#  pragma warning(disable : 4251)
#endif

//--The class 'RWXmlObjectOutputStreamImp' writes objects as XML
//--into the supplied 'RWDataOutputStream'.
//--
//--The format of this stream is detailed in the file 'xmlstreams.xsd'.
//--Implements the body idiom from the handle/body pattern.
//--
//--Example:
//--
//--// Create a stringstream to serve as our sink
//--std::ostringstream s;
//--
//--// Create an XML data stream using the stringstream
//--RWObjectOutputStream in = RWXmlObjectOutputStreamImp::make(s);
//--
//--// Write integer value '1' to XML data stream
//--s << 1;
//--
/**
 * \ingroup xmlstreams_package
 *
 * \brief
 * Serializes one or more objects as an XML-formatted data stream and passes
 * the stream to a supplied RWDataOutputStream.
 *
 * The class RWXmlObjectOutputStreamImp serializes one or more objects as an
 * XML-formatted data stream and passes the stream to a supplied
 * RWDataOutputStream.
 *
 * The XML Streams Module integrates with the general Rogue Wave streams
 * architecture defined by the streams and serialization packages of the
 * Advanced Tools Module of SourcePro Core. This architecture allows an XML
 * stream to be written out and read in using a wide variety of streaming
 * configurations. For more information specific to the XML Streams Module,
 * see the XML Streams Module User's Guide. For information on the general
 * architecture, see the <em>Advanced Tools Module User's Guide</em>.
 *
 * RWXmlObjectOutputStreamImp is the body class of a handle-body pattern.
 * The corresponding handle class is RWObjectOutputStream.
 *
 * The syntax of the XML formatting generated by this class is defined by
 * the XML schema \c xmlstreams.xsd. This schema is located in
 * <tt>buildspace\\rw\\xmlstreams</tt>.
 *
 * \example
 * \code
 * // Create a strstream as the output stream to receive
 * // the XML-formatted object data
 * ostrstream s;
 *
 * // Create an XML data stream using the strstream
 * RWObjectOutputStream out = RWXmlObjectOutputStreamImp::make(s);
 *
 * // Write integer value `1' to XML data stream
 *
 * s << 1;
 * \endcode
 * \endexample
 */
class RW_XMLSTREAMS_GLOBAL RWXmlObjectOutputStreamImp : public RWObjectOutputStreamImp,
    public RWXmlObjectStreamCommon
{
protected:
    RWStoreTable*         table_;
    unsigned              indent_;
    RWCString             rootElementType_; // should be one of object, object-nested, sequence, primitive, or map
    bool             objectPointerFlag_;
    bool             escapeText_;
    std::stack<bool> objectStack_;

    virtual void          openOuterContext(bool writeContext);
    virtual void          closeOuterContext(bool writeContext);

    //--'Ctor' takes an 'ostream' to use as the destination,
    //--Parameter 'rootElementType' should be one of objectTag, nestedObjectTag,
    //--sequenceTag, primitiveTag, or mapTag, depending on what sort of object is streamed
    //--into the document at the top level.
    /**
     * Used by the make() function and potentially by derived classes to
     * initialize an output stream to be used as the sink for the
     * XML-formatted object serialization data. Use this constructor if the
     * required output stream is a standard library ostream and pass a
     * reference to that stream as the \a ostr parameter.
     *
     * The parameter \a rootElementType must be one of the following:
     *
     * - #nestedObjectTag, if serializing an object by value
     * - #objectTag, if serializing an object by pointer
     * - #sequenceTag, if serializing a sequential collection such as
     * RWTPtrOrderedVector
     * - #mapTag, if serializing a mapping collection such as RWTPtrHashMap
     * - #primitiveTag, if serializing a built-in type such as \c int
     *
     * The value passed indicates the root element of the generated
     * document.
     *
     * The parameter \a escape sets whether to escape XML reserved
     * characters in the data being serialized. By setting this parameter to
     * \c true, reserved characters in \c char and \c string values are
     * escaped, allowing the data to include embedded XML.
     *
     * The reserved characters are:
     *
     * \code
     * <  >  &  "  '
     * \endcode
     *
     * You get slightly better performance if the \a escape parameter is set
     * to \c false, but before doing so be certain that your data does not
     * contain reserved characters.
     */
    RWXmlObjectOutputStreamImp(std::ostream& ostr, const RWCString& rootElementType, bool escape)
        :
        RWObjectOutputStreamImp(RWOstreamDataToCharOutputStreamImp::make(RWCharToStreambufOutputStreamImp::make(*(ostr.rdbuf())))),
        table_(rwnil),
        indent_(0),
        rootElementType_(rootElementType),
        objectPointerFlag_(false),
        escapeText_(escape)
    {
        ;
    }

    //--'Ctor' takes an 'ostream' to use as the destination,
    //--Parameter 'formatter' will be returned with a reference to the formatting object
    //--Parameter 'rootElementType' should be one of objectTag, nestedObjectTag,
    //--sequenceTag, primitiveTag, or mapTag, depending on what sort of object is streamed
    //--into the document at the top level.
    /**
     * \copydoc RWXmlObjectOutputStreamImp(std::ostream&, const RWCString&, bool)
     *
     * This constructor also takes a pointer reference to an \c std::ios
     * formatting object. An empty formatting object pointer is created
     * before the XML stream is created and is passed to this constructor
     * through the make() function. This constructor, in creating the
     * underlying character stream for the XML stream, creates a formatting
     * object for the stream and places the address of that object in the
     * pointer reference. The calling application can then use this
     * formatting object to manipulate data formats in the XML stream. See
     * the corresponding
     * \ref RWXmlObjectOutputStreamImp::make(std::ostream&, std::ios*&, const RWCString&, bool) "make()"
     * function description for an example.
     */
    RWXmlObjectOutputStreamImp(std::ostream& ostr, std::ios*& formatter, const RWCString& rootElementType, bool escape)
        :
        RWObjectOutputStreamImp(RWOstreamDataToCharOutputStreamImp::make(RWCharToStreambufOutputStreamImp::make(*(ostr.rdbuf())), formatter)),
        table_(rwnil),
        indent_(0),
        rootElementType_(rootElementType),
        objectPointerFlag_(false),
        escapeText_(escape)
    {
        ;
    }

    //--'Ctor' takes a 'RWDataOutputSream' to use as the destination,
    //--Parameter 'rootElementType' should be one of objectTag, nestedObjectTag,
    //--sequenceTag, primitiveTag, or mapTag, depending on what sort of object is streamed
    //--into the document at the top level.
    /**
     * Used by the make() function and potentially by derived classes to
     * initialize an RWDataOutputStream stream to be used as the sink for
     * the XML-formatted object serialization data. Use this constructor if
     * the required output stream is a RWDataOutputStream stream and pass a
     * reference to that stream as the \a ostr parameter.
     *
     * The parameter \a rootElementType must be one of the following:
     *
     * - #nestedObjectTag, if serializing an object by value
     * - #objectTag, if serializing an object by pointer
     * - #sequenceTag, if serializing a sequential collection such as
     * RWTPtrOrderedVector
     * - #mapTag, if serializing a mapping collection such as RWTPtrHashMap
     * - #primitiveTag, if serializing a built-in type such as \c int
     *
     * The value passed indicates the root element of the generated
     * document.
     *
     * The parameter \a escape sets whether to escape XML reserved
     * characters in the data being serialized. By setting this parameter to
     * \c true, reserved characters in \c char and \c string values are
     * escaped, allowing the data to include embedded XML.
     *
     * The reserved characters are:
     *
     * \code
     * <  >  &  "  '
     * \endcode
     *
     * You get slightly better performance if the \a escape parameter is set
     * to \c false, but before doing so be certain that your data does not
     * contain reserved characters.
     */
    RWXmlObjectOutputStreamImp(const RWDataOutputStream& ostr, const RWCString& rootElementType, bool escape)
        :
        RWObjectOutputStreamImp(ostr),
        table_(rwnil),
        indent_(0),
        rootElementType_(rootElementType),
        objectPointerFlag_(false),
        escapeText_(escape)
    {
        ;
    }
    // Make sure the storeTable is deleted even if an exception is thrown
    ~RWXmlObjectOutputStreamImp()
    {
        if (getContextNestingLevel() > 0) {
            RWXmlObjectOutputStreamImp::closeOuterContext(false);
        }
    }

public:
    //--Constructs an 'RWXmlObjectOutputStreamImp' instance that uses 'sink'
    //--as its sink of bytes, and returns a handle to it.
    //--Parameter 'sink' is the ostream that is used as the sink of bytes.
    //--Parameter 'rootElementType' should be one of objectTag, nestedObjectTag,
    //--sequenceTag, primitiveTag, or mapTag, depending on what sort of object is streamed
    //--into the document at the top level.
    //--Throws no exceptions.
    /**
     * Constructs an RWXmlObjectOutputStreamImp instance that passes the
     * serialized object data to the output stream \a sink, and returns a
     * handle to it. Use this method when the data output stream is a
     * standard library ostream.
     *
     * The parameter \a rootElementType must be one of the following:
     *
     * - #nestedObjectTag, if serializing an object by value
     * - #objectTag, if serializing an object by pointer
     * - #sequenceTag, if serializing a sequential collection such as
     * RWTPtrOrderedVector
     * - #mapTag, if serializing a mapping collection such as RWTPtrHashMap
     * - #primitiveTag, if serializing a built-in type such as \c int
     *
     * The value passed indicates the root element of the generated
     * document. The default setting is nestedObjectTag.
     *
     * The parameter \a escape sets whether to escape XML reserved
     * characters in the data being serialized. By setting this parameter to
     * \c true, reserved characters in \c char and \c string values are
     * escaped, allowing the data to include embedded XML.
     *
     * The reserved characters are:
     *
     * \code
     * <  >  &  "  '
     * \endcode
     *
     * You get slightly better performance if the \a escape parameter is set
     * to \c false, but before doing so be certain that your data does not
     * contain reserved characters.
     */
    static RWObjectOutputStream make(std::ostream& sink, const RWCString& rootElementType = nestedObjectTag, bool escape = true);

    //--Constructs an 'RWXmlObjectOutputStreamImp' instance that uses 'sink'
    //--as its sink of bytes, and returns a handle to it.
    //--Parameter 'sink' is the ostream that is used as the sink of bytes.
    //--Parameter 'formatter' will be returned with a reference to the formatting object
    //--Parameter 'rootElementType' should be one of objectTag, nestedObjectTag,
    //--sequenceTag, primitiveTag, or mapTag, depending on what sort of object is streamed
    //--into the document at the top level.
    //--Throws no exceptions.
    //--Parameter 'formatter' will be returned with a reference to the formatting object
    /**
     * \copydoc RWXmlObjectOutputStreamImp::make(std::ostream&, const RWCString&, bool)
     *
     * This function also takes a pointer reference to an \c std::ios
     * formatting object. An empty formatting object pointer is created
     * before the XML stream is created and is passed through this make()
     * function to the constructor:
     *
     * \code
     * std::ios* formatter;            // uninitialized pointer
     * RWObjectOutputStream xostr =
     * RWXmlObjectOutputStreamImp::make(outfile,formatter);
     * \endcode
     *
     * The constructor, in creating the underlying character stream for the
     * XML stream, creates a formatting object for the stream and places the
     * address of that object in the pointer reference. The calling
     * application can then use this formatting object to manipulate data
     * formats in the XML stream.
     *
     * \code
     * formatter->precision(15);       // manipulate data format
     * \endcode
     */
    static RWObjectOutputStream make(std::ostream& sink, std::ios*& formatter, const RWCString& rootElementType = nestedObjectTag, bool escape = true);

    //--Constructs an 'RWXmlObjectOutputStreamImp' instance that uses 'sink'
    //--as its sink of bytes, and returns a handle to it.
    //--Parameter 'sink' is the data stream that is used as the sink of bytes.
    //--Parameter 'rootElementType' should be one of objectTag, nestedObjectTag,
    //--sequenceTag, primitiveTag, or mapTag, depending on what sort of object is streamed
    //--into the document at the top level.
    //--Throws no exceptions.
    /**
     * Constructs an RWXmlObjectOutputStreamImp instance that passes the
     * serialized object data to the RWDataOutputStream stream \a sink, and
     * returns a handle to it. Use this method when the data output stream
     * is a RWDataOutputStream stream.
     *
     * The parameter \a rootElementType must be one of the following:
     *
     * - #nestedObjectTag, if serializing an object by value
     * - #objectTag, if serializing an object by pointer
     * - #sequenceTag, if serializing a sequential collection such as
     * RWTPtrOrderedVector
     * - #mapTag, if serializing a mapping collection such as RWTPtrHashMap
     * - #primitiveTag, if serializing a built-in type such as \c int
     *
     * The value passed indicates the root element of the generated
     * document. The default setting is #nestedObjectTag.
     *
     * The parameter \a escape sets whether to escape XML reserved
     * characters in the data being serialized. By setting this parameter to
     * \c true, reserved characters in \c char and \c string values are
     * escaped, allowing the data to include embedded XML.
     *
     * The reserved characters are:
     *
     * \code
     * <  >  &  "  '
     * \endcode
     *
     * You get slightly better performance if the \a escape parameter is set
     * to \c false, but before doing so be certain that your data does not
     * contain reserved characters.
     */
    static RWObjectOutputStream make(RWDataOutputStream& sink, const RWCString& rootElementType = nestedObjectTag, bool escape = true);

    void                  setRootElementType(const RWCString& rootElementType)
    {
        rootElementType_ = rootElementType;
    }
    RWCString             getRootElementType()
    {
        return rootElementType_;
    }
    inline void           indent();
    virtual void          newline()
    {
        putCharacterToSink('\n');
        indent();
    }
    inline void           openTag(const char* tag);
    inline void           closeTag(const char* tag);
    inline void           writeAttrName(const char* name);
    inline void           writeAttr(const char* name, const char* value);
    virtual void          startBlock(const RWSymbol&);
    virtual void          endBlock();
    virtual bool     needToWrite(const void* obj);
    virtual void          writeNullPtr();
    virtual void          newObjectMarker();
    virtual void          writeTypeInfo(const RWSymbol& typeInfo);

    /**
     * Writes the object name to the stream.
     */
    virtual void          writeObjectName();
    virtual void          rememberObject(const void* obj);
    virtual void          writeMemberInfo(const RWSymbol& memberName,
                                          RWStreamType memberType);
    virtual void          endMember(const RWSymbol& memberName);
    virtual void          startSequence(int count, RWStreamType elementType, const RWSymbol&);
    virtual void          startElement(int position);
    virtual void          endElement();
    virtual void          endSequence();
    virtual void          startMap(int count, RWStreamType keyType, RWStreamType valueType, const RWSymbol&);
    virtual void          startAssocKey();
    virtual void          startAssocValue();
    virtual void          endAssoc();
    virtual void          endMap();
    virtual void          openPrimitive(const char* typeAttrName, const char* typeAttrValue);
    virtual void          closePrimitive();

    /**
     * Writes a value to the stream, where the type of the value is defined
     * by the parameter. These functions are redefined from the parent class
     * RWObjectOutputStream.
     */
    virtual void          putString(const RWCString& value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putWString(const RWWString& value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUString(const RWBasicUString& value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putBool(bool value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putChar(char value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUnsignedChar(unsigned char value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putSignedChar(signed char value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putShort(short value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUnsignedShort(unsigned short value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putInt(int value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUnsignedInt(unsigned int value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putLong(long value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUnsignedLong(unsigned long value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putFloat(float value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putDouble(double value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putWchar_t(wchar_t value);

#if !defined(RW_NO_LONG_LONG)
    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putLongLong(long long value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUnsignedLongLong(unsigned long long value);
#endif

#ifndef RW_NO_LONG_DOUBLE
    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putLongDouble(long double value);
#endif

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putCharacter(char value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putWCharacter(wchar_t value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putUCharacter(RWUChar value);

    /**
     * \copydoc RWXmlObjectOutputStreamImp::putString(const RWCString&)
     */
    virtual void          putSizeT(size_t value);

    /**
     * Sets up the instance name for the next object to be written out.
     */
    virtual void          setNameForNextObject(const RWCString& str);

protected:
    // Escape characters in char or string values to allow embedded XML
    virtual bool escapeChar(char c, const char*& str);
    virtual RWCString escapeString(const RWCString& str);

    //--This here to prevent putString(RWCString&) from hiding the base class'
    //--function.
    virtual void putString(const char* string, RWSize count)
    {
        RWObjectOutputStreamImp::putString(string, count);
    }

    virtual void putWString(const wchar_t* wstring, RWSize count)
    {
        RWObjectOutputStreamImp::putWString(wstring, count);
    }

    virtual void putUString(const RWUChar* ustring, RWSize count)
    {
        RWObjectOutputStreamImp::putUString(ustring, count);
    }

    virtual void putStringToSink(const RWCString& st)
    {
        getSinkStream().putString(st.data(), static_cast<RWSize>(st.length()));
    }
    virtual void putCharacterToSink(char value)
    {
        getSinkStream().putCharacter(value);
    }
};


inline void RWXmlObjectOutputStreamImp::indent()
{
    RWCString buf(' ', indent_ * 2);
    putStringToSink(buf);
}

inline void RWXmlObjectOutputStreamImp::openTag(const char* tag)
{
    RWCString buf("<");
    buf.append(tag);
    putStringToSink(buf);
}

inline void RWXmlObjectOutputStreamImp::closeTag(const char* tag)
{
    RWCString buf("</");
    buf.append(tag);
    buf.append(">");
    putStringToSink(buf);
}

inline void RWXmlObjectOutputStreamImp::writeAttrName(const char* name)
{
    RWCString buf(" ");
    buf.append(name);
    buf.append("=\"");
    putStringToSink(buf);
}

inline void RWXmlObjectOutputStreamImp::writeAttr(const char* name, const char* value)
{
    writeAttrName(name);
    RWCString buf(value);
    buf.append("\"");
    putStringToSink(buf);
}

#if defined(_MSC_VER)
#  pragma warning(pop)
#endif

#endif // rw_xmlstreams_RWXmlObjectOutputStreamImp_h_
