/*----------------------------------------------------------------------------+
 | MODULE: perflib_create_indexes.sql
 |
 | DESCRIPTION:
 |
 | Indexes for Perflib tables ...
 |
 | INFORMATION:
 |
 | BRM Performance Tuning ...
 |
 | REVISION:
 |
 | $Revision: 1.5 $
 | $Author: ri-user-1 $
 | $Date: 2016/05/30 21:52:40 $
 +----------------------------------------------------------------------------*/
CREATE UNIQUE INDEX i_perf_snapshot__id ON
  performance_snapshot_t (poid_id0) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 204800 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT)
/

CREATE INDEX i_perf_snapshot__host_name ON
  performance_snapshot_t (hostname, name, start_t, end_t)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 204800 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT)
/

CREATE INDEX i_perf_results_add ON
  performance_results_t (obj_id0, parent_element_id, item_level, function) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 204800 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT)
/

CREATE UNIQUE INDEX i_perf_results__id ON
  performance_results_t (obj_id0, rec_id) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 204800 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT)
/

CREATE UNIQUE INDEX i_perf_sql_data__id ON
  performance_sql_data_t (poid_id0)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 204800 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT)
/         

CREATE UNIQUE INDEX i_perf_sql_data_buf__id ON
  performance_sql_data_buf (obj_id0)
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 204800 NEXT 204800 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT)
/         

exit
/
