#!/usr/local/bin/perl
#
# Copyright (c) 1998, 2023, Oracle and/or its affiliates.
#

# usage: def2class hfile

( $me = $0 ) =~ s,.*/,,;
$DEBUG = $ENV{"DEBUG"} || 0;

open( ROUT, ">src/main/java/com/portal/pcm/PortalConst.java" );

# Check if the special "-" syntax is used to specify the Publish
# directory. If found, then I will replace it with the value of the
# environment variable PINBUILD_PUBLISH_DIR.  This will allow the
# Makefiles to use commands that are the same between different views
# and allow winkins to work.
#
@new_argv;
while (@ARGV) {
    if ( $ARGV[0] =~ /^-/ ) {

        # Replace a file name that starts with "-"
        $ARGV[0] =~ s/^-/$ENV{PINBUILD_PUBLISH_DIR}/;
    }

    # Don't allow wildcards
    # See if the file exists, if it doesn't then die
    if ( !-e "$ARGV[0]" ) {
        print "File $ARGV[0] doesn't exist. Terminating.\n";
        exit 1;
    }
    push @new_argv, $ARGV[0];
    shift @ARGV;
}
@ARGV = @new_argv;

@local_time = localtime(time);
my $year = $local_time[5] + 1900;

# Start of the class
print ROUT "package com.portal.pcm;\n\n";
print ROUT "// Copyright (c) 1998, $year, Oracle and/or its affiliates.\n\n";
print ROUT "/**\n";
print ROUT " * PCM define constants\n";
print ROUT " * These are auto generated from the relevant C headers\n";
print ROUT " * \n";
print ROUT " * \@version 2.0 " . localtime(time) . "\n";
print ROUT " * \@author Autogenerated\n";
print ROUT " */\n\n";
print ROUT "public class PortalConst {\n\n";

print ROUT "    public static final int BOOLEAN_TRUE = 1;\n";
print ROUT "    public static final int BOOLEAN_FALSE = 0;\n";

$savcmnt   = 0;
$convenum  = 0;
$clsname   = "";
$constpref = "";
$stupid    = 0;
$stupid1   = 0;
$stupid2   = 0;

while (<>) {

    # Save comment blocks
    if ( $savcmnt == 0 && /^\s*\/\*/ ) {

        # beginning of new block found, clear cache and store
        $curcmnt = "\n    " . $_;
        $savcmnt = 1;

        # print $_;
    }
    elsif ( $savcmnt == 1 ) {
        $curcmnt = $curcmnt . "    " . $_;
    }

    if ( $savcmnt == 1 && /^.*\*\// ) {

        # end of comment found, stop saving
        # strip start and end comment parts
        $curcmnt =~ s/\/\*/ */g;
        $curcmnt =~ s/\*\//*/g;
        $savcmnt = 0;
    }

    if ( $savcmnt == 0 ) {
        if (/^\#\s*define\s+(PCM_|PIN_)(\w+)\s+(0x[0-9A-Fa-f]+|0X[0-9A-Fa-f]+|\d+).*\/\*(.*)\*\//) {

            $var = $2;
            $val = $3;
            $tmp = $4;
            $tmp =~ s/\s\s+//g;
            if ( $curcmnt ne "" ) {
                print ROUT "\n";
                print ROUT "    /**";
                $curcmnt =~ s/(\s+)&(\s+)/$1&amp;$2/g;
                print ROUT $curcmnt;
                print ROUT "     *\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            else {
                print ROUT "\n";
                print ROUT "    /**\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $var = $val;\n";
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(PCM_|PIN_)(\w+)\s+(0x[0-9A-Fa-f]+|0X[0-9A-Fa-f]+|\d+)/) {
            $tmp2 = $2;
            if ( "$tmp2" eq "FOLD_BAL_FLG_SPONSORABLE" ) {
                if ( $stupid == 0 ) {
                    if ( $curcmnt ne "" ) {
                        print ROUT "\n";
                        print ROUT "    /**";
                        print ROUT $curcmnt;
                        print ROUT "     */\n";
                    }
                    print ROUT "    public static final int $tmp2 = $3;\n";
                    $stupid = 1;
                }
            }
            elsif ( "$tmp2" eq "ELEMID_OLD" ) {
                if ( $stupid1 == 0 ) {
                    if ( $curcmnt ne "" ) {
                        print ROUT "\n";
                        print ROUT "    /**";
                        print ROUT $curcmnt;
                        print ROUT "     */\n";
                    }
                    print ROUT "    public static final int $tmp2 = $3;\n";
                    $stupid1 = 1;
                }
            }
            elsif ( "$tmp2" eq "ELEMID_NEW" ) {
                if ( $stupid2 == 0 ) {
                    if ( $curcmnt ne "" ) {
                        print ROUT "\n";
                        print ROUT "    /**";
                        print ROUT $curcmnt;
                        print ROUT "     */\n";
                    }
                    print ROUT "    public static final int $tmp2 = $3;\n";
                    $stupid2 = 1;
                }
            }
            else {
                if ( $curcmnt ne "" ) {
                    print ROUT "\n";
                    print ROUT "    /**";
                    $curcmnt =~ s/(\s+)&(\s+)/$1&amp;$2/g;
                    print ROUT $curcmnt;
                    print ROUT "     */\n";
                }
                print ROUT "    public static final int $tmp2 = $3;\n";
            }
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(\w+)\s+(0x[0-9A-Fa-f]+|0X[0-9A-Fa-f]+|\d+).*\/\*(.*)\*\//) {

            $var = $1;
            $val = $2;
            $tmp = $3;
            $tmp =~ s/\s\s+//g;
            if ( $curcmnt ne "" ) {
                print ROUT "\n    /**";
                print ROUT $curcmnt;
                print ROUT "     *\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            else {
                print ROUT "\n    /**\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $var = $val;\n";
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(\w+)\s+(0x[0-9A-Fa-f]+|0X[0-9A-Fa-f]+|\d+)/) {

            if ( $curcmnt ne "" ) {
                print ROUT "\n    /**";
                print ROUT $curcmnt;
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $1 = $2;\n";
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(PCM_|PIN_)(\w+)\s+(PCM_|PIN_)(\w+).*\/\*(.*)\*\//) {

            $var = $2;
            $val = $4;
            $tmp = $5;
            $tmp =~ s/\s\s+//g;
            if ( $curcmnt ne "" ) {
                print ROUT "\n    /**";
                print ROUT $curcmnt;
                print ROUT "     *\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            else {
                print ROUT "\n    /**\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $var = $val;\n";
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(PCM_|PIN_)(\w+)\s+(PCM_|PIN_)(\w+)/) {

            if ( $curcmnt ne "" ) {
                print ROUT "\n    /**";
                print ROUT $curcmnt;
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $2 = $4;\n";
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(\w+)\s+(\w+).*\/\*(.*)\*\//) {

            $var = $1;
            $val = $2;
            $tmp = $3;
            $tmp =~ s/\s\s+//g;
            if ( $curcmnt ne "" ) {
                print ROUT "\n    /**";
                print ROUT $curcmnt;
                print ROUT "     *\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            else {
                print ROUT "\n    /**\n";
                print ROUT "     * $tmp\n";
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $var = $val;\n";
            $curcmnt = "";
        }
        elsif (/^\#\s*define\s+(\w+)\s+(\w+)/) {

            if ( $curcmnt ne "" ) {
                print ROUT "\n    /**";
                print ROUT $curcmnt;
                print ROUT "     */\n";
            }
            print ROUT "    public static final int $1 = $2;\n";
            $curcmnt = "";
        }
    }
}

print ROUT "}\n";

close ROUT;
