#!/usr/local/bin/perl
#
# Copyright (c) 1998, 2023, Oracle and/or its affiliates.
#

# usage: enum2class hfile

( $me = $0 ) =~ s,.*/,,;
$DEBUG = $ENV{"DEBUG"} || 0;

open( ROUT, ">src/main/java/com/portal/pcm/PortalEnums.java" );

# Check if the special "-" syntax is used to specify the Publish
# directory. If found, then I will replace it with the value of the
# environment variable PINBUILD_PUBLISH_DIR.  This will allow the
# Makefiles to use commands that are the same between different views
# and allow winkins to work.
#
@new_argv;
while (@ARGV) {
    if ( $ARGV[0] =~ /^-/ ) {

        # Replace a file name that starts with "-"
        $ARGV[0] =~ s/^-/$ENV{PINBUILD_PUBLISH_DIR}/;
    }

    # Don't allow wildcards
    # See if the file exists, if it doesn't then die
    if ( !-e "$ARGV[0]" ) {
        print "File $ARGV[0] doesn't exist. Terminating.\n";
        exit 1;
    }
    push @new_argv, $ARGV[0];
    shift @ARGV;
}
@ARGV = @new_argv;

@local_time = localtime(time);
my $year = $local_time[5] + 1900;

# Start of the class
print ROUT "package com.portal.pcm;\n\n";
print ROUT "// Copyright (c) 1998, $year, Oracle and/or its affiliates.\n\n";
print ROUT "/**\n";
print ROUT " * PCM enum constants\n";
print ROUT " * These are auto-generated from the relevant C header\n";
print ROUT " * \n";
print ROUT " * \@version 1.0 " . localtime(time) . "\n";
print ROUT " * \@author Autogenerated\n";
print ROUT " */\n\n";
print ROUT "public class PortalEnums {\n";

$savcmnt   = 0;
$convenum  = 0;
$clsname   = "";
$constpref = "";

while (<>) {
    if ( $convenum == 0 ) {

        # Save comment blocks
        if ( $savcmnt == 0 && /^\s*\/\*/ ) {

            # beginning of new block found, clear cache and store
            $curcmnt = "    " . $_;
            $savcmnt = 1;

            # print $_;
        }
        elsif ( $savcmnt == 1 ) {
            $curcmnt = $curcmnt . "    " . $_;
        }

        if ( $savcmnt == 1 && /^.*\*\// ) {

            # end of comment found, stop saving
            # strip start and end comment parts
            $curcmnt =~ s/\/\*/ */g;
            $curcmnt =~ s/\*\//*/g;
            $savcmnt = 0;
        }

        if ( $savcmnt == 0 ) {
            if (/^.*enum\s+(\w+)\s+\{/) {
                $cp2       = uc $1;
                $constpref = uc $1 . "_";

                $clsname = ucfirst $1;
                $clsname =~ s/_(.+)/ucfirst($1)/e;
                $clsname =~ s/_(.+)/ucfirst($1)/e;
                $clsname =~ s/_(.+)/ucfirst($1)/e;
                $clsname =~ s/_(.+)/ucfirst($1)/e;

                if ( $curcmnt ne "" ) {
                    print ROUT "\n    /**\n";
                    $curcmnt =~ s/(\s+)&(\s+)/$1&amp;$2/g;
                    print ROUT $curcmnt;
                    print ROUT "     */\n";
                }
                print ROUT "    public interface $clsname {\n";

                $cp2 =~ s/(\w+)_(\w*)$/$1_/;
                $cp3 = $cp2;
                $cp3 =~ s/(\w+_[A-Z])[A-Z]*_$/$1/;
                $convenum = 1;
            }
        }
    }
    else {
        if ( $savcmnt == 0 && /^\s*\/\*/ ) {

            # beginning of new block found. print it.
            $t = $_;
            $t =~ s/\/\*/ */g;
            $t =~ s/\*\//*/g;
            print ROUT "    /**\n";
            print ROUT "    " . $t;
            $savcmnt = 1;
        }
        elsif ( $savcmnt == 1 ) {
            $t = $_;
            $t =~ s/\*\//*/g;
            print ROUT "    " . $t;
        }

        if ( $savcmnt == 1 && /^.*\*\// ) {

            # end of comment found, stop saving
            $savcmnt = 0;
            print ROUT "     */\n";
        }

        if ( $savcmnt == 0 ) {
            if (/^\s*$constpref(\w+)\s*\=\s+(\d+).*\/\*(.*)\*\//) {
                print ROUT "\n        /**\n";
                print ROUT "         * $3\n";
                print ROUT "         */\n";
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*$constpref(\w+)\s*\=\s+(\d+)/) {
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*$cp2(\w+)\s*\=\s+(\d+).*\/\*(.*)\*\//) {
                print ROUT "\n        /**\n";
                print ROUT "         * $3\n";
                print ROUT "         */\n";
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*$cp2(\w+)\s*\=\s+(\d+)/) {
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*$cp3(\w+)\s*\=\s+(\d+).*\/\*(.*)\*\//) {
                $tmp = $1;
                $val = $2;
                $tmp =~ s/^([A-Z]*)_(\w*)/$2/;
                print ROUT "\n        /**\n";
                print ROUT "         * $3\n";
                print ROUT "         */\n";
                print ROUT "        public static final int $tmp = $val;\n";
            }
            elsif (/^\s*$cp3(\w+)\s*\=\s+(\d+)/) {
                $tmp = $1;
                $val = $2;
                $tmp =~ s/^([A-Z]*)_(\w*)/$2/;
                print ROUT "        public static final int $tmp = $val;\n";
            }
            elsif (/^\s*PIN_(\w+)\s*\=\s*(\d+).*\/\*(.*)\*\//) {
                print ROUT "\n        /**\n";
                print ROUT "         * $3\n";
                print ROUT "         */\n";
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*PIN_(\w+)\s*\=\s*(\d+)/) {
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*(\w+)\s*\=\s*(\d+).*\/\*(.*)\*\//) {
                print ROUT "\n        /**\n";
                print ROUT "         * $3\n";
                print ROUT "         */\n";
                print ROUT "        public static final int $1 = $2;\n";
            }
            elsif (/^\s*(\w+)\s*\=\s*(\d+)/) {
                print ROUT "        public static final int $1 = $2;\n";
            }

            if (/\s*\}.*\;\s*$/) {
                $convenum = 0;

                print ROUT "    }\n";
            }
        }
    }
}

print ROUT "}\n";

close ROUT;
