#!/usr/local/bin/perl
#
# Copyright (c) 1997, 2023, Oracle and/or its affiliates.
#

( $me = $0 ) =~ s,.*/,,;
$DEBUG = $ENV{"DEBUG"} || 0;

open( JOUT, ">src/main/java/com/portal/pcm/PortalOp.java" );

# Check if the special "-" syntax is used to specify the include/ops
# directory in the Publish directory. If found, then I will replace
# it with the value of the environment variable PINBUILD_PUBLISH_DIR
# plus /include/ops/.  This will allow the
# Makefiles to use commands that are the same between different views
# and allow winkins to work.
#
# I also need to pass all the file names instead of a wildcard so
# that this function is not skipped (due to build avoidance in clearmake)
# when a new op header file is added.
#
@new_argv;
while (@ARGV) {
    if ( $ARGV[0] =~ /^-/ ) {

        # Replace a file name that starts with "-"
        $ARGV[0] =~ s@^-@$ENV{PINBUILD_PUBLISH_DIR}/include/ops/@;
    }

    # Don't allow wildcards
    # See if the file exists, if it doesn't then die
    if ( !-e "$ARGV[0]" ) {
        print "File $ARGV[0] doesn't exist. Terminating.\n";
        exit 1;
    }
    push @new_argv, $ARGV[0];
    shift @ARGV;
}
@ARGV = @new_argv;

@local_time = localtime(time);
my $year = $local_time[5] + 1900;

# Start of the class
print JOUT "package com.portal.pcm;\n\n";
print JOUT "// Copyright (c) 1997, $year, Oracle and/or its affiliates.\n\n";
print JOUT "/**\n";
print JOUT " * PCM opcode constants\n";
print JOUT " * These are auto generated from <code>pcm_ops.h</code>\n";
print JOUT " *\n";
print JOUT " * \@version 1.0 " . localtime(time) . "\n";
print JOUT " * \@author Autogenerated\n";
print JOUT " */\n\n";

print JOUT "public class PortalOp {\n";

while (<>) {
    #
    # Accept lines matching #define PIN_OP_XXXX nnnn
    #
    if (/^#\s*define\s+PCM_OP_(\w+)\s+(\d+).*$/) {
        print JOUT "    public static final int $1 = $2;\n";
    }
}

print JOUT "\n    \/**\n";
print JOUT "     * The return value of this function may vary for each call when executed on\n";
print JOUT "     * certain versions of JRE. This variation is seen only for such opcode numbers\n";
print JOUT "     * that may have multiple opcode names associated with it; in such cases the\n";
print JOUT "     * function may return any one of the associated opcode names. So, if there is\n";
print JOUT "     * any decision being made based on the opcode name returned by this function,\n";
print JOUT "     * then the calling logic should check all the possible opcode names for the\n";
print JOUT "     * given opcode number.\n";
print JOUT "     *\n";
print JOUT "     * Please check the \"NOTE\" section under the following heading for related\n";
print JOUT "     * information: Programmer's Guide -&gt; Introduction to customizing BRM -&gt;\n";
print JOUT "     * Understanding the PCM API and the PIN library -&gt; Header files\n";
print JOUT "     *\n";
print JOUT "     * \@param op opcode number\n";
print JOUT "     * \@return opcode name\n";
print JOUT "     */\n";
print JOUT "    public static String opToString(int op) {\n";
print JOUT "        try {\n";
print JOUT "            java.lang.reflect.Field[] flds = PortalOp.class.getFields();\n";
print JOUT "            for (int i = 0; i < flds.length; i++) {\n";
print JOUT "                try {\n";
print JOUT "                    int val = flds[i].getInt(null);\n";
print JOUT "                    if (val == op) {\n";
print JOUT "                        return flds[i].getName();\n";
print JOUT "                    }\n";
print JOUT "                } catch (IllegalAccessException | IllegalArgumentException e) { \n";
print JOUT "                    continue;\n";
print JOUT "                }\n";
print JOUT "            }\n";
print JOUT "        } catch (SecurityException e) {\n";
print JOUT "        }\n";
print JOUT "        return null;\n";
print JOUT "    }\n";

print JOUT "\n    \/**\n";
print JOUT "     * This function returns the integer number of given name of the opcode\n";
print JOUT "     *\n";
print JOUT "     * \@param op name of the opcode\n";
print JOUT "     * \@return opcode number\n";
print JOUT "     */\n";
print JOUT "    public static int stringToOp(String op) {\n";
print JOUT "        try {\n";
print JOUT "            java.lang.reflect.Field[] flds = PortalOp.class.getFields();\n";
print JOUT "            for (int i = 0; i < flds.length; i++) {\n";
print JOUT "                try {\n";
print JOUT "                    String name = flds[i].getName();\n";
print JOUT "                    if (name.equals(op)) {\n";
print JOUT "                        return flds[i].getInt(null);\n";
print JOUT "                    }\n";
print JOUT "                } catch (IllegalAccessException | IllegalArgumentException e) {\n";
print JOUT "                    continue;\n";
print JOUT "                }\n";
print JOUT "            }\n";
print JOUT "        } catch (SecurityException e) {\n";
print JOUT "        }\n";
print JOUT "        return -1;\n";
print JOUT "    }\n";
print JOUT "}\n";

close JOUT;
