# post-install oraparam.ini

[Oracle]
# NextGen unsupported for post-install ops: INSTALL_CLASS
#INSTALL_CLASS=com.oracle.cie.wizard.WizardController

# NextGen obsolete: DISTRIBUTION
DISTRIBUTION=FALSE

# NextGen unsupported: SOURCE
SOURCE=

# NextGen unsupported: LICENSE_LOCATION
LICENSE_LOCATION=

# NextGen unsupported: JRE_LOCATION
JRE_LOCATION=

# NextGen unsupported: OUI_LOCATION, OUI_CORE_LOCATION, OPATCH_LOCATION
#OUI_LOCATION=..
#OUI_CORE_LOCATION=..
#OPATCH_LOCATION=../../OPatch

# NextGen unsupported: DEFAULT_HOME_LOCATION, DEFAULT_HOME_NAME
DEFAULT_HOME_LOCATION=
DEFAULT_HOME_NAME=

NLS_ENABLED=TRUE

# NextGen unsupported: JRE_MEMORY_OPTIONS
JRE_MEMORY_OPTIONS=

JAVA_OPTIONS=
HOTSPOT_JAVA_OPTIONS=
IBM_JAVA_OPTIONS=
JROCKIT_JAVA_OPTIONS=
VM_TYPES=

JAVA_VERSION=1.8

NO_BROWSE=/net

# NextGen obsolete: BOOTSTRAP
#BOOTSTRAP=TRUE

# NextGen unsupported: CLUSTERWARE, VENDORCLUSTERWARE
#CLUSTERWARE={"oracle.crs","10.1.0.2.0"}
#VENDORCLUSTERWARE=TRUE

#THIN_JDBC_FILENAME is optional and defaults to classes12.jar
#The value specified for this should be packaged with OUI, and should 
#be relative to <OUI expanded stagedir>/modules/
THIN_JDBC_FILENAME=classes12.jar

# NextGen unsupported: OUI_VERSION
OUI_VERSION=

#RUN_OUICA specifies the batch script name that needs to be run
#The script is ouica.bat for win32, and ouica.sh for solaris. 
#If the value is not specified, then the OUICA script is not run
# NextGen unsupported: RUN_OUICA
RUN_OUICA=

# NextGen unsupported: SHOW_HOSTNAME
#SHOW_HOSTNAME=ALWAYS_SHOW shows the hostname panel always
#SHOW_HOSTNAME=NEVER_SHOW does not the hostname panel
#SHOW_HOSTNAME=CONDITION_SHOW shows the hostname panel on condition
SHOW_HOSTNAME=NEVER_SHOW

#Variables to set for extra classes to load in the runtime. This location can be
#absolute or relative to the location of install.cmd/install.sh
# NextGen unsupported, obsolete: EXT_JLIB, EXT_LIB, EXT_BIN
EXT_JLIB=../../Scripts/ext/jlib
EXT_LIB=../../Scripts/ext/lib
EXT_BIN=../../Scripts/ext/bin

EXT_CLASSPATH=setup/BRMScreens.jar,setup/helpset.jar,setup/helpset_fr.jar,setup/helpset_es.jar,setup/helpset_it.jar,setup/helpset_ja.jar,setup/helpset_ko.jar,setup/helpset_pt_BR.jar,setup/helpset_ru_RU.jar,setup/helpset_zh_CN.jar,setup/helpset_zh_TW.jar,oracle_common/modules/oracle.help/oracle_ice.jar
BOOT_CLASSPATH=

# NextGen unsupported: PLATFORM_PREREQS
PLATFORM_PREREQS=FALSE

# NextGen unsupported for post-install ops: PREREQ_CONFIG_LOCATION
# use command-line option instead
#PREREQ_CONFIG_LOCATION=oui/brm/prereq

# legal values: CENTRAL_INVENTORY, ORACLE_HOME
LOG_LOCATION=

[Generic Prereqs]
SWAP_SPACE=500
MIN_DISPLAY_COLORS=256
JAVA_USE_64BIT=MAC-OS-IN64,MAC-OS-IN,Solaris,Solaris_SPARC64,HP_IA64,HP_IA32,Intel_Solaris,Intel_Solaris32
