# @(#)% %
#
# Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.
#      This material is the confidential property of Oracle Corporation
#      or its licensors and may be used, reproduced, stored
#      or transmitted only in accordance with a valid Oracle license
#      or sublicense agreement.
#


################################################################################
################################################################################

##
# Beginning of Batch Controller general processing configuration
#

# Logging configuration
infranet.log.file =	/home/pin/opt/portal/BRM/apps/batch_controller/batch_controller.pinlog
infranet.log.level =          1
infranet.log.logallebuf =     true

# Infranet CM connection configuration
#infranet.connection	pcp://root.0.0.0.1:@192.168.56.101:11960/service/pcm_client
infranet.login.type =         1

# Miscellaneous processing configuration
batch.check.interval =        <#seconds>
batch.file.rename.extension = .bc
batch.start.highload.time =   <hhmmss>
batch.end.highload.time =     <hhmmss>
batch.handler.start.wait =    <#seconds>
batch.handler.end.wait =      <#seconds>
batch.lock.socket.addr =      11971
batch.shutdown.interval = 2

#
# End of Batch Controller general processing configuration
##

################################################################################
################################################################################

##
# Beginning of Random event configuration
#

# List of random event names
#batch.random.events = <eventname>[, <eventname>, ...]

# Entries for File-arrival events
#<eventname>.name =                   <eventlabel>
#<eventname>.handlers =               <handlername>[, <handlername>, ...]
#<eventname>.file.location =          <full_path_to_directory>
#<eventname>.file.pattern =           <filepattern>
#<handlername>.name =                 <handlerlabel>
#<handlername>.max.at.highload.time = <#count>
#<handlername>.max.at.lowload.time =  <#count>
#<handlername>.start.string =         <full_path_to_command> [<options>]

#
# End of Random event configuration
##

################################################################################
################################################################################

##
# Beginning of Timed event configuration
#

# List of timed event names
#batch.timed.events = <eventname>[, <eventname>, ...]

# Entries for Metronomic Time events
#<eventname>.name =                   <eventlabel>
#<eventname>.handlers =               <handlername>[, <handlername>, ...]
#<eventname>.interval =               <#seconds>
#<eventname>.start =                  <hhmmss>
#<eventname>.count =                  <#occurrences>
#<handlername>.name =                 <handlerlabel>
#<handlername>.max.at.highload.time = <#count>
#<handlername>.max.at.lowload.time =  <#count>
#<handlername>.start.string =         <full_path_to_command> [<options>]

# Entries for Scheduled Time events
#<eventname>.name =                   <eventlabel>
#<eventname>.handlers =               <handlername>[, <handlername>, ...]
#<eventname>.at =                     <hhmmss>[, <hhmmss>, ...]
#<eventname>.file.location =          <full_path_to_directory>
#<eventname>.file.pattern =           <filepattern>
#<handlername>.name =                 <handlerlabel>
#<handlername>.max.at.highload.time = <#count>
#<handlername>.max.at.lowload.time =  <#count>
#<handlername>.start.string =         <full_path_to_command> [<options>]

#
# End of Timed event configuration
##

################################################################################
################################################################################

########################################################
#SSL configuration
########################################################
# To  enable SSL, make sure to provide correct values for below config entries. e.g wallet location and filename etc.
infranet.pcp.ssl.enabled = false
infranet.pcp.ssl.wallet.location = /home/pin/opt/portal/BRM/wallet/client
infranet.pcp.ssl.wallet.filename = cwallet.sso


relHandler.name                   relHandler
relHandler.max.at.highload.time   1
relHandler.max.at.lowload.time    1
relHandler.start.string           /home/pin/opt/portal/BRM/apps/pin_rel/RelHandler.pl 


