#
# custom account selection criteria
# 
#cust_acct_search_account_state_constraint=-- cust_acct_search_account_state_constraint: account_state \n\
#AND EXISTS (SELECT an.obj_id0 FROM account_nameinfo_t an WHERE an.obj_id0 = a.poid_id0 and an.state = '{account_state}') \n




