{
 "title": "OCBRM DM-Oracle Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Opcode ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 5 Opcode Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5, (count by (opcode_name) (brm_opcode_errors_total{application=\"dm_oracle\"})))",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Opcode Execution Time ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by (opcode_name) (brm_opcode_exec_time_total{application=\"dm_oracle\"}))",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Opcode Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5,(count by (opcode_name) (brm_opcode_calls_total{application=\"dm_oracle\"})))",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  { "title": "CPU and Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Opcode level User CPU execution time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (opcode_name) (brm_opcode_user_cpu_time_total{application=\"dm_oracle\"})",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  {
   "title": "Opcode level System CPU execution time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (opcode_name) (brm_opcode_system_cpu_time_total{application=\"dm_oracle\"})",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  {
   "title": "Opcode System CPU - DM Oracle",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (opcode,opcode_name,object_type) (\n  irate(brm_opcode_system_cpu_time_total{application=\"dm_oracle\"}[5m])\n)",
     "legendFormat": "{{opcode_name}}, {{object_type}}"
    }
   ]
  }
 ]
}