{
 "title": "OCBRM CM Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Opcode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Opcode Calls",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 23, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(10, (max by (opcode_name) (brm_opcode_calls_total{application=\"cm\"})))",
       "legendFormat": "{{opcode_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Opcode Errors",
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "topk(5, (count by (opcode_name) (brm_opcode_errors_total{application=\"cm\"})))",
       "legendFormat": "{{opcode_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Opcode Execution Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5, avg by (opcode_name) (brm_opcode_exec_time_total{application=\"cm\"}))",
       "legendFormat": "{{opcode_name}}"
      }
     ]
    },
    {
     "title": "Opcode  - PCM_OP_READ_OBJ Error Alert",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(brm_opcode_errors_total{opcode_name=\"PCM_OP_READ_OBJ\"})",
       "legendFormat": "Errors"
      }
     ]
    }
   ]
  },
  { "title": "CPU and Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Opcode level System CPU execution time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (opcode_name) (brm_opcode_system_cpu_time_total{application=\"cm\"})",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  {
   "title": "Opcode level User CPU execution time ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (opcode_name) (brm_opcode_user_cpu_time_total{application=\"cm\"})",
     "legendFormat": "{{opcode_name}}"
    }
   ]
  },
  {
   "title": "Opcode System CPU - CM",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (opcode,opcode_name,object_type) (\n  irate(brm_opcode_system_cpu_time_total{application=\"cm\"}[5m])\n)",
     "legendFormat": "{{opcode_name}}, {{object_type}}"
    }
   ]
  }
 ]
}