{
 "title": "OCBRM DM-Oracle-SHM Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Shared Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shared Memory -  High Water Mark",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brm_dmo_shared_memory_hwm" }
   ]
  },
  {
   "title": "Shared Memory - BigSize-  High Water Mark",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brm_dmo_shared_memory_bigsize_hwm"
    }
   ]
  },
  {
   "title": "Shared Memory - Used (Current)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "yaxes": [
    { "format": "Blocks" }
   ],
   "targets": [
    {
     "expr": "brm_dmo_shared_memory_used_current",
     "legendFormat": "Shared Memory Used"
    }
   ]
  },
  {
   "title": "Shared Memory - BigSize - Used (Current)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "brm_dmo_shared_memory_bigsize_used_current",
     "legendFormat": "Shared Memory Used BigSize"
    }
   ]
  },
  {
   "title": "Shared Memory - Used (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "yaxes": [
    { "format": "Blocks" }
   ],
   "targets": [
    { "expr": "brm_dmo_shared_memory_used_max", "legendFormat": "Max Shared Memory Used" }
   ]
  },
  {
   "title": "Shared Memory - BigSize - Used (Max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "brm_dmo_shared_memory_bigsize_used_max",
     "legendFormat": "Max Shared Memory Used BigSize"
    }
   ]
  },
  { "title": "Front and Back End Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DM Front End and Back End Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(brm_dmo_front_end_ops_done_total)",
     "legendFormat": "Front End"
    },
    {
     "expr": "sum(brm_dmo_back_end_ops_done_total)",
     "legendFormat": "Back End"
    }
   ]
  },
  {
   "title": "DM Front End and Back End Transactions Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(brm_dmo_front_end_trans_done_total)",
     "legendFormat": "Front End"
    },
    {
     "expr": "sum(brm_dmo_back_end_trans_done_total)",
     "legendFormat": "Back End"
    }
   ]
  },
  {
   "title": "Back End Ops Error Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(brm_dmo_back_end_ops_error_total)"
    }
   ]
  },
  {
   "title": "Back End Transaction Error Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(brm_dmo_back_end_trans_error_total)"
    }
   ]
  }
 ]
}