{
 "title": "OCBRM EAI-JS Dashboard",
 "time": { "from": "2021-06-22T13:12:30.009Z", "to": "2021-06-22T13:12:34.691Z" },
 "panels": [
  {
   "title": "Java Server Opcode Metrics",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_portal_js_JSMetrics_CurrentConnectionCount",
     "legendFormat": "Current Connection Count"
    },
    {
     "expr": "com_portal_js_JSMetrics_MaxConnectionCount",
     "legendFormat": "Max Connection Count"
    },
    {
     "expr": "com_portal_js_JSMetrics_TotalOpcodeCount",
     "legendFormat": "Total Opcodes"
    },
    {
     "expr": "com_portal_js_JSMetrics_TotalOpcodeExecutionTime",
     "legendFormat": "Opcode Execution Time"
    }
   ]
  },
  {
   "title": "Successful and Failed Opcode Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_portal_js_JSMetrics_SuccessfulOpcodeCount"
    },
    {
     "expr": "com_portal_js_JSMetrics_FailedOpcodeCount"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used",
     "legendFormat": "Heap Memory Used"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used",
     "legendFormat": "Non-Heap Memory Usage"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuTime",
     "legendFormat": "Process CPU Time"
    }
   ]
  },
  {
   "title": "Bufer Pool Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "java_nio_BufferPool_MemoryUsed", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Max Non Heap Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_max"
    }
   ]
  },
  {
   "title": "Max Heap Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max"
    }
   ]
  },
  {
   "title": "Garbage Collector - Last Info Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_duration",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}