{
 "title": "OCBRM REM TableMetrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "FailedTotal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "event_bal_impacts_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FailedTotal{Table=\"event_bal_impacts_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FailedTotal{Table=\"event_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gsm_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FailedTotal{Table=\"event_dlyd_session_tlco_gsm_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_essentials_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FailedTotal{Table=\"event_essentials_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlay_sess_tlcs_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FailedTotal{Table=\"event_dlay_sess_tlcs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gprs_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FailedTotal{Table=\"event_dlyd_session_tlco_gprs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FilesTotal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "event_bal_impacts_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FilesTotal{Table=\"event_bal_impacts_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_essentials_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FilesTotal{Table=\"event_essentials_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlay_sess_tlcs_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FilesTotal{Table=\"event_dlay_sess_tlcs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FilesTotal{Table=\"event_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gprs_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FilesTotal{Table=\"event_dlyd_session_tlco_gprs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gsm_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_FilesTotal{Table=\"event_dlyd_session_tlco_gsm_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RowsLoadedTotal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "event_bal_impacts_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_RowsLoadedTotal{Table=\"event_bal_impacts_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlay_sess_tlcs_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_RowsLoadedTotal{Table=\"event_dlay_sess_tlcs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gprs_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_RowsLoadedTotal{Table=\"event_dlyd_session_tlco_gprs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_RowsLoadedTotal{Table=\"event_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gsm_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_RowsLoadedTotal{Table=\"event_dlyd_session_tlco_gsm_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_essentials_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_RowsLoadedTotal{Table=\"event_essentials_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LoadMillisTotal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "event_bal_impacts_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_LoadMillisTotal{Table=\"event_bal_impacts_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_essentials_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_LoadMillisTotal{Table=\"event_essentials_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gprs_t",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_LoadMillisTotal{Table=\"event_dlyd_session_tlco_gprs_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_dlyd_session_tlco_gsm_t",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_LoadMillisTotal{Table=\"event_dlyd_session_tlco_gsm_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_essentials_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_LoadMillisTotal{Table=\"event_essentials_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "event_t",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_TableMetrics_LoadMillisTotal{Table=\"event_t\"}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  }
 ]
}