{
 "title": "OCBRM REMMetrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Updater in Milli Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total updater time in Milli Seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_UpdaterMillisTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total updater time in Milli Seconds",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_UpdaterMillisTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Loaded",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Loaded  ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_LoadTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total Loaded  ",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_LoadTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Failure in Updater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Failure in Updater SP",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_FailedUpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total Failure in Updater SP",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_FailedUpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Failure in PreUpdater",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Failure in preUpdater",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_FailedPreUpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total Failure in preUpdater",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_FailedPreUpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Updater Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Updater Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_UpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Updater Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_UpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PreUpdater Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Preupdater Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_PreUpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Preupdater Total",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_PreUpdaterTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Load Time in Milli Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Load Time in Milli Seconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_LoadMillisTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total Load Time in Milli Seconds",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_LoadMillisTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Failure in Loading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Failure in Loading",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_FailedLoadTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total Failure in Loading",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_FailedLoadTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Pre Updater Time in Milli Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pre Updater TIme in MilliSeconds",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_PreUpdaterMillisTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total Pre Updater TIme in MilliSeconds",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_PreUpdaterMillisTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Number of Loaded Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of Loaded Events",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_EventsLoadedTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    },
    {
     "title": "Total number of Loaded Events",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "RatedEventManager_Metrics_EventsLoadedTotal{}",
       "legendFormat": "{{Schema}}"
      }
     ]
    }
   ]
  }
 ]
}