{
 "title": "OCBRM Services Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BRM Status Tracking",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (process) (brm_service_status)",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "BRM Service Status",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (process) (brm_service_status)",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Memory Usage - BRM Services",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by (process) (brm_service_memory_usage_total)",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}