#ifndef rw_stream_RWOstreamDataToCharOutputStreamImp_h_
#define rw_stream_RWOstreamDataToCharOutputStreamImp_h_

/*********************************************************************
 *
 * $Id: //spro/rel2016.1/rw/stream/RWOstreamDataToCharOutputStreamImp.h#1 $
 *
 * Copyright (c) 1996-2016 Rogue Wave Software, Inc.  All Rights Reserved.
 * 
 * This computer software is owned by Rogue Wave Software, Inc. and is
 * protected by U.S. copyright laws and other laws and by international
 * treaties.  This computer software is furnished by Rogue Wave Software, Inc.
 * pursuant to a written license agreement and may be used, copied, transmitted,
 * and stored only in accordance with the terms of such license agreement and
 * with the inclusion of the above copyright notice.  This computer software or
 * any other copies thereof may not be provided or otherwise made available to
 * any other person.
 * 
 * U.S. Government Restricted Rights.  This computer software: (a) was
 * developed at private expense and is in all respects the proprietary
 * information of Rogue Wave Software, Inc.; (b) was not developed with
 * government funds; (c) is a trade secret of Rogue Wave Software, Inc. for all
 * purposes of the Freedom of Information Act; and (d) is a commercial item and
 * thus, pursuant to Section 12.212 of the Federal Acquisition Regulations (FAR)
 * and DFAR Supplement Section 227.7202, Government's use, duplication or
 * disclosure of the computer software is subject to the restrictions set forth
 * by Rogue Wave Software, Inc.
 *
 ********************************************************************/

#include <rw/stream/RWDataOutputStream.h>
#include <rw/stream/RWDataToCharOutputStreamImp.h>
#include <rw/stream/pkgdefs.h>
#include <ostream>

#if defined(_MSC_VER)
#  pragma warning(push)
#  pragma warning(disable : 4251)
#endif

template <class OutputStream> class RWTStreambufToByteCharOutputStream;
typedef RWTStreambufToByteCharOutputStream<RWCharOutputStream> RWStreambufToCharOutputStream;

/**
 * \ingroup streams_package
 *
 * \brief
 * Writes data in US-ASCII format to a narrow character stream.
 *
 * The class RWOstreamDataToCharOutputStreamImp writes data in US-ASCII
 * format to a narrow character stream. The format generated is equivalent
 * to the format generated by the iostreams \b std::ostream class.
 * Implements the body idiom from the handle-body pattern.
 */
class RW_STREAM_GLOBAL RWOstreamDataToCharOutputStreamImp : public RWDataToCharOutputStreamImp
{

public:

    /**
     * Constructs an RWOstreamDataToCharOutputStreamImp instance that uses
     * \a sink as its sink of narrow characters and returns a handle to it.
     * Throws no exceptions.
     *
     * \param sink
     * The narrow character stream that is used as the character sink.
     */
    static RWDataOutputStream make(const RWCharOutputStream& sink)
    {
        return RWDataOutputStream(new RWOstreamDataToCharOutputStreamImp(sink));
    }

    /**
     * Constructs an RWOstreamDataToCharOutputStreamImp instance that uses
     * \a sink as its sink of narrow characters and returns a handle to it.
     * Throws no exceptions.
     *
     * \param sink
     * The narrow character stream that is used as the character sink.
     *
     * \param formatter
     * An object that can be used to modify the format generated by the
     * stream. This object is initialized by the stream, and then returned
     * to the caller.
     */
    static RWDataOutputStream make(const RWCharOutputStream& sink, std::ios*& formatter)
    {
        return RWDataOutputStream(new RWOstreamDataToCharOutputStreamImp(sink, formatter));
    }

    //--Throws no exceptions.
    /**
     * Destructor.
     */
    virtual ~RWOstreamDataToCharOutputStreamImp();

    /**
     * Flushes the embedded iostreams \b std::ostream object and then
     * forwards the closed call to the next processing narrow character
     * output stream.
     */
    virtual void close();

    /**
     * Flushes the embedded iostreams \b std::ostream object.
     */
    virtual void flush();

    /**
     * Returns \c true if either one of the embedded iostreams
     * \b std::ostream objects or the next processing narrow character
     * output stream object is in a bad state. Throws no exceptions.
     */
    virtual bool isBad() const;

    /**
     * Returns \c true if either one of the embedded iostreams
     * \b std::ostream objects or the next processing narrow character
     * output stream object is in a failed state. Throws no exceptions.
     */
    virtual bool isFail() const;

    /**
     * Returns \c true if both the embedded iostreams \b std::ostream object
     * and the next processing narrow character output stream object are in
     * a good state. Throws no exceptions.
     */
    virtual bool isGood() const;

    /**
     * Writes a \c bool value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c bool value to be written to the stream.
     */
    virtual void putBool(bool value);

    /**
     * Writes a \c char value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c char value to be written to the stream.
     */
    virtual void putChar(char value);

    /**
     * Writes a <tt>unsigned char</tt> value to the narrow character stream,
     * used as the data sink.
     *
     * \param value
     * The <tt>unsigned char</tt> value to be written to the stream.
     */
    virtual void putUnsignedChar(unsigned char value);

    /**
     * Writes a <tt>signed char</tt> value to the narrow character stream,
     * used as the data sink.
     *
     * \param value
     * The <tt>signed char</tt> value to be written to the stream.
     */
    virtual void putSignedChar(signed char value);

    /**
     * Writes a \c short value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c short value to be written to the stream.
     */
    virtual void putShort(short value);

    /**
     * Writes a <tt>unsigned short</tt> value to the narrow character
     * stream, used as the data sink.
     *
     * \param value
     * The <tt>unsigned short</tt> value to be written to the stream.
     */
    virtual void putUnsignedShort(unsigned short value);

    /**
     * Writes a \c int value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c int value to be written to the stream.
     */
    virtual void putInt(int value);

    /**
     * Writes a <tt>unsigned int</tt> value to the narrow character stream,
     * used as the data sink.
     *
     * \param value
     * The <tt>unsigned int</tt> value to be written to the stream.
     */
    virtual void putUnsignedInt(unsigned int value);

    /**
     * Writes a \c long value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c long value to be written to the stream.
     */
    virtual void putLong(long value);

    /**
     * Writes a <tt>unsigned long</tt> value to the narrow character stream,
     * used as the data sink.
     *
     * \param value
     * The <tt>unsigned long</tt> value to be written to the stream.
     */
    virtual void putUnsignedLong(unsigned long value);

    /**
     * Writes a \c float value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c float value to be written to the stream.
     */
    virtual void putFloat(float value);

    /**
     * Writes a \c double value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c double value to be written to the stream.
     */
    virtual void putDouble(double value);

    /**
     * Writes a \c wchar_t value to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The \c wchar_t value to be written to the stream.
     */
    virtual void putWchar_t(wchar_t value);

#if !defined(RW_NO_LONG_LONG)
    /**
     * Writes a <tt>long long</tt> value to the narrow character stream,
     * used as the data sink.
     *
     * \param value
     * The <tt>long long</tt> value to be written to the stream.
     */
    virtual void putLongLong(long long value);

    /**
     * Writes an <tt>unsigned long long</tt> value to the narrow character
     * stream, used as the data sink.
     *
     * \param value
     * The <tt>unsigned long long</tt> value to be written to the stream.
     */
    virtual void putUnsignedLongLong(unsigned long long value);
#endif

#ifndef RW_NO_LONG_DOUBLE
    /**
     * Writes a <tt>long double</tt> value to the narrow character stream,
     * used as the data sink.
     *
     * \param value
     * The <tt>long double</tt> value to be written to the stream.
     */
    virtual void putLongDouble(long double value);
#endif

    /**
     * Writes a narrow character to the narrow character stream that is used
     * as the data sink.
     *
     * \param value
     * The narrow character to be written to the stream.
     */
    virtual void putCharacter(char value);

    /**
     * Writes a wide character to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The wide character to be written to the stream.
     */
    virtual void putWCharacter(wchar_t value);

    /**
     * Writes a UTF-16 character to the narrow character stream, used as the
     * data sink.
     *
     * \param value
     * The UTF-16 character to be written to the stream.
     */
    virtual void putUCharacter(RWUChar value);

    /**
     * Writes a \c size_t character to the narrow character stream, used as
     * the data sink.
     *
     * \param value
     * The \c size_t character to be written to the stream.
     */
    virtual void putSizeT(size_t value);

    /**
     * Writes an array of \c bool values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putBools(const bool* arrayPt, RWSize count);

    /**
     * Writes an array of \c char values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putChars(const char* arrayPt, RWSize count);

    /**
     * Writes an array of <tt>unsigned char</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putUnsignedChars(const unsigned char* arrayPt, RWSize count);

    /**
     * Writes an array of <tt>signed char</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putSignedChars(const signed char* arrayPt, RWSize count);

    /**
     * Writes an array of \c short values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putShorts(const short* arrayPt, RWSize count);

    /**
     * Writes an array of <tt>unsigned short</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putUnsignedShorts(const unsigned short* arrayPt, RWSize count);

    /**
     * Writes an array of \c int values to the narrow character stream, used
     * as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putInts(const int* arrayPt, RWSize count);

    /**
     * Writes an array of <tt>unsigned int</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putUnsignedInts(const unsigned int* arrayPt, RWSize count);

    /**
     * Writes an array of \c long values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putLongs(const long* arrayPt, RWSize count);

    /**
     * Writes an array of <tt>unsigned long</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putUnsignedLongs(const unsigned long* arrayPt, RWSize count);

    /**
     * Writes an array of \c float values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putFloats(const float* arrayPt, RWSize count);

    /**
     * Writes an array of \c double values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putDoubles(const double* arrayPt, RWSize count);

    /**
     * Writes an array of \c wchar_t values to the narrow character stream,
     * used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putWchar_ts(const wchar_t* arrayPt, RWSize count);

#if !defined(RW_NO_LONG_LONG)
    /**
     * Writes an array of <tt>long long</tt> values to the narrow character
     * stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putLongLongs(const long long* arrayPt, RWSize count);

    /**
     * Writes an array of <tt>unsigned long long</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putUnsignedLongLongs(const unsigned long long* arrayPt, RWSize count);
#endif

#ifndef RW_NO_LONG_DOUBLE
    /**
     * Writes an array of <tt>long double</tt> values to the narrow
     * character stream, used as the data sink.
     *
     * \param arrayPt
     * A pointer to the array's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putLongDoubles(const long double* arrayPt, RWSize count);
#endif

    /**
     * Writes a narrow character string to the narrow character stream, used
     * as the data sink.
     *
     * \param string
     * A pointer to the string's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putString(const char* string, RWSize count);

    /**
     * Writes a wide character string to the narrow character stream, used
     * as the data sink.
     *
     * \param wstring
     * A pointer to the string's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putWString(const wchar_t* wstring, RWSize count);

    /**
     * Writes a UTF-16 character string to the narrow character stream, used
     * as the data sink.
     *
     * \param ustring
     * A pointer to the string's first element.
     *
     * \param count
     * The number of elements to be written to the stream.
     */
    virtual void putUString(const RWUChar* ustring, RWSize count);

protected:

    //--Throws no exceptions.
    /**
     * Initializes the reference to the narrow character stream that will be
     * used as the character sink.
     *
     * \param sinkStream
     * The narrow character stream that will serve as the character sink.
     */
    RWOstreamDataToCharOutputStreamImp(const RWCharOutputStream& sinkStream);

    //--Throws no exceptions.
    /**
     * Initializes the reference to the narrow character stream that will be
     * used as the character sink.
     *
     * \param sinkStream
     * The narrow character stream that will serve as the sink of
     * characters.
     *
     * \param formatter
     * An object that can be used to modify the format generated by the
     * stream. This object is initialized by the stream, and then returned
     * to the caller.
     */
    RWOstreamDataToCharOutputStreamImp(const RWCharOutputStream& sinkStream,
                                       std::ios*& formatter);

    /**
     * Returns the embedded iostreams \b std::ostream object that is used to
     * format data. Throws no exceptions.
     */
    std::ostream& getOstream()
    {
        return RW_EXPOSE(os_);
    }

    /**
     * \copydoc getOstream()
     */
    const std::ostream& getOstream() const
    {
        return os_;
    }

    /**
     * Returns the embedded iostreams \b std::ostream object that is used to
     * format data.
     *
     * \exception RWExternalStreamException
     * Thrown when the call to the embedded \b std::ostream object used to
     * format data is in a bad or fail state.
     */
    std::ostream& getCheckedOstream();

    /**
     * \copydoc getCheckedOstream()
     */
    const std::ostream& getCheckedOstream() const;

    /**
     * Returns a reference to the \b std::ios base class of the embedded
     * \b std::ostream object, used to format the data inserted in this
     * output stream object. The \b std::ios reference can then be used to
     * modify the format flags used by the embedded \b std::ostream object
     * when generating the formatted US-ASCII representation of the data
     * inserted in this output stream.
     */
    std::ios& getIos()
    {
        return os_;
    }

private:

    void addFillCharacter();

    RWTScopedPointer<RWStreambufToCharOutputStream> buf_;
    std::ostream os_;

};

#if defined(_MSC_VER)
#  pragma warning(pop)
#endif

#endif // rw_stream_RWOstreamDataToCharOutputStreamImp_h_
