@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_edrc_desc.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_edrc_field.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_alias_map.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_calendar.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_holiday.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_destinationdesc.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_pipeline.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_uom.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_resource.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_exchange_rate.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_taxcode.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_taxgroup.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_tax.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_glaccount.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_service.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_serviceclass.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_ref_map.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_map_group.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_servicecode_map.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_usageclass.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_usageclass_map.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_usc_group.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_rsc_group.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_apn_group.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_zonemodel.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_impact_category.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_standard_zone.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_usagetype.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_usagescenario_map.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_apn_map.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discarding.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_daycode.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_timeinterval.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_timezone.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_timemodel.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_timemodel_lnk.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_pricemodel.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_pricemodel_step.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountmodel.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountmdl_ver.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountmaster.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountdetail.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discounttrigger.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountcondition.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountrule.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountstep.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountbalimpact.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_discountmdl_cnf.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_rateplan.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_rateplan_ver.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_rateplan_cnf.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_specialdayrate.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_specialday_lnk.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_networkoper.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_networkmodel.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_icproduct_all.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_splittingtype_all.sql
@/home/pin/opt/portal/ifw/conf/pricingdata/Oracle/ifw_seqcheck.sql
exit
