# Copyright (c) 2022 Oracle and/or its affiliates. 
#------------------------------------------------------------------------------#
# FILE: RELM.properties
#
# DESCRIPTION:
#
# Contains configuration parameters for the REL Manager ...
#
# INFORMATION:
#
# REL Manager ...
#
# REVISION:
#
# $Revision: 1.9 $
# $Author: ri-user-1 $
# $Date: 2022/10/31 14:37:53 $
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# REL Manager Configuration
#------------------------------------------------------------------------------#
#
# JDBC Connection Pool ...
#
# The BRM database schema number (if not defined on the command-line). The following entries may
# subsequently be determined by the schema number in multi-schema deployments (appending '.<schema>'):
#
#    connenctionURL.x     - Schema-specific database service configuration
#    user.x               - Schema-specific user (schema) name.
#    wallet_entry_name.x  - Schema-specific wallet reference (if using wallet)
#

rel_manager.dbno = 1
rel_manager.jdbc_pool.connectionURL.1 = jdbc:oracle:thin:@//${HOSTNAME}:1521/BRM
#rel_manager.jdbc_pool.connectionURL.2 = jdbc:oracle:thin:@//${HOSTNAME}:1521/BRM
rel_manager.jdbc_pool.user.1 = pin
rel_manager.jdbc_pool.wallet_location = ${BRM_CONF_WALLET}
rel_manager.jdbc_pool.wallet_entry_name.1 = infranet.rel.password
rel_manager.jdbc_pool.poolName = REL Manager Connection Pool
rel_manager.jdbc_pool.validateSchema = true
rel_manager.jdbc_pool.initialPoolSize = 1
rel_manager.jdbc_pool.minPoolSize = 1
rel_manager.jdbc_pool.maxPoolSize = 2
rel_manager.jdbc_pool.connectionWaitTimeout = 5
rel_manager.jdbc_pool.validateConnectionOnBorrow = false
rel_manager.jdbc_pool.sqlForValidateConnection = SELECT SYSDATE FROM DUAL
rel_manager.jdbc_pool.fastConnectionFailoverEnabled = false
rel_manager.jdbc_pool.onsConfiguration =
rel_manager.jdbc_pool.maxStatements = 25
rel_manager.jdbc_pool.jmxEnabled = false
#rel_manager.jdbc_pool.metricUpdateInterval = 10
#rel_manager.jdbc_pool.poolLogLevel = INFO

# SSL DB configuration

rel_manager.jdbc_pool.dbSSLEnabled = false
rel_manager.jdbc_pool.dbSSLClientAuth = false
rel_manager.jdbc_pool.sslTrustStoreLocation = __DB_SSL_TRUSTSTORE_LOC__/cwallet.sso
rel_manager.jdbc_pool.sslKeyStoreLocation = __DB_SSL_KEYSTORE_LOC__/cwallet.sso
#rel_manager.jdbc_pool.wallet_entry_name.sslTrustStorePwd=infranet.rel.db.ssl.truststore.password
#rel_manager.jdbc_pool.wallet_entry_name.sslKeyStorePwd=infranet.rel.db.ssl.keystore.password

#
# Global application settings ...
# 
rel_manager.table_format_file = ${PIN_HOME}/apps/rel_manager/TableFormat.properties
# The console prompt to use - the %s token will be replaced with the schema number (e.g. "RELManager-0.0.0.1>")
rel_manager.console_prompt = RELManager-%s>
# The default history file is '.rel_manager_history' - it can be changed below
#rel_manager.history_file = ${PIN_HOME}/apps/rel_manager/alternative_history_file
# Specifies whether to strip directory paths from the filename shown
rel_manager.view.strip_directory_path = true

#
# Commands to be made available. If commands are not required by the application they can be commented
# out below. E.g. if zip files are not used in the deployment, comment out commands 9 through 13 below.
#
rel_manager.commands.1 = com.oracle.brm.rel_manager.SearchComplete
rel_manager.commands.2 = com.oracle.brm.rel_manager.SearchUpdateFailure
rel_manager.commands.3 = com.oracle.brm.rel_manager.SearchLoadFailure
rel_manager.commands.4 = com.oracle.brm.rel_manager.SearchPoid
rel_manager.commands.5 = com.oracle.brm.rel_manager.RetrySession
rel_manager.commands.6 = com.oracle.brm.rel_manager.PurgeComplete
rel_manager.commands.7 = com.oracle.brm.rel_manager.SummaryReport
rel_manager.commands.8 = com.oracle.brm.rel_manager.SearchDetailReport
rel_manager.commands.9 = com.oracle.brm.rel_manager.ZipSummaryReport
rel_manager.commands.10 = com.oracle.brm.rel_manager.ZipDetailReport
rel_manager.commands.11 = com.oracle.brm.rel_manager.ZipFileWrite
rel_manager.commands.12 = com.oracle.brm.rel_manager.ZipFileSearch
rel_manager.commands.13 = com.oracle.brm.rel_manager.ZipFileReload
rel_manager.commands.14 = com.oracle.brm.rel_manager.RELMonitorSummaryReport
rel_manager.commands.15 = com.oracle.brm.rel_manager.RELMonitorDetailReport
rel_manager.commands.16 = com.oracle.brm.rel_manager.RELMonitorPurge

# Directory in which to place (un)zipped data for correction
rel_manager.zip_directory = ${HOME}/data/unzipped
