PCM_OP_GSM_AUTHORIZE {
   Session-Id = $U 
   CC-Request-Type = 1
   CC-Request-Number = 4
   User-Name = $O 
   Called-Station-Id = $D
   Calling-Station-Id = $O 
   Auth-Application-Id = 5
   Origin-Host = 'aaagw.portal.orig.host'
   Origin-Realm = 'aaagw.portal.orig.realm'
   Destination-Realm = 'aaagw.portal.dest.realm'
   Event-Timestamp = $T-100
   Subscription-Id = (
      Subscription-Id-Type=1
      Subscription-Id-Data=$O
   Subscription-Id = )
   Requested-Service-Unit = (
    CC-Time = $R(100,200)
   Requested-Service-Unit = )
  }

PCM_OP_GSM_REAUTHORIZE {
   Session-Id = $S 
   CC-Request-Type = 2
   CC-Request-Number = 4
   User-Name = $S 
   Called-Station-Id = $S
   Calling-Station-Id = $S 
   Auth-Application-Id = 5
   Origin-Host = 'aaagw.portal.orig.host'
   Origin-Realm = 'aaagw.portal.orig.realm'
   Destination-Realm = 'aaagw.portal.dest.realm'
   Event-Timestamp = $T-100
   Subscription-Id = (
      Subscription-Id-Type=1
      Subscription-Id-Data=$S
   Subscription-Id = )
   Requested-Service-Unit = (
    CC-Time = $R(100,200)
   Requested-Service-Unit = )
  }

PCM_OP_GSM_REAUTHORIZE {
   Session-Id = $S 
   CC-Request-Type = 2
   CC-Request-Number = 4
   User-Name = $S 
   Called-Station-Id = $S
   Calling-Station-Id = $S 
   Auth-Application-Id = $S
   Origin-Host = 'aaagw.portal.orig.host'
   Origin-Realm = 'aaagw.portal.orig.realm'
   Destination-Realm = 'aaagw.portal.dest.realm'
   Event-Timestamp = $T-100
   Subscription-Id = (
      Subscription-Id-Type=1
      Subscription-Id-Data=$S
   Subscription-Id = )
   Requested-Service-Unit = (
    CC-Time = $R(100,200)
   Requested-Service-Unit = )
  }

PCM_OP_GSM_STOP_ACCOUNTING {
   Session-Id = $S
   CC-Request-Type = 3
   CC-Request-Number = 4
   User-Name = $S
   Called-Station-Id = $S
   Calling-Station-Id = $S
   Auth-Application-Id = $S
   Origin-Host = 'aaagw.portal.orig.host'
   Origin-Realm = 'aaagw.portal.orig.realm'
   Destination-Realm = 'aaagw.portal.dest.realm'
   Event-Timestamp = $T+1000
   Subscription-Id = (
      Subscription-Id-Type=1
      Subscription-Id-Data=$S
   Subscription-Id = )
   Used-Service-Unit = (
    CC-Time = $R(100,200)
   Used-Service-Unit = )
  }
