#
#======================================================================
# Configuration File for the Sample Object Creation Application
#======================================================================
#
#======================================================================
# Use this file to specify how the sample application connects with
# Infranet.
#
# A copy of this configuration file is automatically installed and 
# configured with default values when you install Infranet. However,
# you can edit this file to suit your specific configuration:
#  -- You can change the default value of an entry.
#  -- You can exclude an optional entry by adding the # symbol
#     at the beginning of the line.
#  -- You can include a commented entry by removing the # symbol.
#
# Before you make any changes to this file, save a backup copy.
#
# To edit this file, follow the instructions in the commented sections.
# For more information on the general syntax of configuration entries,
# see "Reference Guide to Infranet Configuration Files" in the Infranet
# online documentation.
#======================================================================
#
#
#======================================================================
# cm_ptr
# 
# Pointer to the CM/CMMP. 
#
# Use a separate entry for each CM/CMMP. If the application can't
# find the first CM/CMMP, it looks for the next in the list.
#
# Each entry includes three values:
#  -- <protocol>: the protocol must be "ip" for this release
#  -- <hostname>: name or IP address of the computer running
#          the CM/CMMP
#  -- <port>: TCP port number of the CM/CMMP on this computer
#
# The port number should match a corresponding cm_ports entry with
# the same port number in the CM/CMMP configuration file. The 
# default, 11960, is a commonly specified port for the CM/CMMP.
#======================================================================
- nap	cm_ptr	ip	XXX	11960
#- nap cm_ptr	ip	<hostname2>	<port2>


#======================================================================
# userid
#
# Database number and service type for the Infranet database. 
#
# The CM uses the database number to identify the Infranet database 
# and connect to the correct Data Manager. For connections that don't
# require a login name and password, the CM also passes the service
# type to the database.
#
# The database number, in the form 0.0.0.N, is the number assigned to 
# your Infranet database when you installed the system. The default
# is 0.0.0.1.
#
# The service type is "/service/pcm_client", with an ID of  "1".
# Do not change these values.
#======================================================================
- -	userid	0.0.0.1 /service/pcm_client 1


#======================================================================
# These entries contain the login information for connecting
# to the CM:
# 
#  -- "login_type" specifies whether the login name and password 
#     are required. Type 1, the default, indicates that name and 
#     password are required. Type 0 indicates that only the user
#     ID is required.
#
#  -- "login_name" specifies the login name to use when the 
#     sample application requests a connection to the CM. If 
#     "login_type" is 0, you don't need to specify a login name.
#
#  -- "login_pw" specifies the password to use when the sample
#     application connects to the CM. If "login_type" is 0, you 
#     don't need to specify a password.
#======================================================================
- nap	login_type	1
- nap	login_name	XXX
- nap	login_pw	XXX
