#
#       
# Copyright (c) 1996, 2023, Oracle and/or its affiliates. All rights reserved. 
#       
#       This material is the confidential property of Oracle Corporation or its
#       licensors and may be used, reproduced, stored or transmitted only in
#       accordance with a valid Oracle license or sublicense agreement.
#

#       A database number must conform to the format int.int.int.int.
#       A priority must be a value greater than 0.
#       A max account size must be a value greater than 0.
#       A status is either OPEN, CLOSED or UNAVAILABLE
#         OPEN means that the database is available for account
#         creation.
#
#         CLOSED means that the database has reached the 'full'
#         status, and will not be used for account creation unless
#         all other databases are CLOSED, or the account you are
#         creating has a billing relationship (sponsor, brand,
#         subordinate) with another account in this database.
#
#         UNAVAILABLE means never use the database unless forced to by the 
#         rule that a subordinate/sponsored/brand account must be in
#         the same database as its parent. 
#
#         The difference between CLOSED and UNAVAILABLE is that if all
#         databases are CLOSED, one of them will be chosen for account
#         creation. One labelled UNAVAILABLE will never be chosen.
#         This logic is controllable via policy; see fm_cust_pol_get_db_no
#--------------------------------------------------------------------------


DB_NO = "0.0.0.1" ;             # 1st database config block.
PRIORITY = 1 ;
MAX_ACCOUNT_SIZE = 100000 ;
STATUS = "OPEN" ;
SCHEMA_NAME = "pin15" ;

#DB_NO = "0.0.0.2" ;             # 2nd database config block.
#PRIORITY = 1 ;
#MAX_ACCOUNT_SIZE = 100000 ;
#STATUS = "UNAVAILABLE" ;
#SCHEMA_NAME = "pin211x" ;

# 1st database config block, With logical partition
#DB_NO = "0.1.0.1" ;             
#PRIORITY = 1 ;
#MAX_ACCOUNT_SIZE = 100000 ;
#STATUS = "UNAVAILABLE" ;
#SCHEMA_NAME = "pin211x" ;
