#!/bin/sh
#
# @(#)% %
#
# Copyright (c) 2013, 2024, Oracle and/or its affiliates..
#       This material is the confidential property of Oracle Corporation
#       or its licensors and may be used, reproduced, stored
#       or transmitted only in accordance with a valid Oracle license
#       or sublicense agreement.
#

# From 11GR2 onwards, on 64-bit machines, 32-bit oracle client libraries are
# not installed in the lib32 directory. Full 32-bit oracle client needs to be
# installed in a separate ORACLE_HOME and the client libraries in the
# lib directory should be used and ORACLE_HOME needs to be set
# to reflect the client install in this script .

# In the next major release, we can let installer replace tokens for
# 32-bit client install home directory and the oracle version
# Then we can derive the libraries for use in this script

# For 11G2 , set to client install home
# ORACLE_HOME=
# export ORACLE_HOME
# ORA_CLIENT_LIB_PATH=$ORACLE_HOME/lib

# For 11GR1
ORA_CLIENT_LIB_PATH=${ORACLE_HOME}/lib32

# From 7.5 onwards, java6 is being used so we should be using ojdbc6.jar
# from oracle client. 11G Oracle client is recommended since
# 10G client does not ship with ojdbc6.jar.
OJDBCJAR=ojdbc8.jar

REL_LIBS=${ORA_CLIENT_LIB_PATH}:${PIN_HOME}/lib64:${PIN_HOME}/lib


uname=`uname`
if [ "$LD_LIBRARY_PATH" = "" ];
then
      LD_LIBRARY_PATH=${REL_LIBS}
else
      LD_LIBRARY_PATH=${REL_LIBS}:${LD_LIBRARY_PATH}
fi
export LD_LIBRARY_PATH
      

__JAVA_HOME__/bin/java -classpath __JAVA_HOME__/lib/rt.jar:${ORACLE_HOME}/jdbc/lib/${OJDBCJAR}:${ORACLE_HOME}/lib/${OJDBCJAR}:${ORACLE_HOME}/jdbc/lib/classes12.zip:__PIN_HOME__/jars/pcm.jar:__PIN_HOME__/jars/oraclepki.jar:__PIN_HOME__/jars/osdt_cert.jar:__PIN_HOME__/jars/osdt_core.jar:__PIN_HOME__/jars/pcmext.jar:__PIN_HOME__/jars/virtualcolumns.jar:. -mx64m com.portal.vcol.Vcol $@


