#
#	@(#)% %
# 
# Copyright (c) 1996, 2015, Oracle and/or its affiliates. All rights reserved.
# 
#	This material is the confidential property of Oracle Corporation or its
#	licensors and may be used, reproduced, stored or transmitted only in
#	accordance with a valid Oracle license or sublicense agreement.
#

#
# This file contains the configuration information necessary for 
# the pin_amt_install installation script.
#

$PIN_AMT_SCRIPT_LOCATION = "$PIN_MD_INFRANET_BASE/sys/amt/data";
$PIN_AMT_PROPERTIES_LOCATION="$PIN_MD_INFRANET_BASE/sys/amt";
$PIN_AMT_JARS_LOCATION="$PIN_MD_INFRANET_BASE/jars";

if ($PIN_MD_SQL_PLATFORM =~ /Oracle/i) {
   $PIN_AMT_CONTROLLER_SCHEMA_SCRIPT = "create_amt_controller_schema.sql";
   $PIN_AMT_UPDATE_UNIQUENESS_TABLE_SCRIPT = "create_update_uniqueness_table.sql";
   $PIN_AMT_MOVER_SCHEMA_SCRIPT  = "create_amt_mover_schema.sql";
   $PIN_AMT_CLEANUP_INSTANCE_SCRIPT = "create_cleanup_instance.sql";
   $PIN_AMT_COMPARE_RECORD_SCRIPT = "create_compare_record.sql";
   $PIN_AMT_GENERATE_POID_TYPE_MAP_SCRIPT = "create_generate_poid_type_map.sql";
   $PIN_AMT_GENERATE_AMT_METADATA_SCRIPT = "create_generate_amt_metadata.sql";
   $PIN_AMT_MV_PKB_SCRIPT = "create_amt_mv_pkb.sql";
   $PIN_AMT_MV_PKG_SCRIPT = "create_amt_mv_pkg.sql";
   $PIN_AMT_RERATE_PKB_SCRIPT = "create_amt_rerate_pkb.sql";
   $PIN_AMT_RERATE_PKG_SCRIPT = "create_amt_rerate_pkg.sql";
   $PIN_AMT_GROUP_SEARCH_PKG_SCRIPT = "create_amt_group_search_pkg.sql";
   $PIN_AMT_GROUP_SEARCH_PKB_SCRIPT = "create_amt_group_search_pkb.sql";
   $PIN_AMT_PROPERTIES = "Infranet.properties";
   $PCM_JAR = "pcm.jar";
   $PCMEXT_JAR = "pcmext.jar";
   $SPAMT_JAR = "spamt.jar"; 	
   $PIN_AMT_CREATE_INDEXES_SCRIPT = "create_amt_indexes.source";
   $PIN_AMT_GRANT_PERMISSIONS = "create_grant_amt_permissions.sql";
}
