#=======================================================================
# $Header: install_vob/install_odc/Server/ISMP/Portal_Base/scripts/pin_cnf_generate_analytics.pl /cgbubrm_7.5.0.portalbase/1 2015/12/15 01:20:22 vmoteth Exp $
#
# Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
#
#    This material is the confidential property of Oracle Corporation
#    or its licensors and may be used, reproduced, stored
#    or transmitted only in accordance with a valid Oracle license or
#    sublicense agreement.
#
#========================================================================
$PIN_GA_PINCONF_HEADER =  <<END
#************************************************************************
# Configuration Entries for Logging Problems with the Billing Programs
#
#
# Use these entries to specify how the generate analytics applications log
# information about their activity.
#
# This configuration file is automatically installed and configured with
# default values during Portal installation. You can edit this file to:
#   -- change the default values of the entries.
#   -- disable an entry by inserting a crosshatch (#) at the start of
#        the line.
#   -- enable a commented entry by removing the crosshatch (#).
#
# Before you make any changes to this file, save a backup copy.
#
# When editing this file, follow the instructions in each section.
# For more information on the general syntax of configuration entries,
# see "Reference Guide to Portal Configuration Files" in the Portal
# online documentation.
#************************************************************************
END
;

%PIN_GA_PINCONF_ENTRIES = (
        "pin_generate_analytics_logfile_description", <<END
#========================================================================
# logfile
#
# Specifies the full path to the log file for the pin_generate_analytics 
# application.
#
# You can enter any valid path.
#========================================================================
END
	,"pin_generate_analytics_logfile", "- pin_generate_analytics logfile \$\{PIN_LOG_DIR\}/pin_generate_analytics/pin_generate_analytics.pinlog"
	,"pin_generate_analytics_loglevel_description", <<END

#========================================================================
# loglevel
#
# Specifies how much information the generate analytics application logs.
#
# The value for this entry can be:
#
#    0 = no logging
#    1 = (Default) log error messages only
#    2 = log error messages and warnings
#    3 = log error, warning, and debugging messages
#========================================================================
END
        ,"pin_generate_analytics_loglevel", "- pin_generate_analytics loglevel 2"
	,"deadlock_retry_count_description", <<END

#========================================================================
# Deadlock Retry Count
#
# Specified the number of attempts to bill an account again in
# case of a deadlock error.
#
# This entry is required for SQL Server databases.  For other databases,
# this is an optional parameter.  For better performance this count
# should be set depending on the volumes of the accounts to be billed.
#
#========================================================================
END
        ,"deadlock_retry_count", "- pin_generate_analytics  deadlock_retry_count  20"
	,"pin_mta_hotlist_description", <<END

#=====================================================================
# hotlist
#
# Use this entry to set the location (path and filename) of the hot
# list file.
#
# A hot list is a file containing an array of poids, which need to be
# handled by the mta application's working threads first. This
# allows some threads to begin working on some known large or complex
# accounts/bills as early as possible. The array of poids might be
# hard-coded in the host list file, or possibly the file could be
# generated by some other application.
#
# The array of poids must be in flist format. Refer to the example
# files in the distribution for more information about this file.
#======================================================================
END
        ,"pin_mta_hotlist", "- pin_mta hotlist hotlist"
        ,"pin_mta_loglevel_description", <<END
#======================================================================
# loglevel
#
# How much information the applications should log.
#
# The value for this entry can be:
#  -- 0: no logging
#  -- 1: log error messages only
#  -- 2: log error messages and warnings
#  -- 3: log error messages, warnings, and debugging messages
#======================================================================
END
        ,"pin_mta_loglevel", "- pin_mta loglevel 2"
        ,"pin_mta_multi_db_description", <<END
#======================================================================
# multi_db
#
# Enables or disables the multidatabase capability of MTA.
#
# If you enable multi_db, MTA uses global searching instead of the
# normal searching. The value for this entry can be:
#
#    0 = (Default) Disable global searching
#    1 = Enable global searching
#======================================================================
END
        ,"pin_mta_multi_db", "- pin_mta multi_db 0"
        ,"pin_mta_monitor_description", <<END
#======================================================================
# monitor
#
# Use this entry to set the path and name of shared memory map file.
# This binary file stores information about the running mta application.
# With the help of another application (like pin_mta_monitor), you can
# view and modify the number of threads that are running in the MTA
# application without interrupting the application.
#
#======================================================================
END
        ,"pin_mta_monitor", "- pin_mta monitor monitor"
        ,"pin_mta_performance_description", <<END
#======================================================================
# Performance Parameters
#
# These parameters govern how the MTA applications pulls data from the
# database and tranfers it to the application space. They also
# define how many threads (children) are used to process the data in
# the application.
#
#  -- children:   number of threads used to process the accounts in the
#                 application
#  -- per_batch:  number of accounts processed by each child
#  -- per_step:   number of accounts returned in each database search
#  -- fetch_size: number of accounts cached in application memory
#                 before processing starts
#
# Not all application use all these performance parameters. For example,
# pin_inv_accts does not use per_batch.
#
# You can edit these entries to improve the performance of MTA
# applications. You typically need to configure these parameters
# differently for each application. To specify an entry for
# a specific MTA application, replace the generic "pin_mta"
# name with the specific name of the application. In the following
# example pin_inv_accts will use 50000 for the fetch size whereas other
# applications using this configuration file will use 30000 for the
# fetch_size :
#   - pin_mta          fetch_size  30000
#   - pin_inv_accts    fetch_size  50000
#
# For a complete explanation of setting these variables
# for best performance, see "Improving System Performance" in
# the online documentation.
#
#======================================================================
END
        ,"pin_mta_performance"
        ,"- pin_mta       children        5
- pin_mta       per_batch       500
- pin_mta       per_step        1000
- pin_mta       fetch_size      5000"

        ,"pin_mta_logfile_description", <<END
#========================================================================
# mta_logfile
#
# Specifies the full path to the log file used by this MTA application.
#
# You can enter any valid path.
#========================================================================
END
        ,"pin_mta_logfile", "- pin_mta logfile \$\{PIN_LOG_DIR\}/pin_generate_analytics/pin_mta.pinlog"
);

