--
--ER/Studio 6.5 SQL Code Generation
-- Project :      JSA_Create.DM1
--
-- Date Created : Wednesday, March 09, 2005 17:07:33
-- Target DBMS : Oracle 9i
--

-- 
-- SEQUENCE: JSA_SEQ_BULLETINBOARD_ID 
--

CREATE SEQUENCE JSA_SEQ_BULLETINBOARD_ID 
    START WITH 100
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999
    NOCYCLE
    CACHE 20
    NOORDER
/
grant select on JSA_SEQ_BULLETINBOARD_ID to ROLE_JSA_ALL
/
grant select on JSA_SEQ_BULLETINBOARD_ID to ROLE_JSA_SEL
/

-- 
-- SEQUENCE: JSA_SEQ_MODULE_ID 
--

CREATE SEQUENCE JSA_SEQ_MODULE_ID 
    START WITH 100
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999
    NOCYCLE
    CACHE 20
    NOORDER
/
grant select on JSA_SEQ_MODULE_ID to ROLE_JSA_ALL
/
grant select on JSA_SEQ_MODULE_ID to ROLE_JSA_SEL
/

-- 
-- SEQUENCE: JSA_SEQ_USER_ID 
--

CREATE SEQUENCE JSA_SEQ_USER_ID 
    START WITH 100
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999
    NOCYCLE
    CACHE 20
    NOORDER
/
grant select on JSA_SEQ_USER_ID to ROLE_JSA_ALL
/
grant select on JSA_SEQ_USER_ID to ROLE_JSA_SEL
/

-- 
-- SEQUENCE: JSA_SEQ_USERGROUP_ID 
--

CREATE SEQUENCE JSA_SEQ_USERGROUP_ID 
    START WITH 100
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999
    NOCYCLE
    CACHE 20
    NOORDER
/
grant select on JSA_SEQ_USERGROUP_ID to ROLE_JSA_ALL
/
grant select on JSA_SEQ_USERGROUP_ID to ROLE_JSA_SEL
/

-- 
-- TABLE: JSA_BULLETINBOARD 
--

CREATE TABLE JSA_BULLETINBOARD(
    BBS_ID         NUMBER(9, 0)     NOT NULL,
    BBS_INFO       VARCHAR2(254)    NOT NULL,
    BBS_VALIDTO    DATE,
    ENTRYDATE      DATE              DEFAULT SYSDATE NOT NULL,
    ENTRYBY        NUMBER           NOT NULL,
    MODIFDATE      DATE,
    MODIFBY        NUMBER,
    MODIFIED       NUMBER            DEFAULT 1 NOT NULL
                   CONSTRAINT CKC_JSA_BULLET_MODIFIED CHECK (MODIFIED in (0,1)),
    RECVER         NUMBER            DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JSA_BULLETINBOARD PRIMARY KEY (BBS_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_BULLETINBOARD IS 'JSA_BULLETINBOARD'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.BBS_ID IS 'BBS_ID'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.BBS_INFO IS 'BBS_INFO'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.BBS_VALIDTO IS 'BBS_VALIDTO'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.ENTRYDATE IS 'ENTRYDATE'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.ENTRYBY IS 'ENTRYBY'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.MODIFDATE IS 'MODIFDATE'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.MODIFBY IS 'MODIFBY'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.MODIFIED IS 'MODIFIED'
/
COMMENT ON COLUMN JSA_BULLETINBOARD.RECVER IS 'RECVER'
/
grant select, insert, update, delete on JSA_BULLETINBOARD to ROLE_JSA_ALL
/
grant select on JSA_BULLETINBOARD to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_CONFIG 
--

CREATE TABLE JSA_CONFIG(
    CONFIG_ID    NUMBER(9, 0)      NOT NULL,
    USER_ID      NUMBER(9, 0)      NOT NULL,
    KEYWORD      VARCHAR2(254),
    KEYVALUE     VARCHAR2(2000),
    CONSTRAINT PK_JSA_CONFIG PRIMARY KEY (CONFIG_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_CONFIG IS 'JSA_CONFIG'
/
COMMENT ON COLUMN JSA_CONFIG.CONFIG_ID IS 'CONFIG_ID'
/
COMMENT ON COLUMN JSA_CONFIG.USER_ID IS 'internal user-id (pk) of the user'
/
COMMENT ON COLUMN JSA_CONFIG.KEYWORD IS 'KEYWORD'
/
COMMENT ON COLUMN JSA_CONFIG.KEYVALUE IS 'KEYVALUE'
/
grant select, insert, update, delete on JSA_CONFIG to ROLE_JSA_ALL
/
grant select on JSA_CONFIG to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_GROUPRIGHT 
--

CREATE TABLE JSA_GROUPRIGHT(
    USERGROUP_ID    NUMBER(9, 0)    NOT NULL,
    MODULE_ID       NUMBER(9, 0)    NOT NULL,
    CANINSERT       NUMBER          NOT NULL
                    CONSTRAINT CKC_JSA_GROUPR_CANINSERT CHECK (CANINSERT in (0,1)),
    CANUPDATE       NUMBER          NOT NULL
                    CONSTRAINT CKC_JSA_GROUPR_CANUPDATE CHECK (CANUPDATE in (0,1)),
    CANDELETE       NUMBER          NOT NULL
                    CONSTRAINT CKC_JSA_GROUPR_CANDELETE CHECK (CANDELETE in (0,1)),
    CANREAD         NUMBER          NOT NULL
                    CONSTRAINT CKC_JSA_GROUPR_CANREAD CHECK (CANREAD in (0,1)),
    CANPRINT        NUMBER          NOT NULL
                    CONSTRAINT CKC_JSA_GROUPR_CANPRINT CHECK (CANPRINT in (0,1)),
    ENTRYDATE       DATE             DEFAULT SYSDATE NOT NULL,
    ENTRYBY         NUMBER          NOT NULL,
    MODIFDATE       DATE,
    MODIFBY         NUMBER,
    MODIFIED        NUMBER           DEFAULT 1 NOT NULL
                    CONSTRAINT CKC_JSA_GROUPR_MODIFIED CHECK (MODIFIED in (0,1)),
    RECVER          NUMBER           DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JSA_GROUPRIGHT PRIMARY KEY (USERGROUP_ID, MODULE_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_GROUPRIGHT IS 'defininition of the group rights per modul'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.USERGROUP_ID IS 'internal group-id (pk)'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.MODULE_ID IS 'internal modul-id'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.CANINSERT IS 'insert allowed'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.CANUPDATE IS 'update allowed'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.CANDELETE IS 'delete allowed'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.CANREAD IS 'Read allowed'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.CANPRINT IS 'Print allowed'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.ENTRYDATE IS 'ENTRYDATE'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.ENTRYBY IS 'ENTRYBY'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.MODIFDATE IS 'MODIFDATE'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.MODIFBY IS 'MODIFBY'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.MODIFIED IS 'MODIFIED'
/
COMMENT ON COLUMN JSA_GROUPRIGHT.RECVER IS 'RECVER'
/
grant select, insert, update, delete on JSA_GROUPRIGHT to ROLE_JSA_ALL
/
grant select on JSA_GROUPRIGHT to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_GROUPUSER 
--

CREATE TABLE JSA_GROUPUSER(
    USERGROUP_ID    NUMBER(9, 0)    NOT NULL,
    USER_ID         NUMBER(9, 0)    NOT NULL,
    CONSTRAINT PK_JSA_GROUPUSER PRIMARY KEY (USERGROUP_ID, USER_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_GROUPUSER IS 'definition of which users are in which groups'
/
COMMENT ON COLUMN JSA_GROUPUSER.USERGROUP_ID IS 'internal group-id (pk), incremented by 1 for each new row within each company'
/
COMMENT ON COLUMN JSA_GROUPUSER.USER_ID IS 'internal user-id (pk) of the user'
/
grant select, insert, update, delete on JSA_GROUPUSER to ROLE_JSA_ALL
/
grant select on JSA_GROUPUSER to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_MODULE 
--

CREATE TABLE JSA_MODULE(
    MODULE_ID      NUMBER(9, 0)     NOT NULL,
    MODULENAME     VARCHAR2(35)     NOT NULL,
    NAME           VARCHAR2(35)     NOT NULL,
    DESCRIPTION    VARCHAR2(254),
    ENTRYDATE      DATE              DEFAULT SYSDATE NOT NULL,
    ENTRYBY        NUMBER           NOT NULL,
    MODIFDATE      DATE,
    MODIFBY        NUMBER,
    MODIFIED       NUMBER            DEFAULT 1 NOT NULL
                   CONSTRAINT CKC_JSA_MODULE_MODIFIED CHECK (MODIFIED in (0,1)),
    RECVER         NUMBER            DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JSA_MODULE PRIMARY KEY (MODULE_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
STORAGE(PCTINCREASE 0
        )
/



COMMENT ON TABLE JSA_MODULE IS 'definition of all moduls'
/
COMMENT ON COLUMN JSA_MODULE.MODULE_ID IS 'internal module-id (pk), incremented by 1 for each new row within each program-id'
/
COMMENT ON COLUMN JSA_MODULE.MODULENAME IS 'According to this modulename the rights for a module are attached'
/
COMMENT ON COLUMN JSA_MODULE.NAME IS 'The name of the module.'
/
COMMENT ON COLUMN JSA_MODULE.DESCRIPTION IS 'description of the global functionality of the module'
/
COMMENT ON COLUMN JSA_MODULE.ENTRYDATE IS 'ENTRYDATE'
/
COMMENT ON COLUMN JSA_MODULE.ENTRYBY IS 'ENTRYBY'
/
COMMENT ON COLUMN JSA_MODULE.MODIFDATE IS 'MODIFDATE'
/
COMMENT ON COLUMN JSA_MODULE.MODIFBY IS 'MODIFBY'
/
COMMENT ON COLUMN JSA_MODULE.MODIFIED IS 'MODIFIED'
/
COMMENT ON COLUMN JSA_MODULE.RECVER IS 'RECVER'
/
grant select, insert, update, delete on JSA_MODULE to ROLE_JSA_ALL
/
grant select on JSA_MODULE to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_USER 
--

CREATE TABLE JSA_USER(
    USER_ID          NUMBER(9, 0)    NOT NULL,
    LEADER_ID        NUMBER(9, 0),
    ACTIVE           NUMBER          NOT NULL
                     CONSTRAINT CKC_JSA_USER_ACTIVE CHECK (ACTIVE in (0,1)),
    LOGIN            VARCHAR2(18)    NOT NULL,
    USR_FIRSTNAME    VARCHAR2(35),
    USR_LASTNAME     VARCHAR2(35),
    USR_AUTHID       VARCHAR2(15),
    ENTRYDATE        DATE             DEFAULT SYSDATE NOT NULL,
    ENTRYBY          NUMBER          NOT NULL,
    MODIFDATE        DATE,
    MODIFBY          NUMBER,
    MODIFIED         NUMBER           DEFAULT 1 NOT NULL
                     CONSTRAINT CKC_JSA_USER_MODIFIED CHECK (MODIFIED in (0,1)),
    RECVER           NUMBER           DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JSA_USER PRIMARY KEY (USER_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_USER IS 'definition of all authorised users of the application'
/
COMMENT ON COLUMN JSA_USER.USER_ID IS 'internal user-id (pk) of the user'
/
COMMENT ON COLUMN JSA_USER.LEADER_ID IS 'internal user-id (pk) of the user'
/
COMMENT ON COLUMN JSA_USER.ACTIVE IS 'status: a=activ, d=deactiv (if deactiv, login is prohibited)'
/
COMMENT ON COLUMN JSA_USER.LOGIN IS 'login-id, the chars which sould be used in the login dialog'
/
COMMENT ON COLUMN JSA_USER.USR_FIRSTNAME IS 'the first name of the authorised person'
/
COMMENT ON COLUMN JSA_USER.USR_LASTNAME IS 'the last name of the authorised person'
/
COMMENT ON COLUMN JSA_USER.USR_AUTHID IS 'the password which should be used in the login-dialog'
/
COMMENT ON COLUMN JSA_USER.ENTRYDATE IS 'ENTRYDATE'
/
COMMENT ON COLUMN JSA_USER.ENTRYBY IS 'ENTRYBY'
/
COMMENT ON COLUMN JSA_USER.MODIFDATE IS 'MODIFDATE'
/
COMMENT ON COLUMN JSA_USER.MODIFBY IS 'MODIFBY'
/
COMMENT ON COLUMN JSA_USER.MODIFIED IS 'MODIFIED'
/
COMMENT ON COLUMN JSA_USER.RECVER IS 'RECVER'
/
grant select, insert, update, delete on JSA_USER to ROLE_JSA_ALL
/
grant select on JSA_USER to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_USERGROUP 
--

CREATE TABLE JSA_USERGROUP(
    USERGROUP_ID    NUMBER(9, 0)     NOT NULL,
    NAME            VARCHAR2(35)     NOT NULL,
    DESCRIPTION     VARCHAR2(254),
    ENTRYDATE       DATE              DEFAULT SYSDATE NOT NULL,
    ENTRYBY         NUMBER           NOT NULL,
    MODIFDATE       DATE,
    MODIFBY         NUMBER,
    MODIFIED        NUMBER            DEFAULT 1 NOT NULL
                    CONSTRAINT CKC_JSA_USERGR_MODIFIED CHECK (MODIFIED in (0,1)),
    RECVER          NUMBER            DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JSA_USERGROUP PRIMARY KEY (USERGROUP_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_USERGROUP IS 'definition of user group with name and number'
/
COMMENT ON COLUMN JSA_USERGROUP.USERGROUP_ID IS 'internal group-id (pk), incremented by 1 for each new row within each company'
/
COMMENT ON COLUMN JSA_USERGROUP.NAME IS 'name of the user group'
/
COMMENT ON COLUMN JSA_USERGROUP.DESCRIPTION IS 'DESCRIPTION'
/
COMMENT ON COLUMN JSA_USERGROUP.ENTRYDATE IS 'ENTRYDATE'
/
COMMENT ON COLUMN JSA_USERGROUP.ENTRYBY IS 'ENTRYBY'
/
COMMENT ON COLUMN JSA_USERGROUP.MODIFDATE IS 'MODIFDATE'
/
COMMENT ON COLUMN JSA_USERGROUP.MODIFBY IS 'MODIFBY'
/
COMMENT ON COLUMN JSA_USERGROUP.MODIFIED IS 'MODIFIED'
/
COMMENT ON COLUMN JSA_USERGROUP.RECVER IS 'RECVER'
/
grant select, insert, update, delete on JSA_USERGROUP to ROLE_JSA_ALL
/
grant select on JSA_USERGROUP to ROLE_JSA_SEL
/
-- 
-- TABLE: JSA_USERRIGHT 
--

CREATE TABLE JSA_USERRIGHT(
    USER_ID      NUMBER(9, 0)    NOT NULL,
    MODULE_ID    NUMBER(9, 0)    NOT NULL,
    CANINSERT    NUMBER          NOT NULL
                 CONSTRAINT CKC_JSA_USERRI_CANINSERT CHECK (CANINSERT in (0,1)),
    CANUPDATE    NUMBER          NOT NULL
                 CONSTRAINT CKC_JSA_USERRI_CANUPDATE CHECK (CANUPDATE in (0,1)),
    CANDELETE    NUMBER          NOT NULL
                 CONSTRAINT CKC_JSA_USERRI_CANDELETE CHECK (CANDELETE in (0,1)),
    CANREAD      NUMBER          NOT NULL
                 CONSTRAINT CKC_JSA_USERRI_CANREAD CHECK (CANREAD in (0,1)),
    CANPRINT     NUMBER          NOT NULL
                 CONSTRAINT CKC_JSA_USERRI_CANPRINT CHECK (CANPRINT in (0,1)),
    ENTRYDATE    DATE             DEFAULT SYSDATE NOT NULL,
    ENTRYBY      NUMBER          NOT NULL,
    MODIFDATE    DATE,
    MODIFBY      NUMBER,
    MODIFIED     NUMBER           DEFAULT 1 NOT NULL
                 CONSTRAINT CKC_JSA_USERRI_MODIFIED CHECK (MODIFIED in (0,1)),
    RECVER       NUMBER           DEFAULT 0 NOT NULL,
    CONSTRAINT PK_JSA_USERRIGHT PRIMARY KEY (USER_ID, MODULE_ID)
    USING INDEX
        PCTFREE 5
        INITRANS 2
        TABLESPACE JSA_TS_1_IDX
)
PCTFREE 10
PCTUSED 80
INITRANS 2
TABLESPACE JSA_TS_1_DAT
/



COMMENT ON TABLE JSA_USERRIGHT IS 'definition of the user rights per modul'
/
COMMENT ON COLUMN JSA_USERRIGHT.USER_ID IS 'internal user-id (pk) of the user'
/
COMMENT ON COLUMN JSA_USERRIGHT.MODULE_ID IS 'internal modul-id (pk), incremented by 1 for each new row within each program-id'
/
COMMENT ON COLUMN JSA_USERRIGHT.CANINSERT IS 'insert allowed'
/
COMMENT ON COLUMN JSA_USERRIGHT.CANUPDATE IS 'update allowed'
/
COMMENT ON COLUMN JSA_USERRIGHT.CANDELETE IS 'delete allowed'
/
COMMENT ON COLUMN JSA_USERRIGHT.CANREAD IS 'Read allowed'
/
COMMENT ON COLUMN JSA_USERRIGHT.CANPRINT IS 'Print allowed'
/
COMMENT ON COLUMN JSA_USERRIGHT.ENTRYDATE IS 'ENTRYDATE'
/
COMMENT ON COLUMN JSA_USERRIGHT.ENTRYBY IS 'ENTRYBY'
/
COMMENT ON COLUMN JSA_USERRIGHT.MODIFDATE IS 'MODIFDATE'
/
COMMENT ON COLUMN JSA_USERRIGHT.MODIFBY IS 'MODIFBY'
/
COMMENT ON COLUMN JSA_USERRIGHT.MODIFIED IS 'MODIFIED'
/
COMMENT ON COLUMN JSA_USERRIGHT.RECVER IS 'RECVER'
/
grant select, insert, update, delete on JSA_USERRIGHT to ROLE_JSA_ALL
/
grant select on JSA_USERRIGHT to ROLE_JSA_SEL
/
-- 
-- INDEX: AK_JSA_MODULE_MODULENAME 
--

CREATE UNIQUE INDEX AK_JSA_MODULE_MODULENAME ON JSA_MODULE(MODULENAME)
TABLESPACE JSA_TS_1_IDX
STORAGE(INITIAL 10K
        NEXT 10K
        MINEXTENTS 1
        PCTINCREASE 0
        )
/
-- 
-- INDEX: AK_JSA_USER_LOGIN 
--

CREATE UNIQUE INDEX AK_JSA_USER_LOGIN ON JSA_USER(LOGIN)
TABLESPACE JSA_TS_1_IDX
STORAGE(INITIAL 10K
        NEXT 10K
        MINEXTENTS 1
        PCTINCREASE 0
        )
/
-- 
-- TABLE: JSA_CONFIG 
--

ALTER TABLE JSA_CONFIG ADD CONSTRAINT FK_JSA_USER_JSA_CONFIG 
    FOREIGN KEY (USER_ID)
    REFERENCES JSA_USER(USER_ID) ON DELETE CASCADE
/


-- 
-- TABLE: JSA_GROUPRIGHT 
--

ALTER TABLE JSA_GROUPRIGHT ADD CONSTRAINT FK_JSA_MODULE_JSA_GROUPRIGHT 
    FOREIGN KEY (MODULE_ID)
    REFERENCES JSA_MODULE(MODULE_ID) ON DELETE CASCADE
/

ALTER TABLE JSA_GROUPRIGHT ADD CONSTRAINT FK_JSA_USERGROUP_JSA_GROUPRIGH 
    FOREIGN KEY (USERGROUP_ID)
    REFERENCES JSA_USERGROUP(USERGROUP_ID) ON DELETE CASCADE
/


-- 
-- TABLE: JSA_GROUPUSER 
--

ALTER TABLE JSA_GROUPUSER ADD CONSTRAINT FK_JSA_USER_JSA_GROUPUSER 
    FOREIGN KEY (USER_ID)
    REFERENCES JSA_USER(USER_ID) ON DELETE CASCADE
/

ALTER TABLE JSA_GROUPUSER ADD CONSTRAINT FK_JSA_USERGROUP_JSA_GROUPUSER 
    FOREIGN KEY (USERGROUP_ID)
    REFERENCES JSA_USERGROUP(USERGROUP_ID) ON DELETE CASCADE
/


-- 
-- TABLE: JSA_USER 
--

ALTER TABLE JSA_USER ADD CONSTRAINT FK_JSA_USER_JSA_USER 
    FOREIGN KEY (LEADER_ID)
    REFERENCES JSA_USER(USER_ID)
/


-- 
-- TABLE: JSA_USERRIGHT 
--

ALTER TABLE JSA_USERRIGHT ADD CONSTRAINT FK_JSA_MODULE_JSA_USERRIGHT 
    FOREIGN KEY (MODULE_ID)
    REFERENCES JSA_MODULE(MODULE_ID) ON DELETE CASCADE
/

ALTER TABLE JSA_USERRIGHT ADD CONSTRAINT FK_JSA_USER_JSA_USERRIGHT 
    FOREIGN KEY (USER_ID)
    REFERENCES JSA_USER(USER_ID) ON DELETE CASCADE
/


