--------------------------------------------------------------------------------
--
--      Copyright (c) 2003 - 2007 Oracle. All rights reserved.
--
--      This material is the confidential property of Oracle Corporation
--      or its licensors and may be used, reproduced, stored or transmitted
--      only in accordance with a valid Oracle license or sublicense agreement.
--
--------------------------------------------------------------------------------
--
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100105, 100058, 5013, 53, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100106, 100058, 5016, 54, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100107, 100058, 5009, 55, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100108, 100059, 5000, 56, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100109, 100059, 5013, 57, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100110, 100059, 5016, 58, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100111, 100060, 5000, 59, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100112, 100060, 5013, 60, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100113, 100060, 5016, 61, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100114, 100060, 5010, 62, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100115, 100061, 5000, 63, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100116, 100061, 5013, 64, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100117, 100061, 5016, 65, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100118, 100061, 5010, 66, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100119, 100062, 5000, 67, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100120, 100062, 5013, 68, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100121, 100062, 5016, 69, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100122, 100062, 5010, 70, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100123, 100062, 5009, 71, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100125, 100063, 5013, 73, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100126, 100063, 5016, 74, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100127, 100063, 5009, 75, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100128, 100064, 5000, 76, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100129, 100064, 5013, 77, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100130, 100064, 5016, 78, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100131, 100064, 5009, 79, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100132, 100064, 5010, 80, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100133, 100065, 5000, 81, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100134, 100065, 5013, 82, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100135, 100065, 5016, 83, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100136, 100066, 5000, 84, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100138, 100066, 5016, 86, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100139, 100066, 5009, 87, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100140, 100066, 5010, 88, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100141, 100067, 5000, 89, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100142, 100067, 5013, 90, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100143, 100067, 5016, 91, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100146, 100068, 5016, 94, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100147, 100068, 5009, 95, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100148, 100068, 5010, 96, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100149, 100068, 5008, 97, 'EDR_STATUS_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100144, 100068, 5000, 92, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100096, 100055, 5000, 44, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100097, 100055, 5013, 45, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100098, 100056, 5000, 46, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100099, 100056, 5013, 47, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100100, 100056, 5016, 48, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100102, 100057, 5013, 50, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100103, 100057, 5016, 51, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100104, 100058, 5000, 52, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100145, 100068, 5013, 93, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100005, 100055, 5016, 98, 'SUSPENDED_FROM_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100006, 100056, 5008, 99, 'EDR_STATUS_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100007, 100057, 5009, 100, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100008, 100058, 5008, 101, 'EDR_STATUS_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100009, 100059, 5010, 102, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100010, 100060, 5008, 103, 'EDR_STATUS_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100011, 100061, 5009, 104, 'SERVICE_TYPE_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100012, 100062, 5008, 105, 'EDR_STATUS_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100013, 100063, 5010, 106, 'REVENUE_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100014, 100064, 5008, 107, 'EDR_STATUS_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100015, 100065, 5011, 108, 'OUTPUT_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100016, 100066, 5011, 109, 'OUTPUT_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100017, 100067, 5012, 110, 'SUSPENSE_REASON_COL', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100018, 100068, 5011, 111, 'OUTPUT_STREAM_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100124, 100063, 5000, 72, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100137, 100066, 5013, 85, 'ORIGINAL_BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100101, 100057, 5000, 49, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100101, 100057, 5000, 49, 'BATCH_ID_COL', NULL, 'S', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100150, 100055,5018, 112, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100151, 100056,5018, 113, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100152, 100057,5018, 114, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100153, 100058,5018, 115, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100154, 100059,5018, 116, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100155, 100060,5018, 117, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100156, 100061,5018, 118, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100157, 100062,5018, 119, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100158, 100063,5018, 120, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100159, 100064,5018, 121, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100160, 100065,5018, 122, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100161, 100066,5018, 123, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100162, 100067,5018, 124, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES (
100163, 100068,5018, 125, 'INTERN_PROCESS_STATUS', NULL, 'N', 'A', 100,  SYSDATE
, 1, 100,  SYSDATE, 0);
Commit;
 
