--------------------------------------------------------------------------------
--
--      Copyright (c) 2003 - 2006 Oracle. All rights reserved.
--
--      This material is the confidential property of Oracle Corporation
--      or its licensors and may be used, reproduced, stored or transmitted
--      only in accordance with a valid Oracle license or sublicense agreement.
--
--------------------------------------------------------------------------------
--
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100228, 100067, 5015, 185, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100229, 100067, 5007, 186, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100230, 100067, 5002, 187, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100138, 100055, 5001, 97, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100139, 100055, 5014, 98, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100140, 100055, 5006, 99, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100141, 100055, 5005, 100, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100142, 100055, 5015, 101, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100143, 100055, 5007, 102, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100144, 100055, 5002, 103, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100145, 100056, 5001, 104, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100146, 100056, 5014, 105, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100147, 100056, 5006, 106, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100148, 100056, 5005, 107, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100149, 100056, 5015, 108, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100150, 100056, 5007, 109, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100151, 100056, 5002, 110, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100152, 100057, 5001, 111, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100153, 100057, 5014, 112, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100154, 100057, 5006, 113, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100155, 100057, 5005, 114, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100156, 100057, 5015, 115, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100157, 100057, 5007, 116, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100158, 100057, 5002, 117, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100159, 100058, 5001, 118, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100160, 100058, 5014, 119, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100161, 100058, 5006, 120, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100162, 100058, 5005, 121, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100163, 100058, 5015, 122, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100164, 100058, 5007, 123, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100165, 100058, 5002, 124, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100166, 100059, 5001, 125, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100231, 100068, 5001, 188, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100232, 100068, 5014, 189, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100233, 100068, 5006, 190, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100234, 100068, 5005, 191, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100235, 100068, 5015, 192, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100236, 100068, 5007, 193, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100237, 100068, 5002, 194, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100000, 100055, 5003, 195, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100004, 100055, 5017, 198, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100002, 100055, 5004, 196, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100003, 100055, 5017, 197, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100005, 100056, 5003, 199, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100006, 100056, 5004, 200, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100007, 100056, 5017, 201, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100008, 100056, 5017, 202, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100009, 100057, 5003, 203, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100010, 100057, 5004, 204, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100011, 100057, 5017, 205, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100012, 100057, 5017, 206, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100013, 100058, 5003, 207, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100014, 100058, 5004, 208, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100195, 100063, 5014, 154, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100196, 100063, 5006, 155, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100197, 100063, 5005, 156, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100198, 100063, 5015, 157, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100199, 100063, 5007, 158, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100200, 100063, 5002, 159, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100201, 100064, 5001, 160, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100202, 100064, 5014, 161, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100203, 100064, 5006, 162, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100204, 100064, 5005, 163, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100205, 100064, 5015, 164, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100206, 100064, 5007, 165, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100207, 100064, 5002, 166, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100208, 100065, 5001, 167, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100209, 100065, 5014, 168, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100210, 100065, 5006, 169, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100212, 100065, 5015, 171, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100213, 100065, 5007, 172, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100214, 100065, 5002, 173, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100215, 100066, 5001, 174, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100217, 100066, 5006, 176, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100220, 100066, 5005, 177, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100221, 100066, 5015, 178, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100222, 100066, 5007, 179, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100224, 100067, 5001, 181, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100226, 100067, 5006, 183, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100227, 100067, 5005, 184, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100167, 100059, 5014, 126, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100168, 100059, 5006, 127, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100169, 100059, 5005, 128, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100170, 100059, 5015, 129, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100171, 100059, 5007, 130, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100172, 100059, 5002, 131, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100173, 100060, 5001, 132, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100174, 100060, 5014, 133, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100175, 100060, 5006, 134, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100176, 100060, 5005, 135, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100178, 100060, 5007, 137, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100179, 100060, 5002, 138, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100180, 100061, 5001, 139, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100181, 100061, 5014, 140, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100182, 100061, 5006, 141, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100183, 100061, 5005, 142, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100184, 100061, 5015, 143, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100185, 100061, 5007, 144, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100186, 100061, 5002, 145, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100187, 100062, 5001, 146, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100188, 100062, 5014, 147, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100189, 100062, 5006, 148, 'CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100190, 100062, 5005, 149, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100191, 100062, 5015, 150, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100192, 100062, 5007, 151, 'DISCOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100193, 100062, 5002, 152, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100015, 100058, 5017, 209, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100016, 100058, 5017, 210, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100017, 100059, 5003, 211, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100018, 100059, 5004, 212, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100019, 100059, 5017, 213, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100020, 100059, 5017, 214, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100021, 100061, 5003, 215, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100022, 100061, 5004, 216, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100023, 100061, 5017, 217, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100024, 100061, 5017, 218, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100025, 100062, 5003, 219, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100026, 100062, 5004, 220, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100027, 100062, 5017, 221, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100028, 100062, 5017, 222, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100029, 100063, 5003, 223, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100030, 100063, 5004, 224, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100031, 100063, 5017, 225, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100032, 100063, 5017, 226, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100033, 100064, 5003, 227, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100034, 100064, 5004, 228, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100035, 100064, 5017, 229, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100036, 100064, 5017, 230, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100037, 100065, 5003, 231, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100038, 100065, 5004, 232, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100039, 100065, 5017, 233, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100040, 100065, 5017, 234, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100211, 100065, 5005, 170, 'WHOLESALE_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100041, 100066, 5003, 235, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100042, 100066, 5004, 236, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100043, 100066, 5017, 237, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100044, 100066, 5017, 238, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100216, 100066, 5014, 175, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100223, 100066, 5002, 180, 'DURATION_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100045, 100067, 5003, 239, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100046, 100067, 5004, 240, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100047, 100067, 5017, 241, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100048, 100067, 5017, 242, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100225, 100067, 5014, 182, 'OLD_CHARGED_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100049, 100068, 5003, 243, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100050, 100068, 5004, 244, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100051, 100068, 5017, 245, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100052, 100068, 5017, 246, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100053, 100060, 5003, 247, 'VOL_SENT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100054, 100060, 5004, 248, 'VOL_REC_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100055, 100060, 5017, 249, 'EARLIEST_CALL_MADE', NULL, 'M', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100056, 100060, 5017, 250, 'LAST_CALL_MADE', NULL, 'X', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100177, 100060, 5015, 136, 'OLD_DISCOUNT_AMOUNT_COL', 2, 'S', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,
RECVER ) VALUES ( 
100194, 100063, 5001, 153, 'COUNT_COL', NULL, 'C', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
Commit;
 
