--------------------------------------------------------------------------------
--
--      Copyright (c) 2003 - 2006 Oracle. All rights reserved.
--
--      This material is the confidential property of Oracle Corporation
--      or its licensors and may be used, reproduced, stored or transmitted
--      only in accordance with a valid Oracle license or sublicense agreement.
--
--------------------------------------------------------------------------------
--
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100055, 'RA_01', 'Simple', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.', ';'
, 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100056, 'RA_02', 'Status', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.', ';'
, 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100057, 'RA_03', 'SvcType', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.', ';'
, 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100058, 'RA_04', 'SvcType_Status', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.'
, ';', 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100059, 'RA_05', 'RevStream', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.', ';'
, 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100060, 'RA_06', 'RevStream_Status', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.'
, '.', ';', 'A',  SYSDATE, 100
,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100061, 'RA_07', 'RevStream_SvcType', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.'
, '.', ';', 'A',  SYSDATE, 100
,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100062, 'RA_08', 'RevStream_SvcType_Status', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.'
, '.', '.', ';', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100063, 'RA_09', 'SvcType_RevStream', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.'
, '.', ';', 'A',  SYSDATE, 100
,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100064, 'RA_10', 'SvcType_RevStream_Status', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.'
, '.', '.', ';', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100065, 'RA_11', 'OutputStream', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.'
, ';', 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100066, 'RA_12', 'SvcType_RevStream_OutputStream', 'RA_SAMPLE', 'TAB_NAME', 0, 100000
, '.', '.', '.', ';', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100067, 'RA_13', 'SuspenseCode', 'RA_SAMPLE', 'TAB_NAME', 0, 100000, '.', '.', '.'
, ';', 'A',  SYSDATE, 100,  SYSDATE
, 100, 1, 0); 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100068, 'RA_14', 'SvcType_RevStream_Status_OutputStream', 'RA_SAMPLE', 'TAB_NAME'
, 0, 100000, '.', '.', '.', ';', 'A',  SYSDATE
, 100,  SYSDATE, 100, 1, 0); 
Commit;
 
