--------------------------------------------------------------------------------
--
--      Copyright (c) 2003 - 2007 Oracle. All rights reserved.
--
--      This material is the confidential property of Oracle Corporation
--      or its licensors and may be used, reproduced, stored or transmitted
--      only in accordance with a valid Oracle license or sublicense agreement.
--
--------------------------------------------------------------------------------
--
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5008, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.EDR_STATUS', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5009, 'RA_SAMPLE', 'DETAIL.INTERN_SERVICE_CODE', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5010, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.REVENUE_STREAM', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5011, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.OUTPUT_STREAM', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5012, 'RA_SAMPLE', 'DETAIL.ASS_SUSPENSE_EXT.SUSPENSE_REASON', 'Integer', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5013, 'RA_SAMPLE', 'DETAIL.ORIGINAL_BATCH_ID', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5000, 'RA_SAMPLE', 'DETAIL.BATCH_ID', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5014, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.OLD_CHARGED_AMOUNT', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5015, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.OLD_DISCOUNT_AMOUNT', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5016, 'RA_SAMPLE', 'DETAIL.ASS_SUSPENSE_EXT.SUSPENDED_FROM_BATCH_ID', 'String', NULL
, 0,  SYSDATE, NULL,  SYSDATE
, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5017, 'RA_SAMPLE', 'DETAIL.CHARGING_START_TIMESTAMP', 'Date', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5001, 'RA_SAMPLE', 'DETAIL.EVENT_ID', 'String', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5002, 'RA_SAMPLE', 'DETAIL.DURATION', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5003, 'RA_SAMPLE', 'DETAIL.VOLUME_SENT', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5004, 'RA_SAMPLE', 'DETAIL.VOLUME_RECEIVED', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5005, 'RA_SAMPLE', 'DETAIL.WHOLESALE_CHARGED_AMOUNT_VALUE', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5006, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.CHARGED_AMOUNT', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
5007, 'RA_SAMPLE', 'DETAIL.ASS_ARA_EXT.DISCOUNT_AMOUNT', 'Decimal', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES (
5018, 'RA_SAMPLE', 'DETAIL.INTERN_PROCESS_STATUS', 'Integer', NULL, 0,  SYSDATE
, NULL,  SYSDATE, 1, 0);
Commit;
 
