--------------------------------------------------------------------------------
--
--      Copyright (c) 2005 - 2006 Oracle. All rights reserved.
--
--      This material is the confidential property of Oracle Corporation
--      or its licensors and may be used, reproduced, stored or transmitted
--      only in accordance with a valid Oracle license or sublicense agreement.
--
--------------------------------------------------------------------------------

-- IFW_EDRC_DESC --
INSERT INTO IFW_EDRC_DESC ( EDRC_DESC, NAME, ENTRYBY, ENTRYDATE, 
	   MODIFIED, MODIFBY, MODIFDATE,RECVER ) 
VALUES ('SMScontainerDesc', 'SMS report container description', 100,  sysdate
	   , 1, 100,  sysdate, 6); 

-- IFW_EDRC_FIELD -- 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
15008, 'SMScontainerDesc', 'DETAIL.RECORD_TYPE', 'String', NULL, 0,  sysdate
, NULL,  sysdate, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
15009, 'SMScontainerDesc', 'DETAIL.CHARGING_START_TIMESTAMP', 'Date', NULL, 0,  sysdate
, NULL,  sysdate, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
15010, 'SMScontainerDesc', 'DETAIL.ASS_SMS_EXT.ORIGINATING_SWITCH_IDENTIFICATION', 'String', NULL, 0,  sysdate
, NULL,  sysdate, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
15011, 'SMScontainerDesc', 'DETAIL.ASS_SMS_EXT.DESTINATION_SWITCH_IDENTIFICATION', 'String', NULL, 0,  sysdate
, NULL,  sysdate, 1, 0); 
INSERT INTO IFW_EDRC_FIELD ( FIELD_ID, EDRC_DESC, FIELD_NAME, TYPE, DESCRIPTION, ENTRYBY, ENTRYDATE,
MODIFBY, MODIFDATE, MODIFIED, RECVER ) VALUES ( 
15012, 'SMScontainerDesc', 'DETAIL.ASS_SMS_EXT.PROVIDER_ID', 'String', NULL, 0,  sysdate
, NULL,  sysdate, 1, 0); 


-- IFW_SCENARIO -- 
INSERT INTO IFW_SCENARIO ( SCENARIO_ID, CODE, NAME, EDRC_DESC, DEFAULT_TAB_NAME, DEFAULT_FLUSHMODE,
DEFAULT_THRESHOLD, DEFAULT_TEMP_DIR, DEFAULT_DONE_DIR, DEFAULT_CTL_DIR, DEFAULT_FLD_DELIM, STATUS,
ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER ) VALUES ( 
100070, 'SMS_SCE_01', 'SMS_SCENARIO', 'SMScontainerDesc', 'TAB_SMS_RPT', 0, 10000, '.', '.' , '.', ';', 'A', 
 sysdate, 100 ,  sysdate, 100, 1, 3); 

-- IFW_GROUPING --
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100260, 100070, 15008, 1, 'RECORD_TYPE', NULL, 'S', 'A', 100,  sysdate , 1, NULL, NULL, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100262, 100070, 15010, 1, 'ORIGIN_SWITCH_ID', NULL, 'S', 'A', 100,  sysdate , 1, NULL, NULL, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100263, 100070, 15011, 1, 'DEST_SWITCH_ID', NULL, 'S', 'A', 100,  sysdate , 1, NULL, NULL, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100264, 100070, 15012, 1, 'SMSC', NULL, 'S', 'A', 100,  sysdate , 1, NULL, NULL, 0); 
INSERT INTO IFW_GROUPING ( GROUPING_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, COL_FORMAT, DATATYPE,
STATUS, ENTRYBY, ENTRYDATE, MODIFIED, MODIFBY, MODIFDATE, RECVER ) VALUES ( 
100261, 100070, 15009, 1, 'CHARGING_START_TIMESTAMP', 'YYYYMMDD', 'S', 'A', 100,  sysdate ,1, NULL, NULL, 0); 


-- IFW_AGGREGATION --
INSERT INTO IFW_AGGREGATION ( AGGREGATION_ID, SCENARIO_ID, FIELD_ID, RANK, COL_NAME, PRECISIONDIGITS,
	   FUNC, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED,RECVER )
VALUES (190046, 100070, 15008, 5, 'EDR_COUNT', NULL, 
	   'C', 'A',  sysdate, 100, NULL, NULL, 1, 0);
	   
-- IFW_CONDITION -- 
INSERT INTO IFW_CONDITION (CONDITION_ID, SCENARIO_ID, FIELD_ID, VALUE, DATATYPE, STATUS, ENTRYDATE, ENTRYBY, MODIFDATE, MODIFBY, MODIFIED, RECVER)
	   VALUES( 22000, 100070, 15008, '025', 'S', 'A', sysdate, 100, NULL, NULL, 1,0);
	   
commit;
