#ifndef __RWDB_DELETER_H__
#define __RWDB_DELETER_H__

/**************************************************************************
 *
 * $Id: //spro/rel2016.1/rw/db/deleter.h#1 $
 *
 * Copyright (c) 1994-2016 Rogue Wave Software, Inc.  All Rights Reserved.
 * 
 * This computer software is owned by Rogue Wave Software, Inc. and is
 * protected by U.S. copyright laws and other laws and by international
 * treaties.  This computer software is furnished by Rogue Wave Software, Inc.
 * pursuant to a written license agreement and may be used, copied, transmitted,
 * and stored only in accordance with the terms of such license agreement and
 * with the inclusion of the above copyright notice.  This computer software or
 * any other copies thereof may not be provided or otherwise made available to
 * any other person.
 * 
 * U.S. Government Restricted Rights.  This computer software: (a) was
 * developed at private expense and is in all respects the proprietary
 * information of Rogue Wave Software, Inc.; (b) was not developed with
 * government funds; (c) is a trade secret of Rogue Wave Software, Inc. for all
 * purposes of the Freedom of Information Act; and (d) is a commercial item and
 * thus, pursuant to Section 12.212 of the Federal Acquisition Regulations (FAR)
 * and DFAR Supplement Section 227.7202, Government's use, duplication or
 * disclosure of the computer software is subject to the restrictions set forth
 * by Rogue Wave Software, Inc.
 *
 **************************************************************************/

#include <rw/db/dbase.h>
#include <rw/db/defs.h>
#include <rw/db/status.h>
#include <rw/db/table.h>

/**
 * \ingroup db_data_manipulation_group
 *
 * \brief
 * Encapsulates an SQL \c DELETE statement.
 *
 * RWDBDeleter is an encapsulation of an SQL \c DELETE statement. The
 * where() method of RWDBDeleter is used to specify a \c WHERE clause. The
 * \c WHERE clause is encapsulated by an RWDBCriterion, which is some number
 * of RWDBExpr instances combined with logical operators.
 *
 * A \c DELETE statement does not normally produce results. However, the DB
 * Interface Module recognizes that some database vendors provide triggers,
 * which can cause results to be generated by a \c DELETE statement.
 * Consequently, the execute() method of RWDBDeleter returns an RWDBResult,
 * which is a sequence of zero or more RWDBTable objects. Applications are
 * not obliged to request any tables from the returned object.
 *
 * RWDBDeleter is designed around the Interface/Implementation paradigm. An
 * RWDBDeleter instance is an interface to a reference-counted
 * implementation; copy constructors and assignment operators produce
 * additional references to a shared implementation. An RWDBDeleter
 * implementation is a base class from which a family of database-specific
 * deleter implementations is derived.
 *
 * \synopsis
 * #include <rw/db/deleter.h>
 *
 * RWDBDeleter deleter = myTable.deleter();
 * \endsynopsis
 *
 * \sa
 * \parblock
 * The encapsulated \c WHERE clause of an RWDBDeleter is an RWDBCriterion,
 * which is composed of RWDBExpr instances. See RWDBCriterion, RWDBExpr, and
 * RWDBColumn for details.
 *
 * The result of execute() is an RWDBResult, which represents a sequence of
 * zero or more RWDBTable instances. See RWDBResult and RWDBTable for
 * details.
 * \endparblock
 *
 * \example
 * <b>Example 1</b>
 *
 * For this example, we delete all the \c red hubcaps from the \c autoParts
 * table:
 *
 * \code
 * RWDBTable autoParts = myDbase.table("autoParts");
 * RWDBDeleter deleter = autoParts.deleter();
 * deleter.where(autoParts["name"] == "hubcap" &&
 *               autoParts["color"] == "red");
 * deleter.execute();
 * \endcode
 *
 * <b>Example 2</b>
 *
 * For this example, we delete all parts with a specific \c id by repeatedly
 * using binding to a variable containing the \c id:
 *
 * \code
 * RWDBTable allParts = myDbase.table( "AllParts" );
 * RWDBConnection connection = myDbase.connection();
 * RWDBDeleter deleter = allParts.deleter();
 * int id = 1001;
 * deleter.where( allParts["id"] == RWDBBoundExpr( &id ) );
 * deleter.execute(connection); // delete part number
 *                              // 1001
 * id = 2001;
 * deleter.execute(connection); // delete part number 2001
 * \endcode
 * \endexample
 */
class RWDB_GLOBAL RWDBDeleter
{
public:

    /**
     * The default constructor creates an RWDBDeleter whose status is
     * RWDBStatus::notInitialized. This constructor is provided as a
     * convenience, for example, to declare an array of RWDBDeleter objects.
     * A usable RWDBDeleter is obtained from an RWDBTable.
     */
    RWDBDeleter();

    /**
     * Copy constructor. Self shares an implementation with \a deleter.
     */
    RWDBDeleter(const RWDBDeleter& deleter);

    RWDBDeleter(RWDBDeleterImp* imp);

    /**
     * Assignment operator. Self shares an implementation with \a deleter.
     */
    RWDBDeleter&    operator=(const RWDBDeleter& deleter);

    virtual ~RWDBDeleter();

    // access functions
    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * DELETE FROM table [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with an implicit RWDBConnection object. An implicit
     * RWDBConnection object inherits the time zone setting from the
     * producer RWDBDatabase instance. Hence, the time zone setting of the
     * producer RWDBDatabase object will be used for creating the string
     * representations of any RWDateTime instances in self.
     *
     * The behavior of this method depends upon the
     * RWDBDatabase::verboseAsString() setting in the producer RWDBDatabase
     * instance.
     *
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c false, the SQL returned is the same as that passed to the database
     * for execution. This is the default.
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c true, any placeholders in the returned SQL are replaced with their
     * bound values.
     *
     * \note
     * When the RWDBDatabase::verboseAsString() option is set to \c true,
     * the SQL returned by this method may not be a valid SQL statement.
     * However, this method's return value is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with
     * RWDBDatabase::verboseAsString() set to \c true will result in a
     * string with blob data returned as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBDatabase::timeZone(const RWZone*) for time zone setting on
     * RWDBDatabase.
     */
    inline RWCString asString() const
    {
        return rwAsString(table().database().timeZone(),
                          table().database().verboseAsString());
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * DELETE FROM table [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with \a conn. The time zone setting of \a conn will be
     * used for creating string representations of any RWDateTime instances
     * in self.
     *
     * The behavior of this asString() method depends upon the
     * RWDBDatabase::verboseAsString() setting in the producer RWDBDatabase
     * instance.
     *
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c false,the SQL returned is the same as that passed to the database
     * for execution. This is the default.
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c true, any placeholders in the returned SQL are replaced with their
     * bound values.
     *
     * \note
     * When the RWDBDatabase::verboseAsString() option is set to \c true,
     * the SQL returned by this method may not be a valid SQL statement.
     * However, this method's return value is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with
     * RWDBDatabase::verboseAsString() set to \c true will result in a
     * string with blob data returned as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBConnection::timeZone(const RWZone*) for time zone setting on
     * RWDBConnection.
     */
    inline RWCString asString(const RWDBConnection& conn) const
    {
        return rwAsString(conn.timeZone(),
                          table().database().verboseAsString());
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * DELETE FROM table [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with an implicit RWDBConnection object. An implicit
     * RWDBConnection object inherits the time zone setting from the
     * producer RWDBDatabase instance. Hence, the time zone setting of the
     * producer RWDBDatabase object will be used for creating the string
     * representations of any RWDateTime instances in self.
     *
     * The behavior of this method depends on the value of \a verbose, and
     * is independent of the RWDBDatabase::verboseAsString() setting.
     *
     * - If \a verbose is \c false, the SQL returned is the same as that
     * passed to the database for execution.
     * - If \a verbose is \c true, any placeholders in the returned SQL are
     * replaced with their bound values although the SQL passed to the
     * database for execution will not be affected.
     *
     * \note
     * The SQL returned by this method when \a verbose is \c true may not be
     * a valid SQL statement. However, this is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with \a verbose as
     * \c true will result in a string with blob data returned as hex
     * numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBDatabase::timeZone(const RWZone*) for time zone setting on
     * RWDBDatabase.
     */
    inline RWCString asString(bool verbose) const
    {
        return rwAsString(table().database().timeZone(), verbose);
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * DELETE FROM table [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with \a conn. The time zone setting of \a conn will be
     * used for creating string representations of any RWDateTime instances
     * in self.
     *
     * The behavior of this method depends on the value of \a verbose, and
     * is independent of the RWDBDatabase::verboseAsString() setting.
     *
     * - If \a verbose is \c false, the SQL returned is the same as that
     * passed to the database for execution.
     * - If \a verbose is \c true, any placeholders in the returned SQL are
     * replaced with their bound values although the SQL passed to the
     * database for execution will not be affected.
     *
     * \note
     * The SQL returned by this method when \a verbose is \c true may not be
     * a valid SQL statement. However, this is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with \a verbose as
     * \c true will result in a string with blob data returned as hex
     * numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBConnection::timeZone(const RWZone*) for time zone setting on
     * RWDBConnection.
     */
    inline RWCString asString(const RWDBConnection& conn,
                              bool verbose) const
    {
        return rwAsString(conn.timeZone(), verbose);
    }

    RWCString       rwAsString(const RWZone& timeZone,
                               bool verbose = false) const;

    /**
     * Returns the RWDBTable that produced self. Returns an RWDBTable whose
     * status is RWDBStatus::notInitialized if self was produced with the
     * default constructor.
     */
    RWDBTable       table() const;

    /**
     * Installs \a handler as self's error handler. The supplied \a handler
     * is inherited by all objects produced by self. By default, the
     * RWDBStatus::ErrorHandler is inherited from the object that produced
     * self; this method overrides the default.
     */
    void                    setErrorHandler(RWDBStatus::ErrorHandler handler);

    /**
     * Returns the error handler attached to self.
     */
    RWDBStatus::ErrorHandler errorHandler() const;

    /**
     * Returns the current status of self.
     */
    RWDBStatus              status() const;

    /**
     * Returns \c true if self's status is RWDBStatus::ok, otherwise returns
     * \c false. Does not return \c false if the previously executed
     * statement failed. You must check the status of the RWDBResult
     * returned from execute() instead of the status of the RWDBDeleter
     * object.
     */
    bool                isValid() const;

    /**
     * Returns \c true if the object is in ready state, indicating that
     * accessing the object will not block. Accessing a nonready object may
     * potentially block.
     */
    bool                isReady() const;

    // multithreading support

    /**
     * Attempts to acquire the internal mutex lock. If the mutex is already
     * locked by another thread, the function blocks until the mutex is
     * released. This function can be called from a \c const object.
     *
     * \note
     * In single-threaded builds, this function evaluates to a no-op.
     */
    void            acquire(void) const;

    /**
     * Releases a previously acquired mutex. This function can be called
     * from a \c const object.
     *
     * \note
     * In single-threaded builds, this function evaluates to a no-op.
     */
    void            release(void) const;

    /**
     * Specifies \a criterion as self's SQL \c WHERE clause. If self already
     * has a \c WHERE clause, this method replaces it. Specifying an empty
     * \a criterion clears self's \c WHERE clause. Notice that a deleter
     * without a \c WHERE clause deletes all rows from its table. Returns a
     * reference to self.
     */
    RWDBDeleter&    where(const RWDBCriterion& criterion);

    /**
     * Uses a default database connection to cause the SQL statement
     * encapsulated by self to be executed.
     */
    RWDBResult      execute();

    /**
     * Uses the supplied \a connection to cause the SQL statement
     * encapsulated by self to be executed. This function can behave
     * asynchronously if executed using an asynchronous connection.
     */
    RWDBResult      execute(const RWDBConnection& connection);

    /**
     * Clears self's \c WHERE clause and internal controls.
     */
    RWDBStatus      clear();

    /**
     * Returns a copy of self's RWDBCriterion, an encapsulated SQL \c WHERE
     * clause. Returns an empty RWDBCriterion if self has no \c WHERE
     * clause.
     */
    RWDBCriterion   where() const;

private:
    RWDBCountedRef<RWDBDeleterImp>  impl_;
};
#endif
