#ifndef __RWDB_INSERTER_H__
#define __RWDB_INSERTER_H__

/**************************************************************************
 *
 * $Id: //spro/rel2016.1/rw/db/inserter.h#1 $
 *
 * Copyright (c) 1994-2016 Rogue Wave Software, Inc.  All Rights Reserved.
 * 
 * This computer software is owned by Rogue Wave Software, Inc. and is
 * protected by U.S. copyright laws and other laws and by international
 * treaties.  This computer software is furnished by Rogue Wave Software, Inc.
 * pursuant to a written license agreement and may be used, copied, transmitted,
 * and stored only in accordance with the terms of such license agreement and
 * with the inclusion of the above copyright notice.  This computer software or
 * any other copies thereof may not be provided or otherwise made available to
 * any other person.
 * 
 * U.S. Government Restricted Rights.  This computer software: (a) was
 * developed at private expense and is in all respects the proprietary
 * information of Rogue Wave Software, Inc.; (b) was not developed with
 * government funds; (c) is a trade secret of Rogue Wave Software, Inc. for all
 * purposes of the Freedom of Information Act; and (d) is a commercial item and
 * thus, pursuant to Section 12.212 of the Federal Acquisition Regulations (FAR)
 * and DFAR Supplement Section 227.7202, Government's use, duplication or
 * disclosure of the computer software is subject to the restrictions set forth
 * by Rogue Wave Software, Inc.
 *
 **************************************************************************
 *
 * Definition of class RWDBInserter
 *
 * This class provides a standard interface to the database-specific
 * implementation of "inserter", i.e. an object used to insert data
 * into a database table.
 *
 **************************************************************************/

#include <rw/db/dbase.h>
#include <rw/db/defs.h>
#include <rw/db/expr.h>
#include <rw/db/status.h>
#include <rw/db/table.h>
#include <rw/tools/bustring.h>

/**
 * \ingroup db_data_manipulation_group
 *
 * \brief
 * Encapsulates an SQL \c INSERT statement.
 *
 * RWDBInserter is an encapsulation of the SQL \c INSERT statement. In SQL,
 * the \c INSERT statement may be based either on a \c VALUES clause or on a
 * \c SELECT statement. RWDBInserter supports either variant. Use the
 * insertion operator operator<<() to add items to an RWDBInserter
 * encapsulated \c VALUES clause, or supply an RWDBSelector when the
 * RWDBInserter is produced. It is an error to use the insertion operator
 * operator<<() with an RWDBInserter that was produced with an RWDBSelector.
 *
 * An RWDBInserter can be produced with an optional RWDBSchema, which is
 * used to generate a list of column names. If the list of column names is
 * given, the values are inserted one for one into the specified columns.
 * Otherwise the values are inserted into the table columns in the order
 * they were created.
 *
 * RWDBInserter instances that use the indexing operator,
 * \ref operator[](const RWCString&) "operator[]", with \c colName derive a
 * list of column names if all columns are provided. This allows values to
 * be shifted into the inserter in any order without requiring a schema and
 * an additional database access.
 *
 * RWDBInserter has a notion of the current position in itself. This
 * position is set to zero when the RWDBInserter is produced, and reset to
 * zero whenever execute() is called. Each insertion operation adds a value
 * at the current position and increments the position by one. If the
 * RWDBInserter was created with an optional RWDBSchema, then the indexing
 * operators operator[]() can set the position to a specified column or
 * column name, and return a reference to self. The DB Interface Module does
 * not check whether the inserted values match the table's schema in type or
 * in number; such errors are reported by the database when execute() is
 * invoked.
 *
 * An \c INSERT statement does not normally produce results. However, the DB
 * Interface Module recognizes that some database vendors provide triggers,
 * which can cause results to be generated by an \c INSERT statement.
 * Consequently, the RWDBInserter execute() method returns an RWDBResult,
 * which is a sequence of zero or more RWDBTable instances. Applications are
 * not obliged to request any tables from the returned object.
 *
 * RWDBInserter is designed around the Interface/Implementation paradigm. An
 * RWDBInserter instance is an interface to a reference-counted
 * implementation; copy constructors and assignment operators produce
 * additional references to a shared implementation. An RWDBInserter
 * implementation is a base class from which a family of database-specific
 * inserter implementations is derived.
 *
 * \synopsis
 * #include <rw/db/inserter.h>
 *
 * RWDBInserter inserter = myTable.inserter();
 * RWDBInserter inserter = myTable.inserter(mySelector);
 * \endsynopsis
 *
 * \example
 * <b>Example 1</b>
 *
 * For this example, assume an \c AutoParts table in the database, with text
 * column \c name and integer column \c id. Here is a way to populate it
 * with data selected from another table, \c AllParts, which is also assumed
 * to have a \c name and an \c id column.
 *
 * \code
 * RWDBTable allParts = myDbase.table("AllParts");
 * RWDBConnection connection = myDbase.connection();
 * RWDBSelector select = myDbase.selector();
 * select << allParts["name"] << allParts["id"];
 * select.where(allParts["type"] == "Auto");
 * RWDBTable autoParts = myDbase.table("AutoParts");
 * RWDBInserter inserter = autoParts.inserter(select);
 * inserter.execute(connection);
 * \endcode
 *
 * <b>Example 2</b>
 *
 * This is how to insert a single row, using an encapsulated \c VALUES
 * clause:
 *
 * \code
 * RWDBInserter inserter = autoParts.inserter();
 * inserter << "steering wheel" << 1001;
 * inserter.execute(connection);
 * \endcode
 *
 * <b>Example 3</b>
 *
 * This is how to insert a single row, using a column list and an
 * encapsulated \c VALUES clause. The correct order of insertions depends on
 * the supplied RWDBSchema, not on the order of columns in the \c autoParts
 * table:
 *
 * \code
 * RWDBSchema schema;
 * schema.appendColumn("id");
 * schema.appendColumn("name");
 * RWDBInserter inserter = autoParts.inserter(schema);
 * inserter << 1001;               // associate with schema's 0
 *                                 // with column "id"
 * inserter << "steering wheel";   // associate with schema's 0
 *                                 // with column "name"
 * inserter.execute(connection);
 * \endcode
 *
 * <b>Example 4</b>
 *
 * This is how to insert a single row, using a column list, but supplying
 * bindings to application variables. The advantage here is that the same
 * insertion can be made several times without reshifting variables:
 *
 * \code
 * RWDBSchema schema;
 * schema.appendColumn("id");
 * schema.appendColumn("name");
 * RWDBInserter inserter = autoParts.inserter(schema);
 * int id = 1001;
 * RWCString name = "steering wheel";
 * inserter << RWDBBoundExpr( &id );
 * inserter << RWDBBoundExpr( &name );
 * inserter.execute();
 * id = 2001;
 * name = "gear shift";
 * inserter.execute(connection);
 * \endcode
 * \endexample
 *
 * \sa
 * \parblock
 * #RWDBValueManip \ref RWDBValue::rwdbNull "rwdbNull";
 *
 * \ref RWDBValue::rwdbNull "rwdbNull" is used to represent a literal
 * \c NULL value. A \c NULL value can be inserted through an RWDBInserter by
 * inserting \ref RWDBValue::rwdbNull "rwdbNull" into the inserter like
 * this:
 *
 * \code
 * inserter << rwdbNull;
 * \endcode
 *
 * The result of RWDBInserter::execute() is an RWDBResult, which represents
 * a sequence of zero or more RWDBTable instances. For details, see
 * RWDBResult and RWDBTable.
 * \endparblock
 */
class RWDB_SYMBOLIC RWDBInserter
{
public:

    /**
     * The default constructor creates an RWDBInserter whose status is
     * RWDBStatus::notInitialized. This constructor is provided as a
     * convenience, for example, to declare an array of RWDBInserter
     * instances. A usable RWDBInserter is obtained from an RWDBDatabase and
     * RWDBTable.
     */
    RWDBInserter();

    /**
     * Copy constructor. Self shares an implementation with \a ins.
     */
    RWDBInserter(const RWDBInserter& ins);

    RWDBInserter(RWDBInserterImp* impl);

    /**
     * Assignment operator. Self shares an implementation with \a ins.
     */
    RWDBInserter&       operator=(const RWDBInserter& ins);

    ~RWDBInserter();

    // accessors
    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * INSERT INTO table ... VALUES ( ... )
     * \endcode
     *
     * or:
     *
     * \code
     * INSERT  INTO  table  ...  SELECT  ...
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with an implicit RWDBConnection object. An implicit
     * RWDBConnection object inherits the time zone setting from the
     * producer RWDBDatabase instance. Hence, the time zone setting of the
     * producer RWDBDatabase object will be used for creating the string
     * representations of any RWDateTime instances in self.
     *
     * The behavior of this method depends upon the
     * RWDBDatabase::verboseAsString() setting in the producer RWDBDatabase
     * instance.
     *
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c false, the SQL returned is the same as that passed to the database
     * for execution. This is the default.
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c true, any placeholders in the returned SQL are replaced with their
     * bound values.
     *
     * \note
     * When the RWDBDatabase::verboseAsString() option is set to \c true,
     * the SQL returned by this method may not be a valid SQL statement.
     * However, this method's return value is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with
     * RWDBDatabase::verboseAsString() set to \c true will result in a
     * string with blob data returned as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBDatabase::timeZone(const RWZone*) for time zone setting on
     * RWDBDatabase.
     */
    inline RWCString asString() const
    {
        return rwAsString(table().database().timeZone(),
                          table().database().verboseAsString());
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * INSERT INTO table ... VALUES ( ... )
     * \endcode
     *
     * or:
     *
     * \code
     * INSERT  INTO  table  ...  SELECT  ...
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with \a conn. The time zone setting of \a conn will be
     * used for creating string representations of any RWDateTime instances
     * in self.
     *
     * The behavior of this method depends upon the
     * RWDBDatabase::verboseAsString() setting in the producer RWDBDatabase
     * instance.
     *
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c false, the SQL returned is the same as that passed to the database
     * for execution. This is the default.
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c true, any placeholders in the returned SQL are replaced with their
     * bound values.
     *
     * \note
     * When the RWDBDatabase::verboseAsString() option is set to \c true,
     * the SQL returned by this method may not be a valid SQL statement.
     * However, this method's return value is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with
     * RWDBDatabase::verboseAsString() set to \c true will result in a
     * string with blob data returned as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBConnection::timeZone(const RWZone*) for time zone setting on
     * RWDBConnection.
     */
    inline RWCString asString(const RWDBConnection& conn) const
    {
        return rwAsString(conn.timeZone(),
                          table().database().verboseAsString());
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * INSERT INTO table ... VALUES ( ... )
     * \endcode
     *
     * or:
     *
     * \code
     * INSERT INTO table ... SELECT ...
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with an implicit RWDBConnection object. An implicit
     * RWDBConnection object inherits the time zone setting from the
     * producer RWDBDatabase instance. Hence, the time zone setting of the
     * producer RWDBDatabase object will be used for creating the string
     * representations of any RWDateTime instances in self.
     *
     * The behavior of this method depends on the value of \a verbose, and
     * is independent of the RWDBDatabase::verboseAsString() setting.
     *
     * - If \a verbose is \c false, the SQL returned is the same as that
     * passed to the database for execution.
     * - If \a verbose is \c true, any placeholders in the returned SQL are
     * replaced with their bound values although the SQL passed to the
     * database for execution will not be affected.
     *
     * \note
     * The SQL returned by this method when \a verbose is \c true may not be
     * a valid SQL statement. However, this method's return value is not
     * necessarily the same SQL that is sent to the database for execution.
     * For example, if an RWDBBlob object is bound, calling this method with
     * \a verbose as \c true will result in a string with blob data returned
     * as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBDatabase::timeZone(const RWZone*) for time zone setting on
     * RWDBDatabase.
     */
    inline RWCString asString(bool verbose) const
    {
        return rwAsString(table().database().timeZone(), verbose);
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * INSERT INTO table ... VALUES ( ... )
     * \endcode
     *
     * or:
     *
     * \code
     * INSERT INTO table ... SELECT ...
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with \a conn. The time zone setting of \a conn will be
     * used for creating string representations of any RWDateTime instances
     * in self.
     *
     * The behavior of this method depends on the value of \a verbose, and
     * is independent of the RWDBDatabase::verboseAsString() setting.
     *
     * - If \a verbose is \c false, the SQL returned is the same as that
     * passed to the database for execution.
     * - If \a verbose is \c true, any placeholders in the returned SQL are
     * replaced with their bound values although the SQL passed to the
     * database for execution will not be affected.
     *
     * \note
     * The SQL returned by this method when \a verbose is \c true may not be
     * a valid SQL statement. However, this method's return value is not
     * necessarily the same SQL that is sent to the database for execution.
     * For example, if an RWDBBlob object is bound, calling this method with
     * \a verbose as \c true will result in a string with blob data returned
     * as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBConnection::timeZone(const RWZone*) for time zone setting on
     * RWDBConnection.
     */
    inline RWCString asString(const RWDBConnection& conn,
                              bool verbose) const
    {
        return rwAsString(conn.timeZone(), verbose);
    }

    /**
     * Returns the RWDBTable that produced self. Returns an RWDBTable whose
     * status is RWDBStatus::notInitialized if self was created with the
     * default constructor.
     */
    RWDBTable           table() const;

    // internal asString method
    RWCString           rwAsString(const RWZone& timeZone,
                                   bool verbose = false) const;

    // error handling functions

    /**
     * Installs \a handler as self's error handler. The supplied \a handler
     * is inherited by all objects produced by self. By default, an
     * RWDBStatus::ErrorHandler is inherited from the object that produced
     * self; this method overrides the default.
     */
    void                     setErrorHandler(RWDBStatus::ErrorHandler handler);

    /**
     * Returns the error handler attached to self.
     */
    RWDBStatus::ErrorHandler errorHandler() const;

    /**
     * Returns the current status of self.
     */
    RWDBStatus               status() const;

    /**
     * Returns \c true if self's status is RWDBStatus::ok, otherwise returns
     * \c false. Does not return \c false if the previous executed statement
     * failed. You must check the status of the RWDBResult returned from
     * execute() instead of the status of the RWDBInserter object.
     */
    bool                isValid() const;

    /**
     * This function returns \c true if the object is in ready state,
     * indicating that accessing the object will not block. Accessing a
     * nonready object may potentially block.
     */
    bool                isReady() const;

    // multithreading support

    /**
     * Attempts to acquire the internal mutex lock. If the mutex is already
     * locked by another thread, the function blocks until the mutex is
     * released. This function can be called from a \c const object.
     *
     * \note
     * In single-threaded builds, this function evaluates to a no-op.
     */
    void                acquire(void) const;

    /**
     * Releases a previously acquired mutex. This function can be called
     * from a \c const object.
     *
     * \note
     * In single-threaded builds, this function evaluates to a no-op.
     */
    void                release(void) const;

    // execution

    /**
     * Uses a default database connection to cause the SQL statement
     * encapsulated by self to be executed.
     */
    RWDBResult          execute();

    /**
     * Uses the supplied \a connection to cause the SQL statement
     * encapsulated by self to be executed. This function can behave
     * asynchronously if executed using an asynchronous connection.
     */
    RWDBResult          execute(const RWDBConnection& connection);

    /**
     * Sends all cached data, if any, to the server. Depending on the size
     * of the \c cache parameter used to create the inserter, can work one
     * of two ways:
     *
     * - When the \c cache parameter is less than or equal to 1, sends
     * cached data to the server immediately on invocation of execute().
     * Ignores any direct invocations of flush(), like a no-op.
     * - When the \c cache parameter is greater than 1, sends cached data to
     * the server, and is called automatically when the cache is full.
     *
     * When the connection between executions changes, flush() is called
     * before executing on the new connection. However, new data since the
     * last execute on the old connection is saved for the new execute on
     * the new connection.
     */
    RWDBResult          flush();

    /**
     * Clears self's list of scalar values and all internal controls.
     */
    RWDBStatus          clear();

    // indexing

    /**
     * Sets self's current position to the index associated with the column
     * in the column list whose name matches \a colName. If there is no such
     * column, \a colName is appended to the column list and the current
     * position is set to the index of that new entry. The next insertion
     * into self will associate the inserted value with the current
     * position. Returns a reference to self.
     */
    RWDBInserter&       operator[](const RWCString& colName);

    /**
     * Sets self's current position to the index associated with the column
     * in the column list whose name matches
     * \a column.\ref RWDBColumn::name() "name()". If there is no such
     * column, \a column.\ref RWDBColumn::name() "name()" is appended to the
     * column list and the current position is set to the index of that new
     * entry. The next insertion into self will associate the inserted value
     * with the current position. Returns a reference to self.
     */
    RWDBInserter&       operator[](const RWDBColumn& column);

    // adding values to insert

    /**
     * Adds \a value to self's encapsulated \c VALUES clause. If self was
     * produced with an RWDBSelector, sets self's status to
     * RWDBStatus::invalidUsage. Equivalent to inserting \a value into self.
     * Returns reference to self.
     */
    RWDBInserter&       addValue(const RWDBExpr& value);

    /**
     * \copydoc addValue(const RWDBExpr&)
     */
    RWDBInserter&       addValue(const RWDBBoundExpr& value);

    // adding scalar expressions, i.e. values, to insert

    /**
     * Adds a scalar expression to the encapsulated \c VALUES clause in
     * self, allowing values or scalar expressions to be inserted into a
     * table. The position that \a value holds is associated with the
     * current position within self. The current position is incremented
     * after adding the expression. If self was produced with an
     * RWDBSelector, sets self's status to RWDBStatus::invalidUsage. Returns
     * a reference to self.
     */
    RWDBInserter&       operator<<(const RWDBExpr& value);

    /**
     * Adds a variable expression to the encapsulated \c VALUES clause in
     * self where supported, thus allowing values or scalar expressions to
     * be inserted into a table. The position that \a value holds is
     * associated with the current position within self. The current
     * position is incremented after adding the expression. If self was
     * produced with an RWDBSelector, sets self's status to
     * RWDBStatus::invalidUsage. Returns a reference to self.
     */
    RWDBInserter&       operator<<(const RWDBBoundExpr& value);

    /**
     * Adds an #RWDBValueManip to the encapsulated \c VALUES clause in self.
     * #RWDBValueManip is a typedef and is typically used to insert a
     * literal \c NULL into the inserter. The position that \a manip holds
     * is associated with the current position within self. The current
     * position is incremented after adding the expression.
     *
     * Use \ref RWDBValue::rwdbNull "rwdbNull" to insert a literal \c NULL
     * into an inserter.
     */
    RWDBInserter&       operator<<(RWDBValueManip manip);

    /**
     * Adds the provided \a value as a literal in the encapsulated \c VALUES
     * clause in self. The position that \a value holds is associated with
     * the current position within self. The current position is incremented
     * after adding the value. If self was produced with an RWDBSelector,
     * sets self's status to RWDBStatus::invalidUsage. Returns a reference
     * to self.
     */
    RWDBInserter&       operator<<(const RWDBValue& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(char value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(unsigned char value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(short value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(unsigned short value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(int value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(unsigned int value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(long value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(unsigned long value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(long long value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(unsigned long long value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(float value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(double value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(long double value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const char* value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWDecimalPortable& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWDate& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWDateTime& value);

#if !defined(RW_DISABLE_DEPRECATED)
    /**
     * \deprecated
     * As of SourcePro 12.5, use RWDBInserter::operator<<(const RWDateTime&)
     * instead.
     *
     * \copydoc operator<<(const RWDBValue&)
     */
    RW_DEPRECATE_FUNC("Use operator<<(const RWDateTime&) instead")
    RWDBInserter&       operator<<(const RWDBDateTime& value);
#endif

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWDBDuration& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWCString& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWDBMBString& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWBasicUString& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWWString& value);

    /**
     * \copydoc operator<<(const RWDBValue&)
     */
    RWDBInserter&       operator<<(const RWDBBlob& value);

    /**
     * A row of data can be inserted directly from an RWDBReader into an
     * RWDBInserter. This method is equivalent to using a loop to extract
     * each value out of \a reader into \c inserter. Returns a reference to
     * self.
     */
    RWDBInserter&       operator<<(RWDBReader& reader);

    /**
     * Returns the current position, at which the next value will be shifted
     * in using the insertion operator. Returns #RW_NPOS if isValid()
     * returns false.
     */
    size_t position() const;

private:
    RWDBCountedRef<RWDBInserterImp> impl_;
};

#endif
