#ifndef __RWDB_UPDATER_H__
#define __RWDB_UPDATER_H__

/**************************************************************************
 *
 * $Id: //spro/rel2016.1/rw/db/updater.h#1 $
 *
 * Copyright (c) 1994-2016 Rogue Wave Software, Inc.  All Rights Reserved.
 * 
 * This computer software is owned by Rogue Wave Software, Inc. and is
 * protected by U.S. copyright laws and other laws and by international
 * treaties.  This computer software is furnished by Rogue Wave Software, Inc.
 * pursuant to a written license agreement and may be used, copied, transmitted,
 * and stored only in accordance with the terms of such license agreement and
 * with the inclusion of the above copyright notice.  This computer software or
 * any other copies thereof may not be provided or otherwise made available to
 * any other person.
 * 
 * U.S. Government Restricted Rights.  This computer software: (a) was
 * developed at private expense and is in all respects the proprietary
 * information of Rogue Wave Software, Inc.; (b) was not developed with
 * government funds; (c) is a trade secret of Rogue Wave Software, Inc. for all
 * purposes of the Freedom of Information Act; and (d) is a commercial item and
 * thus, pursuant to Section 12.212 of the Federal Acquisition Regulations (FAR)
 * and DFAR Supplement Section 227.7202, Government's use, duplication or
 * disclosure of the computer software is subject to the restrictions set forth
 * by Rogue Wave Software, Inc.
 *
 **************************************************************************
 *
 * Definition of class RWDBUpdater
 *
 * This class provides a standard interface to the specific database
 * implementation of "updaters", i.e. a class used to update data
 * in the database.
 * NOTE: RWDBUpdater's are constructed from a table or directly from
 *       a database.
 * For more information about the specific implementation,
 * see the header files for the specific database.
 *
 **************************************************************************/

#include <rw/db/dbase.h>
#include <rw/db/defs.h>
#include <rw/db/status.h>
#include <rw/db/table.h>

/**
 * \ingroup db_data_manipulation_group
 *
 * \brief
 * Encapsulates the SQL \c UPDATE statement.
 *
 * RWDBUpdater is an encapsulation of an SQL \c UPDATE statement. Its
 * methods provide an application with explicit control over the \c UPDATE
 * statement's \c SET and \c WHERE clauses.
 *
 * The insertion operator operator<<() is used to add encapsulated \c SET
 * clauses to an RWDBUpdater; the where() method specifies a \c WHERE
 * clause. The items that are inserted into an RWDBUpdater are
 * RWDBAssignment objects, created by the
 * \ref RWDBColumn::assign() "assign()" method of RWDBColumn. The \c WHERE
 * clause is encapsulated by an RWDBCriterion, which is some number of
 * RWDBExpr objects combined with logical operators.
 *
 * An \c UPDATE statement does not normally produce results. However, the DB
 * Interface Module recognizes that some database vendors provide triggers,
 * which can cause results to be generated by an \c UPDATE statement.
 * Consequently, the execute() method of RWDBUpdater returns an RWDBResult,
 * which is a sequence of zero or more RWDBTable objects. Applications are
 * not obliged to request any tables from the returned object.
 *
 * RWDBUpdater is designed around the Interface/Implementation paradigm. An
 * RWDBUpdater instance is an interface to a reference-counted
 * implementation; copy constructors and assignment operators produce
 * additional references to a shared implementation. An RWDBUpdater
 * implementation is a base class from which a family of database-specific
 * updater implementations is derived.
 *
 * \synopsis
 * #include <rw/db/updater.h>
 *
 * RWDBUpdater updater = myTable.updater();
 * \endsynopsis
 *
 * \sa
 * \parblock
 * The encapsulated \c WHERE clause of an RWDBUpdater is an RWDBCriterion,
 * which is composed of RWDBExpr objects. Each encapsulated \c SET clause is
 * an RWDBAssignment, produced by the \ref RWDBColumn::assign() "assign()"
 * method of RWDBColumn. See RWDBAssignment, RWDBCriterion, RWDBExpr, and
 * RWDBColumn for details.
 *
 * The result of RWDBUpdater::execute() is an RWDBResult, which represents a
 * sequence of zero or more RWDBTable objects. See RWDBResult and RWDBTable
 * for details.
 * \endparblock
 *
 * \example
 * <b>Example 1</b>
 *
 * This example uses an RWDBUpdater to increment the \c number column of the
 * \c Inventory table by \c 50 wherever \c red is found in the \c color
 * column.
 *
 * \code
 * RWDBTable inventory = myDbase.table("Inventory");
 * RWDBConnection connection = myDbase.connection();
 * RWDBUpdater update = inventory.updater();
 * RWDBColumn number = inventory["number"];
 * update << number.assign(number + 50);
 * update.where(inventory["color"] == "red");
 * update.execute(connection);
 * \endcode
 *
 * <b>Example 2</b>
 *
 * This example accomplishes the same task as Example 1, but provides
 * bindings to an application variable. This allows the application to
 * repeatedly execute the update with different values without reshifting in
 * values.
 *
 * \code
 * RWDBTable inventory = myDbase.table("Inventory");
 * RWDBConnection connection = myDbase.connection();
 * RWDBUpdater update = inventory.updater();
 * RWDBColumn number = inventory["number"];
 * int increment = 50;
 * RWCString color = "red";
 * update << number.assign( number + RWDBBoundExpr( &increment) );
 * update.where( inventory["color"] == RWDBBoundExpr(&color) );
 * update.execute(connection);
 * increment = 100;
 * color = "gold";
 * update.execute(connection);
 * \endcode
 * \endexample
 */
class RWDB_SYMBOLIC RWDBUpdater
{
public:
    /**
     * The default constructor creates an RWDBUpdater whose status is
     * RWDBStatus::notInitialized. This constructor is provided as a
     * convenience, for example, for declaring an array of RWDBUpdater
     * objects. Usable RWDBUpdater instances are obtained from RWDBTable
     * instances.
     */
    RWDBUpdater();

    /**
     * Copy constructor. Self shares an implementation with \a upd.
     */
    RWDBUpdater(const RWDBUpdater& upd);

    RWDBUpdater(RWDBUpdaterImp* imp);

    /**
     * Assignment operator. Self shared an implementation with \a upd.
     */
    RWDBUpdater& operator=(const RWDBUpdater& upd);

    ~RWDBUpdater();

    // accessors
    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * UPDATE table SET ... [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with an implicit RWDBConnection object. An implicit
     * RWDBConnection object inherits the time zone setting from the
     * producer RWDBDatabase instance. Hence, the time zone setting of the
     * producer RWDBDatabase object will be used for creating the string
     * representations of any RWDateTime instances in self.
     *
     * The behavior of this method depends upon the
     * RWDBDatabase::verboseAsString() setting in the producer RWDBDatabase
     * instance.
     *
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c false, the SQL returned is the same as that passed to the database
     * for execution. This is the default.
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c true, any placeholders in the returned SQL are replaced with their
     * bound values.
     *
     * \note
     * When the RWDBDatabase::verboseAsString() option is set to \c true,
     * the SQL returned by this method may not be a valid SQL statement.
     * However, this method's return value is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with
     * RWDBDatabase::verboseAsString() set to \c true will result in a
     * string with blob data returned as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBDatabase::timeZone(const RWZone*) for time zone setting on
     * RWDBDatabase.
     */
    inline RWCString asString() const
    {
        return rwAsString(table().database().timeZone(),
                          table().database().verboseAsString());
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * UPDATE table SET ... [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with \a conn. The time zone setting of \a conn will be
     * used for creating string representations of any RWDateTime instances
     * in self.
     *
     * The behavior of this method depends upon the
     * RWDBDatabase::verboseAsString() setting in the producer RWDBDatabase
     * instance.
     *
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c false, the SQL returned is the same as that passed to the database
     * for execution. This is the default.
     * - If \ref RWDBDatabase::verboseAsString() "verboseAsString()" is
     * \c true, any placeholders in the returned SQL are replaced with their
     * bound values.
     *
     * \note
     * When the RWDBDatabase::verboseAsString() option is set to \c true,
     * the SQL returned by this method may not be a valid SQL statement.
     * However, this method's return value is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with
     * RWDBDatabase::verboseAsString() set to \c true will result in a
     * string with blob data returned as hex numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBConnection::timeZone(const RWZone*) for time zone setting on
     * RWDBConnection.
     */
    inline RWCString asString(const RWDBConnection& conn) const
    {
        return rwAsString(conn.timeZone(),
                          table().database().verboseAsString());
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * UPDATE table SET ... [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with an implicit RWDBConnection object. An implicit
     * RWDBConnection object inherits the time zone setting from the
     * producer RWDBDatabase instance. Hence, the time zone setting of the
     * producer RWDBDatabase object will be used for creating the string
     * representations of any RWDateTime instances in self.
     *
     * The behavior of this method depends on the value of \a verbose, and
     * is independent of the RWDBDatabase::verboseAsString() setting.
     *
     * - If \a verbose is \c false, the SQL returned is the same as that
     * passed to the database for execution.
     * - If \a verbose is \c true, any placeholders in the returned SQL are
     * replaced with their bound values although the SQL passed to the
     * database for execution will not be affected.
     *
     * \note
     * The SQL returned by this method when \a verbose is \c true may not be
     * a valid SQL statement. However, this is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with \a verbose as
     * \c true will result in a string with blob data returned as hex
     * numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBDatabase::timeZone(const RWZone*) for time zone setting on
     * RWDBDatabase.
     */
    inline RWCString asString(bool verbose) const
    {
        return rwAsString(table().database().timeZone(),
                          verbose);
    }

    /**
     * Returns the SQL equivalent of:
     *
     * \code
     * UPDATE table SET ... [ WHERE ...]
     * \endcode
     *
     * This method returns an SQL statement that would be produced by
     * executing self with \a conn. The time zone setting of \a conn will be
     * used for creating string representations of any RWDateTime instances
     * in self.
     *
     * The behavior of this method depends on the value of \a verbose, and
     * is independent of the RWDBDatabase::verboseAsString() setting.
     *
     * - If \a verbose is \c false, the SQL returned is the same as that
     * passed to the database for execution.
     * - If \a verbose is \c true, any placeholders in the returned SQL are
     * replaced with their bound values although the SQL passed to the
     * database for execution will not be affected.
     *
     * \note
     * The SQL returned by this method when \a verbose is \c true may not be
     * a valid SQL statement. However, this is not necessarily the same SQL
     * that is sent to the database for execution. For example, if an
     * RWDBBlob object is bound, calling this method with \a verbose as
     * \c true will result in a string with blob data returned as hex
     * numbers, such as \c 0x0A32F5.
     *
     * \sa
     * RWDBConnection::timeZone(const RWZone*) for time zone setting on
     * RWDBConnection.
     */
    inline RWCString asString(const RWDBConnection& conn,
                              bool verbose) const
    {
        return rwAsString(conn.timeZone(), verbose);
    }

    RWCString           rwAsString(const RWZone& timeZone,
                                   bool verbose = false) const;
    /**
     * Returns the RWDBTable that produced self. Returns an RWDBTable whose
     * status is RWDBStatus::notInitialized if self was created with the
     * default constructor.
     */
    RWDBTable           table() const;

    /**
     * Sets self's current position to \a index.
     */
    RWDBUpdater&        operator[](size_t index);

    /**
     * Installs \a handler as self's error handler. The supplied \a handler
     * is inherited by all objects produced by self. By default, an
     * RWDBStatus::ErrorHandler is inherited from the object that produced
     * self; this method overrides the default.
     */
    void                     setErrorHandler(RWDBStatus::ErrorHandler handler);

    /**
     * Returns the error handler attached to self.
     */
    RWDBStatus::ErrorHandler errorHandler() const;

    /**
     * Returns the current status of self.
     */
    RWDBStatus               status() const;

    /**
     * Returns \c true if self's status is RWDBStatus::ok, otherwise returns
     * \c false. Does not return \c false if the previously executed
     * statement failed. In this case, you must check the status of the
     * RWDBResult returned from execute() instead of the status of the
     * RWDBUpdater object.
     */
    bool                isValid() const;

    /**
     * Returns \c true if the object is in ready state, indicating that
     * accessing the object will not block. Accessing a nonready object may
     * potentially block.
     */
    bool                isReady() const;

    /**
     * Attempts to acquire the internal mutex lock. If the mutex is already
     * locked by another thread, the function blocks until the mutex is
     * released. This function can be called from a \c const object.
     *
     * \note
     * In single-threaded builds, this function evaluates to a no-op.
     */
    void                acquire(void) const;

    /**
     * Releases a previously acquired mutex. This function can be called
     * from a \c const object.
     *
     * \note
     * In single-threaded builds, this function evaluates to a no-op.
     */
    void                release(void) const;

    /**
     * Uses a default database connection to execute the SQL statement
     * encapsulated by self.
     */
    RWDBResult          execute();

    /**
     * Uses the supplied \a connection to execute the SQL statement
     * encapsulated by self. This function can behave asynchronously if
     * executed using an asynchronous connection.
     */
    RWDBResult          execute(const RWDBConnection& connection);

    /**
     * Clears self's list of assignments, \c WHERE clauses, and internal
     * controls.
     */
    RWDBStatus          clear();

    /**
     * Adds the encapsulated \c SET clause represented by \a assignment to
     * self. Equivalent to inserting \a assignment into self. Returns a
     * reference to self.
     */
    RWDBUpdater&        set(const RWDBAssignment& assignment);

    /**
     * Specifies \a criterion as self's SQL \c WHERE clause. If self already
     * has a \c WHERE clause, this method replaces it. Specifying an empty
     * \a criterion clears self's \c WHERE clause. Notice that an updater
     * without a \c WHERE clause updates all rows in its table. Returns a
     * reference to self.
     */
    RWDBUpdater&        where(const RWDBCriterion& criterion);

    /**
     * Returns a copy of self's RWDBCriterion, an encapsulated SQL \c WHERE
     * clause. Returns an empty RWDBCriterion if self has no \c WHERE
     * clause.
     */
    RWDBCriterion   where() const;

    // Insertion operator. Synonym for set()
#ifndef RW_TRAILING_RWEXPORT
    /**
     * \relates RWDBUpdater
     *
     * Appends \a assignment to the encapsulated \c SET clause in \a upd.
     * Returns a reference to \a upd.
     */
    friend  RWDB_SYMBOLIC RWDBUpdater&    operator<<(RWDBUpdater& upd,
            const RWDBAssignment& assignment);
#else
    friend  RWDBUpdater& RWDB_SYMBOLIC    operator<<(RWDBUpdater& updater,
            const RWDBAssignment& assignment);
#endif


private:
    RWDBCountedRef<RWDBUpdaterImp>    impl_;
};
#endif
