#infranet.connection=pcp://root.0.0.0.1:@192.168.56.101:11960/0.0.0.1 /service/admin_client 1
infranet.login.type=1
infranet.log.file=./default.pinlog
infranet.log.level=1
infranet.log.logallebuf=true
# To enable SSL, make sure to provide correct values for below config entries. e.g wallet location and filename etc.
infranet.pcp.ssl.enabled = false
infranet.pcp.ssl.wallet.location = /home/pin/opt/portal/BRM/wallet/client
infranet.pcp.ssl.wallet.filename = cwallet.sso
