#!/tools/CGBU/contrib/DO/BRM/Perl/15.0.1.0.0/latest/linux/bin/perl
# Copyright (c) 1997, 2017, Oracle and/or its affiliates. All rights reserved.
#      This material is the confidential property of Oracle Corporation or its
#      licensors and may be used, reproduced, stored or transmitted
#      only in accordance with a valid Oracle license or sublicense agreement.


use Getopt::Std;
######################################################################
## Configuration stuff
######################################################################

$CONF_DBNAME="defiant";
$ORACLE_VERSION="Oracle8";

#--------------------------------------------
# end of configuration section
#--------------------------------------------
#=============================================================================
# check what operation system we are running on
# $^O will return name of OS
if ( $^O =~ /win/i )
{
# NT computer ( actually any windows operation system )
# Command to run sqlplus
$SQL_COMMAND     = "plus80 -s";
# For Windows NT Oracle 8 has a different batch sql processor
if ( $ORACLE_VERSION =~ /^Oracle8i$/i ) {
$SQL_COMMAND     = "sqlplus -s";
}

# Temporary directory to create files
$PIN_CONF_TEMPDIR     = "C:/temp";
}
else
{
# UNIX assignment
# Command to run sqlplus
$SQL_COMMAND       = "sqlplus -s";

# Temporary directory to create files
$PIN_CONF_TEMPDIR       = "/tmp";
}

($ME = $0) =~ s,.*/,,;

$sql_cmnd =<<SQLPLUSEND 
spool $PIN_CONF_TEMPDIR/data.lst;
set serveroutput on SIZE 1000000
DECLARE
-- set up cursors to fetch data from service_t
--
poidvalue NUMBER;
count INTEGER;
idx INTEGER;

cursor db_id is 
	select poid_id0 from service_t where login like 'netaccount%'; 

BEGIN

	-- db no
	count := 0;
	idx := 0;
	open db_id;
 FOR count IN 1..1000 LOOP
	fetch db_id into poidvalue;
	EXIT WHEN db_id%NOTFOUND;
        if ( idx > 4 ) THEN
          idx := 0;
        END IF;
        if ( idx = 0 ) THEN
	insert into service_broadband_ipaddrs_t values (poidvalue,1,'ip|156.151.0.0');
        END IF;
        if ( idx = 1 ) THEN
	insert into service_broadband_ipaddrs_t values (poidvalue,1,'ip|1.2.3.4');
        END IF;
        if ( idx = 2 ) THEN
	insert into service_broadband_ipaddrs_t values (poidvalue,1,'ip|127.123.2.3');
        END IF;
        if ( idx = 3 ) THEN
	insert into service_broadband_ipaddrs_t values (poidvalue,1,'ip|157.123.12.12');
        END IF;
        if ( idx = 4 ) THEN
	insert into service_broadband_ipaddrs_t values (poidvalue,1,'ip|206.245.190.166');
        END IF;
	idx := idx + 1;

 END LOOP;
        commit;
	close db_id;

END;
/

SQLPLUSEND
;

exec_sqlcommand($sql_cmnd);

###############################################################################
# exec_sqlcommand()
#       input:
#               sql command(s)
###############################################################################
sub exec_sqlcommand {
	local ($cmd) = @_;
	local ($status) = 0;
	local ($exitcode) = 0;
	local ($tmpfile) = "$PIN_CONF_TEMPDIR/pintmp$$.sql";
	# Create a temporary file with the sqlplus input.
	#
	open(TMPFILE, ">$tmpfile") || die "$ME: cannot create $tmpfile\n";
	print TMPFILE "$cmd";
	print TMPFILE "\nexit;\n";
	close(TMPFILE);

	$sqlout = `$SQL_COMMAND /\@$CONF_DBNAME < $tmpfile`;
	$exitcode = $?;
	$status = ($? >> 8);

        unlink "$tmpfile";

       if ($sqlout =~ m/ERROR: /) {
       print("$sqlout");
       print("$ME: SQLPLUS failed (exitcode = $exitcode)\n");
       exit(1);
       }

       #
       if ($status || $exitcode) {
       print("$ME: SQLPLUS failed with status $status\n");
       exit (1);
       }
}

1;


