#
# Copyright (c) 2003, 2021, Oracle and/or its affiliates. All rights reserved.
#
# This material is the confidential property of Oracle Corporation or its
# licensors and may be used, reproduced, stored or transmitted only in
# accordance with a valid Oracle license or sublicense agreement.
#

#infranet.connection=pcp://root.0.0.0.1:&aes|08|0D5E11BFDD97D2769D9B0DBFBD1BBF7E5D40C305EDF3D77DF111AAB8F781E92122@__CM_HOST__:__CM_PORT__/service/admin_client 1
infranet.login.type=1

#To turn on search restriction - Search Template ids can be set as a comma seperated list below
#( ref - BRM doc for imformation on search teamplate Id)   
#
#allowed.search.template.ids=None

#To turn on logging in the webservices
#
#webservices.log.enabled=true
webservices.input.validation.enabled=false
webservices.soap.input.validation.reportonly=true
webservices.output.validation.enabled=false
webservices.soap.output.validation.reportonly=true

#below input/output date format confirms to Java's SimpleDateFormat specification
#webservices.output.date.format=yyyy-MM-dd'T'HH:mm:ss
#webservices.output.date.prefixunixtstamp=false
#webservices.output.date.timezone=UTC
#webservices.input.date.format=yyyy-MM-dd'T'HH:mm:ss
#webservices.input.date.prefixunixtstamp=false
#webservices.input.date.timezone=UTC

wsm.audit.log.enabled=false

#infranet.custom.field.package=

#For PCM logging purposes - typically not required if you're using the
#webservices logging
#
#infranet.log.opcodes.enabled=true
#infranet.log.opcodes.file=opcodes.log

#
# SSL related entries
#
#infranet.pcp.ssl.enabled=true
#infranet.pcp.ssl.wallet.location=/path/to/wallet/directory
#infranet.pcp.ssl.wallet.filename=cwallet.sso
#infranet.pcp.ssl.handshake.timeout=30000

#infranet.PcmTimeoutInMsecs=0
#infranet.connectionpool.minsize=min_connections
#infranet.connectionpool.maxsize=max_connections
#infranet.connectionpool.timeout=connection_timeout

#To enable OAUTH Validation in OAM12c ,configure the following OAUTH parameters
#infranet.OAuthIDP=OAM12c
#infranet.OAuthAccessTokenUrl=http://<oam_managed_server_hostname>:<oam_managed_server_port>/oauth2/rest/token/info
#infranet.OAuthDomainName=<OamIdDomainName>


# To enable OAuth validation OAM11g , configure following OAuth parameters.
# OAuth validator related entries
#**********************************************************************************************
# The OAuth validation is performed by a OAM client, register a client on OAM server,
# and configure following client info.
#**********************************************************************************************  
#infranet.OAuthIDP=OAM11g

#infranet.OAuthAccessTokenUrl=http://ip address of OAM server:port#/ms_oauth/oauth2/endpoints/oauthservice/tokens
#infranet.OAuthClientId= Set Client id, which is added to act as OAuth validator
#infranet.OAuthClientSecret= set encrypted client secret 


# To enable OAuth validation with IDCS , configure following OAuth parameters.
# OAuth validator related entries
#**********************************************************************************************
# The OAuth validation is performed by a IDCS client, register a client on IDCS server,
# and configure following client info.
#**********************************************************************************************  
#infranet.OAuthIDP=IDCS

#infranet.OAuthAccessTokenUrl=http://ip address of IDCS server:port#/oauth2/v1/introspect
#infranet.OAuthClientId= Set Client id, which is added to act as OAuth validator
#infranet.OAuthClientSecret= set encrypted client secret 
#infranet.wallet.location=<set the location of the wallet to read clientSecret and clientId>

#OAuth default Grant properties
#Keep follwoing as defualt unless there are some changes in grant type or token action
#*********************************************************************************************
infranet.OAuthGrantType=oracle-idm%3A%2Foauth%2Fgrant-type%2Fresource-access-token%2Fjwt
infranet.OAuthTokenAction=validate

#Oauth introspection Parameters(oracle_token_attrs_retrieval)
#OAuth introspection is the same as access token validation but additional claims data is included inside the access token as part of the response.
#includes following prams with space :
#iss aud exp prn jti exp iat oracle.oauth.scope oracle.oauth.client_origin_id
#Refer oracle doc for more info on Oauth Introspection
infranet.OAuthTokenAttributes=iss%20aud%20exp%20prn%20jti%20exp%20iat%20oracle.oauth.scope%20oracle.oauth.client_origin_id%20oracle.oauth.user_origin_id%20oracle.oauth.user_origin_id_type%20oracle.oauth.tk_context%20oracle.oauth.id_d_id%20oracle.oauth.svc_p_n

# Modify following scope prefix,
#Use your resource id as a prefix. The resource id is a default prefix for all available scopes of a certain resource. 
# if an additional prefix is set in OAM,then resource scope prefix should be set appropriately.
#BRM OAuth resource scope definition /Example -
#BrmWebService should be configured as a resource in OAM,
#and may define all available webservices as allowed scope with a certain prefix
#For example -  scope = BRMWSM.BRMBalServices_v2, BRMWSM.BRMBillServices_v2 ;
#where BRMWSM is prefix(resource id/name) and BRMBalServices_v2 is the Webservice name as available in the BRMWebService Manager.
#*********************************************************************************************
infranet.ResourceScopePrefix=BRMWSM
