#!/bin/sh
# StateConfigTool.java
# Copyright (c) 2003,2021, Oracle and/or its affiliates. All rights reserved.
#
# This material is the confidential property of Oracle Corporation or
# its licensors and may be used, reproduced, stored or transmitted only
# in accordance with a valid Oracle license or sublicense agreement.
#
#

#PKG_HOME is root directory of PIPELINE install.
PKG_HOME=$IFW_HOME

JAVA=$JAVA_HOME/bin/java

JARS="$PIN_HOME/jars/pcm.jar:$PIN_HOME/jars/oraclepki.jar:$ORACLE_HOME/jdbc/lib/ojdbc8.jar"
for i in $PKG_HOME/tools/StateConfigTool/*.jar
do
	JARS="$JARS:$i"
done

for i in $PKG_HOME/tools/StateConfigTool/*.zip
do
	JARS="$JARS:$i"
done


$JAVA -cp "$JARS" com.solution42.intsmacc.db.datamigration.stateconfig.StateConfigTool $*
