INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'TEL', 'Telephony', 1, 'B', 'DURATION', '1420', NULL, NULL, 1, '/service/telco/gsm/telephony'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'GPRS', 'General Packet Radio Service', 3, 'B', 'TOTAL', '1450', NULL, NULL, 1, '/service/ip/gprs'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'WAP', 'Wireless Application Protocol', 4, 'B', 'VOLUME', '1460', NULL, NULL, 1, '/service/wap/interactive'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'SMS', 'Short Message Service', 2, 'E', 'DURATION', '1430', NULL, NULL, 1, '/service/telco/gsm/sms'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'*', 'dummy service (do not use!) - needed for ZoneModel wildcard', 99, 'L', 'DURATION'
, '1420', NULL, NULL, 1, '/service'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'DATA', 'GSM Data Service', 5, 'B', 'DURATION', '1420', NULL, NULL, 1, '/service/telco/gsm/data'); 
INSERT INTO IFW_SERVICE ( SERVICECODE, NAME, RANK, TOS, RUMGROUP, DEF_GLACCOUNT, DEF_REVENUEGROUP,
PARENT_SERVICE, BASIC, PIN_SERVICETYPE ) VALUES ( 
'FAX', 'GSM Fax Service', 6, 'B', 'DURATION', '1420', NULL, NULL, 1, '/service/telco/gsm/fax'); 
commit;
 
