INSERT INTO IFW_RUMGROUP_LNK ( RUMGROUP, RUM, UOM ) VALUES ( 
'DURATION', 'DUR', 'SEC'); 
INSERT INTO IFW_RUMGROUP_LNK ( RUMGROUP, RUM, UOM ) VALUES ( 
'VOLUME', 'SND', 'BYT'); 
INSERT INTO IFW_RUMGROUP_LNK ( RUMGROUP, RUM, UOM ) VALUES ( 
'VOLUME', 'REC', 'BYT'); 
INSERT INTO IFW_RUMGROUP_LNK ( RUMGROUP, RUM, UOM ) VALUES ( 
'TOTAL', 'DUR', 'SEC'); 
INSERT INTO IFW_RUMGROUP_LNK ( RUMGROUP, RUM, UOM ) VALUES ( 
'TOTAL', 'SND', 'BYT'); 
INSERT INTO IFW_RUMGROUP_LNK ( RUMGROUP, RUM, UOM ) VALUES ( 
'TOTAL', 'REC', 'BYT'); 
commit;
 
