INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'DEM', 280, 'German Mark'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'EUR', 978, 'Euro'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ADP', 20, 'Andorran Peseta'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AED', 784, 'UAE Dirham'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AFA', 4, 'Afghanistan Afghani'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ALL', 8, 'Albanian Lek'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AMD', 51, 'Armenian Dram'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ANG', 532, 'Netherlands Antillian Guilder'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AON', 24, 'Angolan Kwanza'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ARS', 32, 'Argentine Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ATS', 40, 'Austrian Schilling'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AUD', 36, 'Australian Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AWG', 533, 'Aruban Guilder'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'AZM', 31, 'Azerbaijanian Manat'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BBD', 52, 'Barbados Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BDT', 50, 'Bangladeshi Taka'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BEF', 56, 'Belgian Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BGL', 100, 'Bulgarian Lev'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BHD', 48, 'Bahraini Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BIF', 108, 'Burundi Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BMD', 60, 'Bermudan Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BND', 96, 'Brunei Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BOB', 68, 'Bolivia Boliviano'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BRL', 986, 'Brazilian Real'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BSD', 44, 'Bahamian Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BTN', 64, 'Bhutan Ngultrum'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BWP', 72, 'Botswanian Pula'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BYB', 112, 'Belarussian Ruble'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'BZD', 84, 'Belize Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CAD', 124, 'Canadian Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CHF', 756, 'Swiss Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CLP', 152, 'Chilean Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CNY', 156, 'Yuan Renminbi'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'COP', 170, 'Colombian Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CRC', 188, 'Costa Rican Colon'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CUP', 192, 'Cuban Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CVE', 132, 'Cape Verde Escudo'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CYP', 196, 'Cyprus Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'CZK', 203, 'Czech Koruna'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'DJF', 262, 'Djibouti Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'DKK', 208, 'Danish Krone'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'DOP', 214, 'Dominican Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'DZD', 12, 'Algerian Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ECS', 218, 'Ecuador Sucre'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'EEK', 233, 'Estonia Kroon'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'EGP', 818, 'Egyptian Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ESP', 724, 'Spanish Peseta'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ETB', 230, 'Ethiopian Birr'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'FIM', 246, 'Finnish Markka'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'FJD', 242, 'Fiji Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'FKP', 238, 'Falkland Islands Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'FRF', 250, 'French Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GBP', 826, 'British Pound Sterling'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GHC', 288, 'Ghanaian Cedi'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GIP', 292, 'Gibraltar Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GMD', 270, 'Gambian Dalasi'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GNF', 324, 'Guinea Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GRD', 300, 'Greek Drachma'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GTQ', 320, 'Guatemalan Quetzal'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GWP', 624, 'Guinea-Bissau Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'GYD', 328, 'Guyana Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'HKD', 344, 'Hong Kong Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'HNL', 340, 'Honduran Lempira'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'HRK', 191, 'Croatian Kuna'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'HTG', 332, 'Haitian Gourde'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'HUF', 348, 'Hungarian Forint'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'IDR', 360, 'Indonesian Rupiah'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'IEP', 372, 'Irish Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ILS', 376, 'Israeli Shekel'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'INR', 356, 'Indian Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'IQD', 368, 'Iraqi Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'IRR', 364, 'Iranian Rial'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ISK', 352, 'Iceland Krona'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ITL', 380, 'Italian Lira'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'JMD', 388, 'Jamaican Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'JOD', 400, 'Jordanian dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'JPY', 392, 'Japanese Yen'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KES', 404, 'Kenyan Shilling'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KGS', 417, 'Kyrgyzstan Som'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KHR', 116, 'Kampuchean (Cambodian) Riel'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KMF', 174, 'Comoros Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KPW', 408, 'North Korean Won'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KRW', 410, '(South) Korean Won'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KWD', 414, 'Kuwaiti Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KYD', 136, 'Cayman Islands Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'KZT', 398, 'Kazakhstan Tenge'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LAK', 418, 'Lao Kip'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LBP', 422, 'Lebanese Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LKR', 144, 'Sri Lanka Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LRD', 430, 'Liberian Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LSL', 426, 'Lesotho Loti'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LTL', 440, 'Lithuanian Litus'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LUF', 442, 'Luxembourg Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LVL', 428, 'Latvian Lats'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'LYD', 434, 'Libyan Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MAD', 504, 'Moroccan Dirham'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MDL', 498, 'Moldovan Leu'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MGF', 450, 'Malagasy Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MKD', 807, 'Macedonian Denar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MMK', 104, 'Myanmar Kyat'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MNT', 496, 'Mongolian Tugrik'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MOP', 446, 'Macau Pataca'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MRO', 478, 'Mauritanian Ouguiya'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MTL', 470, 'Maltese Lira'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MUR', 480, 'Mauritius Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MVR', 462, 'Maldive Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MWK', 454, 'Malawi Kwacha'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MXP', 484, 'Mexican Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MYR', 458, 'Malaysian Ringgit'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'MZM', 508, 'Mozambique Metical'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NAD', 516, 'Namibia Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NGN', 566, 'Nigerian Naira'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NIC', 558, 'Nicaraguan Cordoba'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NLG', 528, 'Netherlands Guilder'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NOK', 578, 'Norwegian Krone'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NPR', 524, 'Nepalese Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'NZD', 554, 'New Zealand Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'OMR', 512, 'Omani Rial'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PAB', 590, 'Panamanian Balboa'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PEN', 604, 'Peru Nuevo Sol'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PGK', 598, 'Papua New Guinea Kina'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PHP', 608, 'Philippine Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PKR', 586, 'Pakistan Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PLN', 985, 'Poland Zloty'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PLZ', 616, 'Polish Zloty'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PTE', 620, 'Portugese Escudo'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'PYG', 600, 'Paraguay Guarani'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'QAR', 634, 'Qatari Rial'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ROL', 642, 'Romanian Leu'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'RUR', 810, 'Russian Ruble'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'RWF', 646, 'Rwanda Franc'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SAR', 682, 'Saudi Riyal'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SBD', 90, 'Solomon Islands Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SCR', 690, 'Seychelles Rupee'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SDD', 736, 'Sudanese Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SEK', 752, 'Swedish Krona'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SGD', 702, 'Singapore Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SHP', 654, 'St. Helena Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SIT', 705, 'Slovenian Tolar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SKK', 703, 'Slovak Koruna'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SLL', 694, 'Sierra Leone Leone'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SOS', 706, 'Somali Shilling'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SRG', 740, 'Suriname Guilder'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'STD', 678, 'Sao Tome and Principe Dobra'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SVC', 222, 'El Salvador Colon'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SYP', 760, 'Syrian Pound'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'SZL', 748, 'Swaziland Lilangeni'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'THB', 764, 'Thai Baht'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TJR', 762, 'Tajik Ruble'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TMM', 795, 'Turkmenistan Manat'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TND', 788, 'Tunisian Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TOP', 776, 'Tongan Pa''anga'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TPE', 626, 'Timor Escudo'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TRL', 792, 'Turkish Lira'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TTD', 780, 'Trinidad and Tobago Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TWD', 901, 'Taiwan Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'TZS', 834, 'Tanzanian Shilling'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'UAK', 804, 'Ukraine Karbovanet'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'UGX', 800, 'Uganda Shilling'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'USD', 840, 'US Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'UYU', 858, 'Uruguayan Peso'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'UZS', 860, 'Uzbekistan Sum'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'VEB', 862, 'Venezualan Bolivar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'VND', 704, 'Vietnamese Dong'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'VUV', 548, 'Vanuatu Vatu'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'WST', 882, 'Samoan Tala'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'YER', 886, 'Yemeni Rial'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'YUN', 890, 'New Yugoslavian Dinar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ZAR', 710, 'South African Rand'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ZMK', 894, 'Zambian Kwacha'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ZRN', 180, 'Zaire Zaire'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES ( 
'ZWD', 716, 'Zimbabwe Dollar'); 
INSERT INTO IFW_CURRENCY ( CURRENCY, CURRENCY_ID, NAME ) VALUES (
'SDR', 999, 'SDR');
commit;
