######################################################################
#
# Copyright (c) 2000, 2009, Oracle and/or its affiliates. All rights reserved. 
#
#      This material is the exclusive property and trade secret of
#      Oracle Corporation. No part may be reproduced,
#      disclosed, stored in a retrieval system, or otherwise
#      transmitted in any form or by any means, electronic,
#      mechanical, photocopying, optical, magnetic, chemical,
#      biological, or otherwise, without prior written permission
#      of Oracle Corporation.
#
######################################################################

include ../../env.unix
include ../../Make.include.unix

all:
	$(JAVAC) -classpath $(CLASSPATH) *.java

clean:
	rm -f *.class
