#ifndef LRP_ENDOFSYMBOLINFO_HPP
#define LRP_ENDOFSYMBOLINFO_HPP

//==============================================================================
//
//          Copyright (c) 1996 - 2006 Oracle. All rights reserved.
//          
//          This material is the confidential property of Oracle Corporation or its
//          licensors and may be used, reproduced, stored or transmitted only in
//          accordance with a valid Oracle license or sublicense agreement.
//
//------------------------------------------------------------------------------
// Block: LRP
//------------------------------------------------------------------------------
// Module Description:
//   Declaration of the class EndOfSymbolInfo.
//
// Open Points:
//   <open points>
//
// Review Status:
//   in-work
//
//------------------------------------------------------------------------------
// Responsible: Stefan Deigmueller
//
// $RCSfile: EndOfSymbolInfo.hpp,v $
// $Revision: 1.1 $
// $Author: sd $
// $Date: 2001/07/04 08:39:17 $
// $Locker:  $
//------------------------------------------------------------------------------
// $Log: EndOfSymbolInfo.hpp,v $
// Revision 1.1  2001/07/04 08:39:17  sd
// - Initial revision
//
//==============================================================================

namespace FRM
{
class RecordDescr;
}
namespace LRP
{

/** <b><tt>EndOfSymbolInfo</tt></b> is used to store information about 
 *  end-of-symbol symbols that are automatically generated by the parser
 *  when for example ASN.1 streams are parsed.
 *
 * <p><table BORDER CELLSPACING=0 CELLPADDING=2 NOSAVE >
 *  <tr>
 *  <td><font size=-1>$RCSfile: EndOfSymbolInfo.hpp,v $</font></td>
 *  <td><font size=-1>$Revision: 1.1 $</font></td>
 *  <td><font size=-1>$Date: 2001/07/04 08:39:17 $</font></td>
 *  <td><font size=-1>$Author: sd $</font></td>
 *  </tr>
 *  </table>
 */
class EndOfSymbolInfo
{
  public:
    /**@name EndOfSymbolInfo.hpp constructors and destructor */
    //@{

    /** Constructor
     *  @param recordDescr The record description of the end-of-symbol record
     *  @param position Stream position where the symbol shall be generated
     */
    EndOfSymbolInfo( const FRM::RecordDescr* recordDescr, 
                         size_t                 position );

    /** Destructor
     */
    ~EndOfSymbolInfo();

    //@}


    /**@name EndOfSymbolInfo.hpp public methods */
    //@{

    /** Get the record description
     *  @return The symbol id
     */
    const FRM::RecordDescr* recordDescr() const;

    /** Get the position for the symbol
     *  @return The position
     */
    size_t position() const;

    //@}

  private:
    // Instance members
    const FRM::RecordDescr* recordDescrM;
    size_t                 positionM;
};

//==============================================================================
// Constructor
//==============================================================================
inline 
EndOfSymbolInfo::EndOfSymbolInfo( const FRM::RecordDescr* recordDescr, 
                                          size_t                 position )
  : recordDescrM( recordDescr ),
    positionM( position )
{
  RWPRECONDITION( recordDescrM != 0 );
}

//==============================================================================
// Destructor
//==============================================================================
inline 
EndOfSymbolInfo::~EndOfSymbolInfo()
{
}

//==============================================================================
// Get the symbold id
//==============================================================================
inline const FRM::RecordDescr*
EndOfSymbolInfo::recordDescr() const
{
  return recordDescrM;
}

//==============================================================================
// Get the position of the symbol
//==============================================================================
inline size_t
EndOfSymbolInfo::position() const
{
  return positionM;
}
}
#endif // ENDOFSYMBOLINFO_HPP
